seed/tasks.py
seed/tests/test_matching.py

There was an issue with some addresses having leading zeros.  After talking with Robin added a change to _normalize_address_str to do a lstrip(0) on the house field to remove leading zeros from the normalized address.  Leading zeros still appear in building data just not used for matching.  Added a test to test_strip_leading_zeros to test for this: test_strip_leading_zeros

Fix for issue where some records may have leading zeros in address causing match to fail.

---

seed/tasks.py
seed/tests/test_tasks.py

Now uses the column order in the original file for the order of the headers.  Made the change to cache_first_line.  See notes there.  It would be better to patch MCM per the comments I left in the code but this should fix the issue until that can be done.

Fix for issue 24: set field order in mapping based on imported data.

---

seed/static/seed/partials/mapping.html

Preventing two sets of headers from appearing in the mapping table

Avoiding duplicate headers

---

seed/views/main.py

Seems to also deal with remembering the mapping for non-pm files.  Tested by taking a file and changing a header slightly (Address -> Addresz) and seeing that when imported as a CSV it suggests "Address Line 1" and when imported as a PM file it suggests "Addresz".  Verified matching memory for CSV files by importing a file and defining a strange mapping (UBI -> Bob) and then re-importing the file and seeing that the mapping suggestion is preserved.

Re-enabled code to do fuzzy mapping on non-pm files.

---

seed/tasks.py

MCM parser is doing some processing behind the scenes to replace superscripts.  So when I replaced the code that iterated through the (modified) headers that each row in the parser has with code that uses the original header those original headers had some differences causing a lookup error.  Added a call to the same processing so that now column names from the file are still in file order but have been processed the same so their names agree with the headers for each row again.

Fix for Issue 169 (problem with importing files with superscripts in header) 

---

seed/data/pm-mapping.json

Re-generated the pm-mapping.json file from the Translation of PM to SEED fields 2015_03-13.xlsx file.  Robin added missing data types.  Added rules to include all rows from the file:  
1:  If BEDES field name is blank use PM native field name.  
2:  If BEDES version is blank set bedes field in json to false.

Re-generated the pm-mapping.json file

---

seed/tasks.py
seed/tests/test_matching.py

Formats address to use the abbreviated street type names, e.g. "Street" to "St". 
As described in pull request [https://github.com/SEED-platform/seed/pull/163], also see Issue[https://github.com/SEED-platform/seed/issues/25].

Add formatter for normalized address to compare abbreviations.

---

seed/search.py
seed/tests/test_views.py

Allow matching of exact queries by surrounding them in quotes. Allow matching for empty fields by supplying an empty `""` as the search query.
Fixes #20

Issue #20 - Exact and empty matching on search fields.

---

README-osx.md

cleaned up the install instructions for OSX. I wasn't sure if this file or the [wiki](https://github.com/SEED-platform/seed/wiki/Development-version-of-SEED-on-a-Mac-OSX) was the 'truth'. If it is the wiki, then we should remove this file.

cleanup osx instructions

---

seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/search_service.js

Save the building sort column and sort order selections in sessionStorage, so they aren't lost when navigating back and forth between building list and detail views.
Refs #12

Issue #12 - Save building sort column and order in sessionStorage

---

seed/views/main.py

@RDmitchell 
I didn't previously notice our changes affecting the progress requests of any actions other than uploading, but this change will allow any functions expecting the old format to continue to function.
Basically, the cache previously stored only a number to represent progress, e.g. 100, but now it stores a dictionary in order to communicate additional information asynchronously to the front end.  This change allows it to continue to accept ints or floats for the time being.
Fixes #232

Making the progress API backwards compatible

---

seed/static/seed/js/seed.js
seed/static/seed/js/services/search_service.js

Builds off of PR #222 
Save the building filter parameters in sessionStorage, so they aren't lost when navigating back and forth between building list and detail views.
Refs #12

Issue #12 - Save building filter params in sessionStorage

---

mcm/tests/test_reader.py
seed/tests/test_decorators.py

This updates the MCM tests to correctly locate the test files, and updates the progress cache tests

Fixing MCM and progress cache test failures

---

seed/search.py
seed/static/seed/js/controllers/matching_controller.js
seed/static/seed/partials/matching_list_table.html
seed/static/seed/tests/matching_controller.spec.js

This series of commits implement a drop-down component (i.e. select element) on the "matching" page. 
Included is a fix for a method in search.py, which was preventing the filter from working correctly (regardless of whether we used the old radio buttons or new pulldown).
Also included is a series of tests added to the units tests for the controller in matching_controller.spec.js. These three tests exercise the update_show_filter function in the controller. I'm not sure yet how to write an integration test to actually update the pulldown directly in the UI and confirm the resulting data shown on the page.

Fix for issue #51(plus a fix to search.py)

---

seed/lib/mcm/mapper.py
seed/lib/mcm/tests/test_mapper.py
seed/search.py
seed/tests/test_views.py

Add blank fields to building extra data json data. Previously, empty fields were excluded from the json data. This patch also updates the null filtering on json data to handle this new case and be backwards compatible with old data.
Fixes #247

Issue 247 - Rework of JSON Blob extra_data field

---

seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/search_service.js

This PR reintroduces the saving of filters from PR #235 , but takes care of the issues in #243 by prepending a prefix based off the current url. This makes it so that saved filters will be different when on the buildings page vs individual project pages. 
As this deals with the complex filtering params, this needs solid testing around all filtering and ordering. I tried with buildings and with individual projects with success.
Refs #12

Issue #12 - Remember filter settings redo

---

seed/mappings/mapper.py
seed/migrations/0002_buildingsnapshot_duplicate.py
seed/models.py
seed/static/seed/js/controllers/data_upload_modal_ctrl.js
seed/static/seed/js/controllers/mapping_controller.js
seed/static/seed/js/controllers/matching_controller.js
seed/static/seed/js/services/building_service.js
seed/static/seed/partials/building_audit_log.html
seed/static/seed/partials/data_upload_modal.html
seed/tasks.py
seed/templates/seed/_js_urls.html
seed/tests/test_tasks.py
seed/tests/test_views.py
seed/urls/main.py
seed/utils/buildings.py
seed/utils/constants.py
seed/views/main.py

Should have changes for both uploading duplicate data (Issue #83) and providing a changelog for merging buildings.
NOTE:  This involves a database migration so need to do
python manage.py makemigrations --settings=config.settings.dev
python manage.py migrate --settings=config.settings.dev
Added a 'duplicate' column to BuildingSnapshots table. Updated front end to display number of duplicates and tell user they will not be used. Added and modified unit tests. Added API endpoint to delete duplicate records for a given input file. NOTE: The raw import records are not being deleted in order to retain functionality in the review mapping screen.
Note on how rows are added to BuildingSnapshot table when a record is importing (prior to these changes):
1:  Pre-mapping:  A raw BuildingSnapshot …

Issue 83 uploading duplicate data

---

seed/static/seed/partials/matching_list_table.html

Extra data fields were not handled correctly in the DOM for the matching view table. I added checks to handle both string and numeric cases of the JSON data. 
Energy star & organization extra data fields shown:
Zip extra data field shown:
Refs #325

Issue #325 - Handle extra data fields on matching table

---

.coveragerc

Made some changes to our coverage config to get a more accurate report. Basically don't check test files, migrations, or debug code. Looks like we're close to 70% coverage.

Better coverage reporting settings

---

README.md

Pin the travis status image to develop branch. Currently, the image just shows the status of the last build, which isn't really helpful when it's from a random PR or branch.

Fix travis status image for develop branch

---

seed/search.py
seed/tests/test_views.py

An unnecessary change I made while working on empty and not empty filters caused a bug in the projects label filtering. This PR reintroduces the catch for empty filter values and adds a regression test for this odd case.
Refs #243

Issue #243 - Reintroduce excluding empty query values

---

seed/views/main.py

to return a confidence of 100 on fields for a file that has already been matched.  Otherwise non-pm fields in a PM file would have a confidence of 0 even after matching causing them to not be displayed at the review mappings screne.  This should make reviewing the mappings behave as expected and since users can not re-map files that have been matched then hopefully any other impact will be minimal.

Changing get_column_matching_suggestions 

---

seed/static/seed/js/controllers/building_detail_controller.js
seed/utils.py

There are a few different lists of fields to ignore that govern which fields from the BuildingSnapshot table are processed/displayed.  Missed a couple in the last commit, adding them here.

Removing the "duplicate" field was being displayed in the building details

---

seed/decorators.py
seed/search.py
seed/static/seed/js/directives/beUploader.js
seed/static/seed/partials/data_upload_modal.html
seed/tasks.py
seed/templates/seed/base.html
seed/tests/test_decorators.py
seed/tests/test_views.py
seed/utils/buildings.py
seed/utils/cache.py

This PR removed the vast majority of direct cache.set/cache.get calls, and centralized them in a new cache utility that standardizes format, functionality, and let's us easily debug any time the cache is modified.
It also lets us control timeouts, if desired, and has one new functional change - any time a progress key is read, the timeout is reset to keep the key alive.
Please run through the normal tests and make sure I didn't break any caches - I ran the tests and haven't seen any issues myself.

Centralized caching

---

config/settings/main.py

Remove the config for the Woopra domain. This stops django-analytical from putting the tracking code in the DOM. I don't see any dependency issues, as local dev never includes it anyway.
Refs #90

Issue #90 - Remove woopra

---

requirements/base.txt
seed/tasks.py
seed/tests/test_matching.py

Handle directions in address normalization. Probably still some odd cases that need worked out, but this gets the basics. Eg both `100 Main S` and `100 Main South` will return the same result, but `100 Main` and `100 Main S` will be different.
Reworked the tests using a metaclass so you can simply add cases, and they will register as separate test methods and fail independently. 
refs #315

Issue #315 - Address direction normalize

---

seed/data/pm-mapping.json

Partial solution to Issue[https://github.com/SEED-platform/seed/issues/364] since there are field names that are showing as duplicates. We decided to exclude 3 field names that are causing the duplicate field name check to trigger. 
Below is the current mapping without the 3 field names.

Append partial list of PM Webservices field names to mapping json

---

pytest.ini

The `pytest.ini` file which is used for running the test suite using `pytest` was still pointing at the `BE` python module.
I updated the `DJANGO_SETTINGS_MODULE` value to point to `config.settings.test` which is the correct python path for the test settings

Fixes pytest.ini to point to the correct DJANGO_SETTINGS_MODULE

---

seed/tasks.py

I encountered this bug while doing investigatory work on #386 
When trying to execute the building matching phase of data import, I was getting an error because `lower()` was being called on `None` in the `_find_matches` function.
```
[2015-09-23 12:20:33,918: ERROR/MainProcess] Task seed.tasks._match_buildings[626978cc-7f2d-4c4d-941e-9bc5e854f937] raised unexpected: AttributeError("'NoneType' object has no attribute 'lower'",)
Traceback (most recent call last):
File "/Users/piper/python-environments/seed/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/Users/piper/python-environments/seed/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
return self.run(*args, **kwargs)
File …
```

Account for null values in the normalized connonical building address

---

seed/views/main.py

Even though the query initially run specifies a date range that is abandoned to walk the tree of a canonical building's parents.  Since this is using the tree there may be some other records with no year_ending date.  Added a check to ignore them from processing.

Fix for Issue 402.  Added check to make sure records have year_ending

---

seed/tasks.py
seed/tests/test_matching.py

Handle parsing error for complex multi direction addresses like `M St., N St., 4th St., Delaware St., SW`. Catch the error and return the original address so the import doesn't crash.
Refs #424

Issue #424 - Handle usaddress parsing error

---

requirements/base.txt
samples/demo_app/requirements.txt
samples/demo_app/setup.py
samples/demo_app/stats/views.py
seed/audit_logs/views.py
seed/cleansing/views.py
seed/data_importer/views.py
seed/decorators.py
seed/landing/views.py
seed/static/seed/js/services/auth_service.js
seed/static/seed/js/services/organization_service.js
seed/static/seed/js/services/project_service.js
seed/static/seed/js/services/uploader_service.js
seed/static/seed/js/services/user_service.js
seed/views/accounts.py
seed/views/api.py
seed/views/main.py
seed/views/meters.py
seed/views/projects.py

Add some logic to the `ajax_request` decorator to check status responses, and return correct status codes. I also removed the `render_to` import from `django-annoying`, and was able to remove `django-annoying` entirely.
On the FE, remove all the redundant status message checks. These are no longer necessary because the error method should now be triggered.
On the BE, it seems that two styles for status are used:
- `'status':'success'`
- `'success':True`
I didn't try to normalize all of these yet, as I feel like it would take me down a long rabbit hole of test fixing. But this is something we should keep in mind.
Refs #437

Issue #437 - API endpoint status codes

---

seed/static/seed/less/style.less
seed/static/seed/partials/accounts.html
seed/static/seed/partials/building_area_section.html
seed/static/seed/partials/building_audit_log.html
seed/static/seed/partials/building_contacts_section.html
seed/static/seed/partials/building_detail_section.html
seed/static/seed/partials/building_energy_section.html
seed/static/seed/partials/building_projects_section.html
seed/static/seed/partials/buildings.html
seed/static/seed/partials/buildings_table.html
seed/static/seed/partials/dataset_detail.html
seed/static/seed/partials/home.html
seed/static/seed/partials/matching_detail_table.html
seed/static/seed/partials/matching_list_table.html
seed/static/seed/partials/members.html
seed/static/seed/partials/project_detail.html
seed/static/seed/partials/sub_org.html
seed/templates/seed/_header.html

A lof of 'a' tags have unnecessary href='javascript:void(0);" attributes alongside things link ng-click. These void calls are causing problems with jquery. 
According to Angular documentation, we can just get rid of the href in these instances as they're not needed. (See "Example" section here https://docs.angularjs.org/api/ng/directive/ngHref)

Removed href='javascript:void(0);' attributes from 'a' tags

---

requirements/base.txt
seed/audit_logs/migrations/0001_initial.py
seed/audit_logs/migrations/0003_auto_20151105_1539.py
seed/audit_logs/models.py
seed/landing/migrations/0001_initial.py
seed/landing/migrations/0002_auto_20151105_1539.py
seed/landing/models.py
seed/lib/exporter.py
seed/managers/json.py
seed/migrations/0001_initial.py
seed/migrations/0003_auto_20151105_1539.py
seed/models.py
seed/search.py
seed/tests/test_views.py
seed/views/main.py

Upgrade from an unmaintained postgres json field package to a newer one. Fix some hacks I had to do because of the old package and lack of support for fancy queries on json fields.
- Old migrations were updated to use the newer package. This feels dirty, but I don't see any other way because the old package was being imported.
- Added a `default={}` to any JsonFields used. Old package did this automatically as far as I can tell.
- Added new migrations for the changes. These won't change data. They're just for housekeeping.
Refs #465

Issue #465 - Update postgres json field package & fix hacks

---

seed/tasks.py
seed/tests/test_matching.py

Fixes https://github.com/SEED-platform/seed/issues/317
Addresses that are declared as ranges were not being normalized or parsed correctly.
All of the following should be normalized to the same canonical form `310-310 green st`
* `300-310 green st`
* `300 - 310 green st`
* `300/310 green st`
* `300 310 green st`
* `300-10` green st`  (omits the leading digit on the second number)
The numeric portion of the address is now passed through a normalization function `seed.tasks._normalize_address_number` which uses a regex to detect numeric ranges and normalize them.

Add normalization rules for address ranges

---

docs/source/conf.py

The documentation configuration hadn't been updated since the AppRegistry was introduced in django 1.7.  This was causing some automated imports to trigger the registry not ready exception.
Manually imported and called `django.setup`

Fix building of the documentation

---

config/settings/dev.py

Automated builds with ReadTheDocs were closer with the merge of #496, but it was failing due to the DOMAIN_URLCONFS not being defined in the Settings dictionary.  This wasn't defined because on ReadTheDocs, there won't be a local_untracked.py file, and the dev.py file did not include an initialization of this variable.  For development/deployment, when local_untracked.py _is actually present_, the value will be overwritten with whatever the dev has defined in local_untracked.py.
To complete the RTD automated builds, the following steps are needed if they aren't already present:
I believe that is it.  At that point, each commit to https://github.com/SEED-platform/seed will trigger a new build of the docs.  
Thanks
FYI @nllong

Fix Automated ReadTheDocs Builds

---

seed/search.py

This makes the query use the `AND` operator on the supplied labels.

make the label query use the AND operator

---

README.md

Here is the addition of the badges (in action [here](https://github.com/Myoldmopar/seed/tree/AddRTDBadges#standard-energy-efficiency-data-seed-platform)).  The stable badge is showing red because:
- The master branch hasn't been updated with the fixes in develop, and that will happen at release time
- ReadTheDocs may need some update to point to the master branch for stable

Add badges for stable and latest

---

.travis.yml

The project was not taking advantage of some easy to implement changes to speed up travis-ci test runs.
- [caching pip downloads](https://docs.travis-ci.com/user/caching/)
- [using docker-container based builds](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure)
Added two lines to the travis-ci configuration to enable these features.
Worth looking at the test runs to see what the actual increase in speed is before blindly merging this.

Speed up tests runs on travis by caching pip requirements and using Docker

---

seed/tasks.py

https://github.com/SEED-platform/seed/issues/273
Some of the code within `seed.tasks._match_buildings` didn't account for a possible null value, and was treating it as if it was a string.
Simple conditional statement.  The location of this code is pretty deep in a big method.  This is a pretty strait forward fix so I opted to just toss it in without the large overhead that would go into covering this with a test.  Alternatively, this code could be injected into the `_find_matches` function, but I was a little hesitant to change it's behavior.

Account for null addresses during matching

---

seed/migrations/0010_auto_20151204_1337.py
seed/migrations/0011_auto_20151209_0821.py
seed/models.py
seed/tests/test_organization_utils.py
seed/utils/organizations.py

Each organization needs to have a set of default labels created for it.  This was implemented as a data migration initially which created all of the default labels for existing organizations.  Newly created organizations after this migration has run however would not have any labels.
Added creation of the default labels to the `seed.utils.organizations.create_organization` utility function.  This function is to create organizations from the API endpoint through which organizations are created.
> Note that I chose this method over using something like a `post_save` signal because of my experience in the past with signals creating highly complex interactions between applications that are difficult to diagnose.  Since this functionality's primary use case is to populate a default set of …

Make organization creation also populate default labels

---

seed/static/seed/js/controllers/building_list_controller.js
seed/tasks.py
seed/views/projects.py

API requests for creating projects, adding building to projects, and removing buildings from projects relied on a cache which could be initialized without a status using [`set_cache_raw`](https://github.com/SEED-platform/seed/blob/develop/seed/utils/cache.py#L9) but then would later be reset using [`set_cache`](https://github.com/SEED-platform/seed/blob/develop/seed/utils/cache.py#L17). This lead to an error when [line 30](https://github.com/SEED-platform/seed/blob/develop/seed/utils/cache.py#L30) was executed, assuming that the key had been created using `set_cache` and that it thus had a dictionary key for 'status'. This is noted in issue #527. The behavior of not being able to add projects is noted in issue #497. 
Issue #527 is still outstanding. There are a number of ways of …

Updating caching methods for project control via api.

---

seed/static/seed/js/controllers/building_list_controller.js
seed/tasks.py
seed/views/main.py
seed/views/projects.py

The export progress api call would never complete synchronously (and potentially asynchronously) due to the cache not being updated properly.
The same way the data-import process was; explicitly caching information that can be updated in an asynchronous mode, and ensuring the cache is set to a completed state at the end of the celery task queue so that in a synchronous mode the task still registers as completed. This is an unfortunate consequence of the need for CELERY_ALWAYS_EAGER to be set for CI tests. 
This is an extension of PR #528. I'm not sure what the preferred method of merging this in is a result, but if @mmclark want's me to re-submit it after PR #528 is merged that is a very easy task.
@danielmcquillen @pipermerriam Could one of you verify that this is working for you? I …

Updating caching for export & caching control via api.

---

.travis.yml
seed/tasks.py
seed/tests/test_tasks.py

A possible fix for #521
DO_NOT_MERGE
The function `seed.tasks.get_canonical_id_matches` is responsible for looking up other building snapshots which are a match based on the three fields `pm_property_id`, `tax_lot_id`, and `custom_id_1`.  The current implementation is written such that it will match buildings that have *any* of these fields in common, or even snapshots which have a `pm_property_id` that is equal to another snapshot's `tax_lot_id`.
I'm not actually sure that the logic is *wrong*, but I do know that it is wrong for the desired functionality of #487 since it will always result in buildings that were split based on their tax id being re-merged due to something like a common `pm_property_id` or `custom_id_1`.
Instead of doing a query that matches any of these, the query has …

Fix overmatching of buildings

---

seed/search.py

The query being performed when filtering by multiple labels was not working as expected.  Even if a building had both labels assigned, the query would not return that building.
After some basic experimentation an alternate way of querying via AND-ing querysets together did produce a database query that returned the appropriate results.
Here is a gist of the SQL produced by the two different query methods.  https://gist.github.com/pipermerriam/afd2a87a1b17ad10efc4

Fix multi-label filtering

---

seed/static/seed/js/services/search_service.js

On the FE, the `search_service` service calls its method `select_or_deselect_all_buildings` whenever A) the select all checkbox is toggled or B) `search_buildings` is called in order to get results from the server, after which (if successfully returned) the `update_results` method is called, which in turn calls `select_or_deselect_all_buildings`
Meanwhile, the `selected_buildings` array holds a list of building IDs for buildings that have been selected. By definition is should be empty if no buildings are selected **or** if the 'select all' checkbox has been selected.
In the A case above, the `selected_buildings` array is always initialized to an empty array before calling `select_or_deselect_all_buildings`, but in case B this array isn't set to empty even though …

Clear out selected_buildings when select_or_deselect_all_buildings

---

seed/static/seed/js/controllers/menu_controller.js
seed/static/seed/js/services/label_service.js
seed/views/labels.py

https://github.com/SEED-platform/seed/issues/560
The new labeling functionality didn't handle users with multiple organizations correctly.  It was always using `user.orgs.first()` when it should have really been using the `organization_id` that was currently active for the user.
Fixed the organization selector to actually work, after which I modified the `label_service` to always send through `organization_id` as a query parameter.  Then within the two label api views, the organization used is fetched from that organization id.

Handle users with multiple organizations correctly with labels

---

seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/js/controllers/mapping_controller.js
seed/static/seed/js/services/search_service.js
seed/static/seed/partials/project_detail.html

https://github.com/SEED-platform/seed/issues/553
Selected buildings that fall outside of a new filter change were not being deselected.
For example, a user might filter once and see four buildings (rows). They might select all four, filter again, and then see two buildings (rows) that are selected. The user might then assume only two buildings were selected, when in fact all four were still selected.
Added a method to `search_service` to explicitly deselect all selected buildings, in the process clearing out the `selected_buildings` array and setting `select_all_checkbox` to false.
This method is now called by controllers after the user updates filters and before the controller calls for a new search.
It was agreed that, in a future iteration, we should revisit the concept of updating …

Fix 'unseen selected buildings' issue after filters are updated

---

seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/partials/buildings.html

https://github.com/SEED-platform/seed/issues/593
In the latest SEED build, at the end of the 'Add to existing project' process on the buildings list, the "View project" button wasn't showing the updated project view when clicked.
To the best of my knowledge, what is happening is that the pulldown shown in the 'select existing project' modal is nulling out the $scope.project property. It does this after the entire add process is complete and the controller has called the project_service to reload the projects. When that happens, the UI select control reloads and nulls out the $scope.project due via its binding.
This behavior is not seen in the current production build, but that could be because of changes to Angular and related libraries in the newer versions we are now using.
I created a …

Update controller and view fix missing .project bug

---

config/settings/common.py
seed/pagination.py
seed/static/seed/partials/buildings.html
seed/tests/test_labels_api_views.py
seed/views/labels.py

https://github.com/SEED-platform/seed/issues/601
The response from the `get_labels` api was being paginated.  This kept the front end from seeing any labels that weren't on the first page.
Removed the pagination since this endpoint should *in theory* not have an overly large number of results.

Removes pagination from labels list view

---

seed/cleansing/tests.py
seed/tasks.py

https://github.com/SEED-platform/seed/issues/603
Tax lot ID needs to be cast to a string prior to normalization
I cast it to a string

ensure that tax_lot_id is stringified before normalization

---

seed/cleansing/tests.py

The test `seed/cleansing/tests.py::test_cleanse` was constructing a list using `[v for v in some_dict.values()]`.  Since dictionaries are not ordered, when this was later checked to be equal to another list of the expected values, the items didn't end up being in the same order and thus the equality check failed.
Instead of using `self.assertEqual` which requires true equality, the test now uses [`self.assertItemsEqual`](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual) which ensures that the items in the two iterables are the same (independent of ordering).

fix non-deterministic test case

---

seed/mappings/mapper.py
seed/tests/test_models.py

Data found in the `extra_data` field(s) would be overridden if new data was uploaded that contained blank values.
Changed the logic in `seed.utils.mapper.merge_extra_data` to not clobber existing data with blank data.

Don't override extra data with blank data

---

seed/filters.py
seed/managers/json.py
seed/mappings/seed_mappings.py
seed/public/models.py
seed/search.py
seed/token_generators.py
seed/urls/labels.py
seed/utils/api_client.py
seed/utils/visualization.py
seed/views/main.py
seed/views/projects.py

Issue #627 
If you were trying to add a label while sorting on a field that was in the `extra_data` section of the building a 500 was thrown.  This was due to how sorting was implemented on extra-data fields which results in a `list` type being returned.
Later in the code, it was have `.filter()` called on it which resulted in an `AttributeError`
Sidestepped the bug by adding a new parameter to the `orchestrate_search_filter_sort` helper function to allow skipping the sort portion of that function's logic.

Fix 500 error when fetching labels

---

seed/search.py
seed/tests/test_views.py
seed/utils/search.py

Enables case insensitive filtering on building list via `^""` carat syntax. `^"test"` would match any case of `test`.
Refs #546

Issue #546 - Case insensitive match with carat symbol

---

seed/search.py

Incorrect null syntax in filter fields will throw an error. This is a first step patch to at least not give a 500 back from the server. Return no results on invalid syntax.
Refs #595

Issue #595 - Catch invalid operator errors and return nothing.

---

seed/static/seed/js/controllers/building_detail_controller.js
seed/static/seed/js/controllers/building_detail_update_labels_modal_ctrl.js
seed/static/seed/js/seed.js
seed/static/seed/partials/building_detail_section.html
seed/static/seed/partials/building_detail_update_labels_modal.html
seed/templates/seed/_scripts.html

We wanted a way to edit labels for a specific building on the building detail page.
Adds editing label functionality on the building detail page. Uses the same assets and modal and flow as the list page.
I posed a question [here](https://github.com/SEED-platform/seed/issues/515#issuecomment-173778067) about when the add/remove labels button should be shown. I implemented it in a way that shows the "add/remove labels" button as soon as you land on the building detail page. I think this feels correct.
Edit labels on building detail page.
Refs #515

Issue #515 - Building detail page edit labels

---

config/settings/common.py
seed/serializers/celery.py
seed/tasks.py

PR #669 switched celery's serialization from pickle to JSON. A case was missed where datetime objects sometimes need to be serialized.
Adds a custom JSON serializer to handle datetimes, and use this serializer in celery tasks. Datetimes are encoded as ISO8601 in this implementation.
Upload a spreadsheet with date objects.
Refs #432 #669

Issue #432 - Custom celery JSON serializer to handle datetimes

---

seed/static/seed/js/services/dataset_service.js

Renaming data sets was broken unless you were flagged as a Django superuser. The endpoint needs the `organization_id` passed along.
I don't have any tests for this, but it's a good candidate for a selenium test. Not sure if those are ready. 
Refs #634

Issue #634 - Renaming data set fix

---

seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/partials/buildings.html

New matched/unmatched dropdown on building list page was not respecting cached sessionStorage filter params. This fixes the issue.
Refs #581

Issue #581 - Matching dropdown should respect sessionStorage

---

seed/views/labels.py

https://github.com/SEED-platform/seed/issues/627
A bug in django-pgjson was resulting in a query that *should* have worked failing.
https://github.com/djangonauts/django-pgjson/issues/35
Instead of letting the django orm do it's magic, I cast the subquery to a tuple to force evaluation and bypass the bad code.
It's worth noting that if we can get switched over to Django 1.8 we can drop this 3rd-party dependency entirely in favor of `django.contrib.postgres` based fields which are likely to be more reliable.

Stop-gap solution for django-pgjson bug

---

seed/landing/migrations/0003_seeduser_default_building_detail_custom_columns.py
seed/landing/models.py
seed/static/seed/js/controllers/building_detail_controller.js
seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/js/controllers/buildings_settings_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/user_service.js
seed/static/seed/partials/building_audit_log.html
seed/static/seed/partials/building_detail_section.html
seed/static/seed/partials/building_energy_section.html
seed/static/seed/partials/building_projects_section.html
seed/static/seed/partials/building_settings_section.html
seed/tests/test_views.py
seed/urls/main.py
seed/views/main.py

Adds column show/hide/reordering on the Building Details page. Implements this in the same way as the Building List page is done. A new "settings" tab is added to the detail page for this.
I was able to use the existing buildings_settings_controller to accomplish this, by making minor modifications to handle a single building.
On the BE, these preferences are stored in the same way as the buildings list page, in a new field on the user model. Building Detail column settings are global in this implementation. I used a new field so that we could easily make changes if we feel there's a need for a different solution.
Try it out on a Building Detail page.
Refs #577

Issue #577 - Building Detail show/hide/reorder columns

---

seed/views/labels.py

https://github.com/SEED-platform/seed/issues/592
When removing a label via a bulk update where the current filters include filtering by that label the application informs you that 0 buildings were updated when in fact all of the selected buildings are updated.  
This was due to using a `queryset.count()` to return the number of updated buildings which re-evaluates the queryset.  Since the label had already been removed, the queryset evaluated to having zero items.
Prior to calling `save()` which updates all of the buildings, the value of `count()` is stored.  This allows returning an accurate number of updated buildings.

Fix updated building count

---

seed/static/seed/js/controllers/building_detail_controller.js

Tiny fix to hide `co_parent` field from building detail page.
Refs #690

Add co_parent to list of invalid keys to show on building detail page.

---

config/settings/common.py
config/settings/dev.py
config/settings/main.py
requirements/base.txt

Add sentry logging to servers. This is only for backend logging.
@mmclark I have a setting that needs to go into the server local settings for this to work. It's no-op without it.
Refs #719

Issue #719 - Sentry logging on BE

---

config/settings/common.py
config/template_context.py
seed/templates/seed/base.html

Adds sentry logging for JS and Angular exceptions. This is automatically turned on when Django's DEBUG setting is set to False and the sentry key is present.
Refs #719

Issue #719 - Sentry JS logging

---

seed/views/main.py

Implement retries when exporting buildings. This was previously implemented for file system storage, but the servers use s3 storage. Now both cases should work.
Refs #686

Issue #686 - Send a working status if s3 file isn't ready.

---

seed/lib/exporter.py

This work was done during the investigation of #686 
The `seed.exporter.Exporter` class was complex and did not follow some best practices.
* Extracted methods that could be turned into vanilla functions.
* Changed file handling to use files as context managers.  This prevents file descriptors from getting left open which is really bad.
* Reduced the memory footprint for iteration over large querysets (I suspect this might be part of why exporting large building lists fails)
* Minor cleanup to how file extension is validated.

Cleanup building exporter class.

---

.travis.yml
requirements/local.txt
tox.ini

Require a newer version of tox with the '-' argument is available to suppress output errors.

upgrade tox to 2.3.1 and do not clobber local_untracked

---

seed/tests/test_delete.py
seed/views/main.py

https://github.com/SEED-platform/seed/issues/730
The `seed.views.delete_buildings` view was still using the *old* search logic so it didn't work when filtering by labels.
Updated it to use the new search functionality.

Fix building deletion while filtering by label

---

seed/views/accounts.py

Deleting org buildings in the admin view feels very slow, this may be one reason. 
Speeds up the get_organizations endpoint. This was taking up to 3 minutes on seedtest. Locally, this speedup brought a 16 second response time down to 1 second. This mainly removes a bunch of count() queries that were able to be combined.
Refs #747 #684

Issue #747 - Speedup get_organization endpoint

---

config/settings/test.py

Use faster hasher so tests run quicker.
Refs #749

Issue #749 - Use fast password hasher during tests.

---

requirements/base.txt

Switch to a pypi supported and current version of django-storages. The previous one was 3 years unmaintained and was installed via mercurial.

Switch to supported django-storanges pypi package

---

requirements/base.txt

Updates in the previous pull requests required a new version of the python boto library (which was quite out of date).

update boto version

---

requirements/base.txt
seed/audit_logs/models.py

This package is unnecessary. It is also unmaintained and not compatible with Django 1.8.

Remove djorm-ext-expressions package

---

seed/views/main.py

https://github.com/SEED-platform/seed/issues/770
I fat-fingered a variable name when refactoring the `export_buildings` view.
Fixed the variable name.

fix unbound variable in buildings export view

---

seed/migrations/0013_auto_20160225_1213.py
seed/models.py

If a merged building has differing values for a field, that difference is stored in the AttributeOption model.
Makes the AttributeOption.value field larger by changing it from CharField to TextField. This is necessary because some values are bigger than 255 characters.
Refs #792

Issue #792 - AttributeOption.value larger field

---

seed/static/seed/js/controllers/matching_controller.js
seed/static/seed/js/services/building_service.js
seed/static/seed/js/services/search_service.js

`search_service.generate_columns` and `building_service.create_column_array` were very similar. `building_service.create_column_array` was only used during matching.
Combine these methods into one, using the `search_service.generate_columns` method. Call the search_service method on the matching page instead. Removes duplicate code.
Refs #723

Issue #723 - Refactor FE columns methods into single method.

---

seed/views/main.py

`get_column_mapping_suggestions` endpoint during mapping was taking upwards of 30 seconds on seedtest.
Optimize the queries for this endpoint. Currently this endpoint does around 15,000 queries with a small input file. This PR brings that number down to around 40. Response time for this endpoint is current around 25 seconds locally. This PR brings it down to around 500ms. 
Also added some organization membership checking for security.
Added issue #809 to investigate whether all this logic is necessary for getting the Schema info.
Refs #803

Issue #803 - Fix slow get_column_mapping_suggestions

---

seed/managers/json.py
seed/managers/tests/test_json_manager.py

Put in a fix for how a json query is handled when doing an order_by. This changes the behavior of the json_query, but ordering is only done in select situations, so i'm hoping the limited scope of this ensures we don't have any regressions.
Refs #804

Issue #804 - Fix for extra data order by results

---

config/settings/common.py
config/settings/local_untracked.py.dist
requirements/base.txt
seed/energy/meter_data_processor/green_button_data_analyser.py
seed/energy/meter_data_processor/tasks.py
seed/energy/pm_energy_template/post_process.py
seed/energy/pm_energy_template/template_to_json.py
seed/static/seed/partials/building_energy_section.html
seed/views/main.py

Update log:
- Fixed ngToast not shown bug.
- Add django-celery for `python manage.py celery` command to work.
- Move seed/energy/tasks.py to seed/energy/meter_data_processor folder to avoid circular import.
- Separate the code requesting GreenButton XML data as an independent task. Since schedulers will be set to run daily/monthly, when new GreenButton batch request info is saved by user, the new separated task will be called to request GreenButton XML file immediately instead of waiting for the scheduler to do it.
- Ignore rows missing critical data in uploaded energy template to avoid KairosDB insert exception.
Note:
- The backfill start date for GreenButton data is set to March 1, 2014, it is hard coded for the service provided by DC partner. I'm working on making it flexible.
- …

Timeseries testing update

---

seed/static/seed/js/controllers/building_detail_controller.js

Sort the building detail fields alphabetically if the user hasn't set any field settings.
Refs #840

Issue #840 - Sort building detail fields alphabetically by default.

---

seed/static/seed/js/seed.js
seed/static/seed/js/services/http_serializer.js
seed/static/seed/js/services/label_service.js
seed/templates/seed/_scripts.html

Semicolons inside of JSON inside of GET params were not being urlencoded by angular. Angular is doing this on purpose for some situations.
Adds a custom params encoder to use where necessary. This may be an issue in many places, so it's reusable. This is also temporary, as I plan on opening a PR on Angular to make this behavior less strict.
Refs #861

Issue #861 - Use a custom $http serializer to encode semicolons.

---

seed/static/seed/js/controllers/cleansing_controller.js

Removes an unused call to session storage in cleansing modal. Mainly removing this for cleanup and to make it less confusing.
Refs #841

Issue #841 - Cleansing modal doesn't use number per page.

---

seed/static/seed/js/seed.js
seed/static/seed/js/services/label_service.js

Angular's default http serialization does not encode semicolons in specific cases where it probably should. I have a custom serializer in place to fix this.
Use my custom http serializer globally.
Normal flow should be tested.
Refs #861 & https://github.com/angular/angular.js/pull/14309

Use custom serializer globally.

---

seed/tasks.py
seed/tests/test_tasks.py

Deletes users without organization memberships when an organization is deleted.
Delete an org with one user, user should be deleted.
Refs #899

Issue #899 - Delete users without orgs on org delete.

---

config/settings/common.py
requirements/base.txt
seed/landing/forms.py
seed/landing/views.py
seed/tests/test_account_views.py
seed/validators.py
seed/views/accounts.py

Django 1.9 comes with password validation built in.
Remove the django-passwords package and use Django's password validation.
Refs #902

Issue #902 - Use Django built in password validation

---

seed/static/seed/partials/buildings.html
seed/static/seed/partials/dataset_list.html
seed/static/seed/partials/project_detail.html
seed/static/seed/partials/projects.html

We introduced ng-pluralize as part of a bigger FE update, but this directive didn't respond well to the existing code's use of the  "number" formatter for the relevant value. 
I tried fixing via a documented strategy of formatting the value within the "when" attribute, but that didn't work in this situation (perhaps because of the scope.object.value nature of the value). So in the interest of time I just pulled out the number from the ng-pluralize, which now just updates the noun in the label.
Separates noun being pluralized from formatting of actual number.
Make sure "Buildings" header properly shows number of buildings, including when buildings > 1000.
#914

Separate quantity and pluralized label

---

config/settings/dev.py
config/settings/local_untracked.py.dist
config/settings/local_untracked_docker.py
config/settings/main.py
config/settings/travis.py
config/utils.py

DOMAIN_URLCONFS is defined in all the settings files, but I can't find a reason for it to exist.
Remove the setting.

Remove DOMAIN_URLCONFS setting.

---

docs/source/spelling_wordlist.txt
seed/models.py
seed/search.py
seed/views/main.py

Building list page is slow with a ton of records. 
This PR is a performance tweak for searching. The building list page calls `search_buildings`. The mapping/matching/other pages call `search_building_snapshots`. 
Both of these endpoints hit the same search methods that return children, parents, and coparent info. Building list does not need this information. So this PR passes along some info so that these related queries are not ran, speeding up the building list search.
@RDmitchell This needs solid testing, as it involves filtering in general. I ran through the normal flow with sample files and it looks good. But you may want to run your full test once this is merged.
Refs #916

Issue #916 - Slow building filtering

---

seed/static/seed/js/controllers/mapping_controller.js

When adding a new extra_data column, the mapping step after you start mapping would not show the new columns. 
Refresh columns after mapping.
Refs #885

Issue #885 - Refresh columns during mapping step

---

seed/audit_logs/views.py
seed/decorators.py
seed/tests/test_decorators.py
seed/tests/test_views.py
seed/views/accounts.py
seed/views/main.py
seed/views/projects.py

Buncha errors in sentry around org id missing. I'd like to surface these as informative messages to the browser.
Make a decorator for views requiring organization_id passed via GET. Throw a bad request with an error message if not. Unsure how these are happening but this is a start.
Refs #942

Issue #942 - Be strict about requiring organization_id

---

docs/source/setup_docker.rst
docs/source/spelling_wordlist.txt

The setup instructions for Docker where Windows/OS X centric and did not work
for Ubuntu. This pull request was based on what I did to get it working. 
This adds setup instructions for Docker on Ubuntu
- setting up Docker
- optional instructions for Virtual Box
- alternative option to run  Docker locally, with the local repo used  as a volume for the web server so local changes are reflected there.
Pull the repo to a clean directory (ideally on a fresh install) on an Ubuntu box and follow
the instructions.
None. This is based on the work I did setting up my dev environment.
This contains changes to documentation only.  It should be checked for clarity and validated
(this is based on the  process I followed, but naturally that took some experimentation so its not an exact match) If needed …

This adds setup instructions for Docker on Ubuntu

---

seed/static/seed/js/controllers/buildings_reports_controller.js

Fixes js error in getAggChartData
- yAxisType: Category, missing quotes causing Undefined error
- added quotes : produces bar chart
Chart wasn't loading due to js error
Adds quotes to fix js error
Go to reports page and generate charts
#965
Existing test at seed/static/seed/tests/buildings_reports_controller.spec.js was failing, now passes

Fixes js error in getAggChartData

---

seed/static/seed/js/controllers/bluesky_properties_controller.js
seed/static/seed/js/controllers/bluesky_taxlots_controller.js
seed/static/seed/js/seed.js
seed/static/seed/partials/bluesky/table.html

(See title) More UI Grid additions to the bluesky property and taxlot grids.  The individual grid settings are saved separately, and there's a custom option under the grid menu at the top right to completely reset any saved grid changes (filters, sorting, column order, column width, column visibility).
Please deploy to seeddev at your convenience.

Added column menus, grid menus, and saving/restoring state

---

seed/bluesky/views.py
seed/static/seed/js/controllers/bluesky_properties_controller.js
seed/static/seed/js/controllers/bluesky_taxlots_controller.js
seed/static/seed/js/seed.js
seed/static/seed/partials/bluesky/table.html

The bluesky grids now allow any columns to be pinned to the left or right, and for your settings to be saved.  By default, the first column in each grid is pinned.
IMPORTANT: You won't see the first column pinned unless you pin it yourself or reset the grid settings.  This is because you have already "saved" your grid state with no columns pinned since this wasn't a feature until now.  In the top-right grid menu, hit `Reset Settings`

Added column pinning

---

seed/static/seed/partials/buildings.html

List of labels to filter were limited to only 25 items
Expands the filter list to 255 items
add more than 25 labels and make sure that they show up in the building list filter by label box
#989

allow 255 items in label list

---

seed/functional/tests/base.py
seed/functional/tests/test_browser.py

- made generic wait_for_element method take can use different
strategies
- converted wait_for_element_by_css to use this
- added set_buildings_list_columns method to control displayed
columns in buildings list
This is a test for #953.  Could not reproduce issue but added test to ensure it works.
Adds a Selenium test against this issue. Expanded functional test functionality.
No need to manually test as this adds automated test
#953

954 - Added selenium test to check year ending can be edited.

---

config/settings/local_untracked.py.dist
config/settings/local_untracked_docker.py
seed/functional/tests/base.py
seed/functional/tests/test_browser.py
seed/static/seed/js/controllers/building_list_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/building_service.js
seed/static/seed/js/services/search_service.js

There were many errors in Sentry where the user tried to access a page in the building list that wasn't allowed. This addresses the issue by making the number of pages a method that is called.
Also, the building view of project buildings did not have the number of items, filters, etc in the local storage. This was updated.
Note that the filters for a project and all buildings are now the same. If you go from one to the other, the filters/settings persist.
Fixes the most prevalent sentry error.
List all the buildings and change from 10 -> 100. Go out, then come back to the view and click `last record`. It should return the results immediately (before it just hung).
Open up a project (list the buildings), and make sure the number of items and filters stick when clicking around.
#1005

1005 number of pages

---

requirements/test.txt
seed/decorators.py
seed/functional/tests/base.py
seed/functional/tests/test_browser.py
seed/tests/test_decorators.py
seed/tests/test_views.py
seed/views/main.py

See #1008.
There were many errors on sentry related to this bug. I have not determined what action on the front end is causing this, but this PR will allow for the app to continue.
Makes the error of org id not existing explicit and a JSON. Before it was a string result.
Normal monkey testing.
#1008

return json when invalid organization is passed, catch the error nicely

---

seed/static/seed/js/controllers/bluesky_properties_controller.js
seed/static/seed/js/controllers/bluesky_taxlots_controller.js
seed/static/seed/js/services/bluesky_service.js

Saves the chosen cycle between property/taxlot views for each organization.  The selected cycle will persist for the duration of the session, after which point it will default back to the first choice.

Bluesky Cycle Saving

---

seed/views/properties.py

Views of tax lots and properties were crashing when the cycle was not found. 
Added a simple guard to prevent .latest() from being called on None.
View properties
None

allow null cycles in views of properties and taxlots

---

seed/management/commands/create_sample_data.py
seed/test_helpers/fake.py

This should fix the issues with audit log data in the command for creating sample data.  Had a problem merging develop into the branch I had been working on so since it is only two files I just made a new branch.  This PR does not address issues with using the generated data as import files.
Adds a management command called create_sample_data that takes the following command-line params:
--A number of A cases to create
--B number of B cases to create
--C number of C cases to create
--D number of D cases to create
--Y years to be created in a csv string.  E.G. "2014,2015,2016"
--audit-depth the number of additional records to be created for each case for each year.  E.G. "--A 1 --B 0 --C 0 --D 0 --Y "2014,2015,2016" --audit-depth 5" will create 6 PropertyStates and 6 TaxlotStates (remember …

Demo data with audit logs

---

seed/data_importer/tasks.py
seed/data_importer/tests/test_data_import.py
seed/lib/mcm/data/SEED/seed.py

Save to taxlot table only if the mapping says to use the taxlot table.
fixed bug where taxlotstate objects were being created for every import record.
run tests.

do not create taxlot table if not mapping to it

---

api/urls.py
api/views.py
seed/data_importer/tasks.py
seed/data_importer/tests/test_case_a.py
seed/data_importer/tests/test_case_b.py
seed/data_importer/tests/test_data_import.py
seed/data_importer/tests/test_matching.py
seed/lib/mcm/mapper.py
seed/lib/mcm/tests/test_mapper.py
seed/models/__init__.py
seed/models/columns.py
seed/models/joins.py
seed/models/properties.py
seed/models/tax_lots.py
seed/pagination.py
seed/tests/test_columns.py
seed/views/datasets.py
seed/views/main.py
seed/views/organizations.py
seed/views/projects.py
seed/views/users.py

A user can put a delimited list of tax lot ids in a field. 
Handles delimited values in jurisdiction_tax_lot_id field. For example, 33366555; 33366125; 33366148 will be broken up into 3 separate tax lots.
There are some test.
N/A

Many taxlotids import field

---

seed/data_importer/tasks.py
seed/data_importer/tests/test_robindemocase.py
seed/data_importer/tests/util.py
seed/lib/mappings/mapping_columns.py
seed/lib/mappings/mapping_data.py
seed/lib/mappings/test_mapping_columns.py
seed/lib/mappings/test_mapping_data.py
seed/lib/mcm/mapper.py
seed/lib/mcm/matchers.py
seed/lib/mcm/tests/test_mapper.py
seed/lib/mcm/tests/test_matchers.py
seed/views/main.py

Mapping would sometimes return duplicate mapping results and the suggestions were sometimes way off.
This PR allows for only one unique mapping result per set of fields. If there are duplicates, then it will look at all the mapping suggestions and decide the next best one to pick based on the confidence of the match.
In addition, if a column has no suggestions or all the suggestions are removed, then the mapping suggestion will be set to the raw column name and end up as extra data.
Go through the mapping process with the covered building sample and the new property/taxlot examples.
#1085 #1090
N/A

1090 duplicate field names

---

api/views.py

The get_api_schema would return this "testing" function.
This removes the endpoint from the api_schema return.
Browse to /app/api/get_api_schema.  On develop, the `test_view_with_arg` function is listed.  With this fix it is no longer listed.
#133876097

Remove a test view from the get_api_schema function call

---

seed/data_importer/tasks.py
seed/lib/mcm/mapper.py
seed/lib/mcm/tests/test_mapper.py

The taxlot id needs to be normalized in order for matching code to work properly.
Removes -, spaces, /, \ from taxlot ids. Also trims white space and upcases.
import test files with characters above in tax lot id. Make sure to map the jurisdiction tax lot id to the tax lot field in the file.
https://www.pivotaltracker.com/n/projects/1865423
N/A

normalize the jurisdiction tax lot id

---

requirements/test.txt

The `fake-factory` pip package was deprecated and now fails to install.  It is now `faker`.
Fixes the dependency.
Travis tests should pass.
n/a

Fix faker dependency

---

config/management/commands/create_default_user.py
seed/lib/superperms/orgs/models.py
seed/tests/test_api.py
seed/tests/test_views.py

There was an error when new organizations were created that data sets could not be added. This was because there was not a cycle available. 
When an organization gets created a Default {year-1} Calendar Year cycle will be generated automatically.
Create org, then create a data set. Make sure that no error is thrown.
#1182

upon org creation, create a default cycle

---

seed/views/properties.py
seed/views/taxlots.py

Correct cosmetic audit history order in the case where an import file matches within itself and then proceeds to match with existing data.
It's difficult to order a tree structure linearly, but this PR fixes a corner case where some import files with duplicates (or matches) need to match with existing data

Audit History Order

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/partials/inventory_list.html

Adds a label `EXCLUDE` button to the inventory list page
Add one or more labels to the label filter on the inventory list page and select the `EXCLUDE` button.  Any inventory records with any of those labels will be hidden.
#1401

Added a label exclusion button #1401

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/services/inventory_service.js

On the inventory list page, the 3 datetime fields (`Recent Sale Date`, `PM Generation Date`, `PM Release Date`) can now be filtered similar to the number filter.
The filter supports multiple filters separated by commas, and the date string can be either a year (`2016`), a year and a month (`2016-05`), or a full date with no time (`2016-05-31`).
The filter syntax is as follows:
> 2016
> 2016-05
> 2016-05-31
> = 2016
> == 2016-05
> != 2015
> ! 2015
> <> 2015-10
> \>= 2016
> < 2016-05
> 2016, >= 2016-10-01
> \>= 2015, < 2017
#1416

Date filter

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/views/cycles.py
seed/views/properties.py

Click the (i) button on the inventory list page (for multiple cycles) to make sure that the hyperlinks work as expected

Fixed cycle mismatch when the backend doesn't order the cycles by name

---

bin/start-seed.sh

Sets the listening interfaces to "all" ie. 0.0.0.0, instead of
implicitly localhost. This makes setting up network forwarding under
Vagrant for dev instances a bit easier.

Makes start-seed run a bit easier under Vagrant

---

seed/static/seed/partials/inventory_list.html

Short label names (less than 3 characters) were unselectable when filtering by label on the inventory list view.
Create (or rename) a label to be only one or two characters, apply that label to a record, and attempt to filter by that label on the inventory list view.

Allow short labels to be filtered on the inventory list page

---

config/settings/dev.py
seed/utils/generic.py

The Swagger page imports the markdown package, and upon import, it issues many, many debug lines to the console.  This only occurs in dev mode when the log is set to debug.  But it makes it hard to develop when all those lines mask actual messages.
Adds a log filter that will simply filter out the markdown import messages.
On the develop branch, run SEED in dev mode and load the swagger page.  The console should be littered with messages:
Then on this branch, run SEED in dev mode and those particular messages should be gone, leaving only relevant messages.
N/A
Above.

Filter out bazillions of markdown package import debug log statements

---

seed/models/models.py

Doesn't look like this model is used anywhere anymore, but this startup warning courtesy of the Django system check was starting to bug me.
Starting the dev server without this patch was always giving me this notice:
```
September 08, 2017 - 20:19:45
Django version 1.9.13, using settings 'config.settings.dev'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Performing system checks...
System check identified some issues:
WARNINGS:
seed.NonCanonicalProjectBuildings.projectbuilding: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
System check identified 1 issue (0 silenced).
```

Fixes startup warning on `seed.NonCanonicalProjectBuildings.projectbuilding`

---

seed/static/seed/js/services/data_quality_service.js

Seems djangorestframework will fill in a 301 redirect to add a trailing slash. No need for two AJAX requests here.

Fix typo, remove spurious 301 redirect.

---

seed/data_importer/tests/test_case_b.py
seed/data_importer/tests/test_data_import.py
seed/lib/mcm/mapper.py
seed/lib/mcm/tests/test_mapper.py

SEED was removing too many characters when performing Jurisdiction Tax Lot ID normalization.
The normalization will only remove characters when they are repeated. It will also strip spaces from the beginning and ending.
Import test files. Test matching.
#1329

make the normalize tax lot code less stringent

---

seed/models/properties.py

Extra data was not showing up in the property coparent requests. 
Add extra_data to coparent. I don't expect this to slow down the requests significantly.
Import two sets of data that have matches. Look at the matching page and make sure that extra_data can be seen/selected.
in PT

add extra_data on coparent for PropertyStates

---

seed/static/seed/js/services/inventory_service.js

Changes to column settings are saved to localStorage.  On loading the settings, they are compared to all existing columns and defunct ones are removed.  The issue was that only the column name was previously checked, and the column name could be identical for both Property and Tax Lot columns.
This PR checks both the column name and the table to make sure the column still exists before showing it.
#1320

Fixed old column settings from showing invalid entries - #1320

---

seed/static/seed/js/controllers/pairing_controller.js
seed/static/seed/partials/pairing.html

- Shows the selected left columns on the right half for the child rows
- Fixed filtering numeric columns on the pairing page
#1432

Pairing - Show the left columns on the right for child rows

---

config/settings/dev.py
seed/utils/nocache.py

Completely disables client-side caching when the dev settings profile is used, without the browser Developer Tools being open with `Disable cache` checked.
This works by setting the response header `Cache-Control: no-cache, no-store, must-revalidate, max-age=0`, along with equal `Date` `Expires` and `Last-Modified` headers

Disable all client-side caching when the dev profile is used

---

seed/static/seed/js/controllers/inventory_settings_controller.js

Follow-on work to #1457. Hides the `*_pint` columns until the main body
of the UI work for differentiating metric and imperial units is ready.
There are now database columns ready to receive tagged Quantity units for the EUIs and Areas. The UI is not yet ready, so these columns should not be displayed to users. They have a `(Pint)` suffix in the UI, just in case they display, to avoid mistakenly stuffing production data into them.
Fixes one missed case where the Quantity-related columns (eg. `Site EUI (pint)`) show in the Property List Settings.
See "Definition of Done" below.
#1457 
Given a migrated 2.2 database, the page `/app/#/properties/settings` should not show any columns with the suffix `(pint)` available for toggling display.

Hides `*_pint` columns in Property List Settings view

---

seed/static/seed/partials/inventory_detail.html

Added `Custom ID 1` field for Related Properties on the inventory detail page
#1404

Added `Custom ID 1` field for Related Properties

---

seed/static/seed/js/controllers/mapping_controller.js
seed/static/seed/partials/mapping.html

Added a  `Map SEED fields to imported file fields` button to the mapping page
Import a file, then press the button on the mapping page.  All seed header names should change to the original imported column names, and the type should be Property
#1238

Added a mapping button to `Map SEED fields to imported file fields`

---

seed/static/seed/js/controllers/inventory_settings_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/inventory_service.js
seed/static/seed/js/services/matching_service.js

- Use `table` instead of `related` in settings for checking saved columns against all existing columns
- Ensure that *_pint columns are hidden more broadly
Improves column saving/loading broadly, but primarily to fix the saving of settings for the inventory detail page.
This will also delete any previously saved column settings
Change column settings (inventory, inventory detail, matching, matching detail), refresh the page to see that the settings have persisted, and return to the primary view to see that the selected columns are being used as expected

Improved Column Saving

---

seed/data_importer/tasks.py
seed/models/data_quality.py
seed/static/seed/js/controllers/mapping_controller.js

If the user clicks back to mappings during the mapping review process and before the data quality checks were complete, then there was a chance that the results weren't cleared out.
Add in an explicit check that verifies that the data quality checks are complete before displaying the mapped results.
Load data with a lot of errors. Click Back to Mapping immediately once it appears and try remapping the data. The number of errors/warnings should not change.
#1488

1488 data quality results

---

seed/data_importer/views.py
seed/static/seed/js/controllers/data_quality_modal_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/partials/data_quality_modal.html
seed/tests/data_quality/test_views.py
seed/views/data_quality.py

Data quality results that were presented in the modal were only exportable from the mapping results.
Add the export capability to the DQ results from the inventory list
- Go to inventory page
- Select a few records (that will have DQ issues)
- Run DQ
- From modal, make sure export exists
- Try to download results and inspect file.
#1363

Export DQ from Inventory

---

bin/install_javascript_dependencies.sh

Running Django's `collectstatic` command has to copy and validate about 15,259 files and directories.  Cleaning up after fine-uploader reduces this total to 2,741
Deletes the `node_modules` directory from the fine-uploader directory after building
From the seed directory:
```bash
rm -rf seed/static/vendors/bower_components/fine-uploader
./bin/install_javascript_dependencies.sh
```

Removes node_modules from fine-uploader after building

---

docs/source/setup_osx.rst

It caused problems with finding the settings for celery in on mac. Also those instructions weren't there in the Ubuntu instructions.
@nllong @axelstudios

removing instruction to python setup.py install

---

bin/start-seed.sh

The old implementation (count the # of times "celery" is greppable from
the process list) is vulnerable to skipping a needed start if I'm
tailing `/tmp/celeryd.log` in another terminal window. Here we let the
celery process write a pid file and check for the presence of that
instead.
1. Before merge, use `./bin/start-seed.sh` to start the dev environment
2. Open a second window and then tail `/tmp/celeryd.log`
3. Kill django and celery in the first window
4. Restart with `./bin/start-seed.sh`
Expected: celery should restart.
Observed: celery doesn't restart; we're told it's already running because the tail command is spoofing it.
After merge, repeat steps. Expected and observed should now match.
n/a

Tightens up check for whether celery's running in dev

---

seed/api/v2_1/views.py
seed/models/tax_lot_properties.py
seed/test_helpers/fake.py
seed/tests/test_project_views.py
seed/tests/test_properties_serializers.py
seed/tests/test_property_views.py
seed/tests/test_views.py
seed/tests/util.py

The inventory list page did not show the analysis state as a string. 
Converts the analysis_state field to the enumeration string.
Load data, check inventory page for analysis_state as 'Not Started' instead of 0.
N/A

display analysis state string instead of int

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/mapping_controller.js
seed/static/seed/js/services/inventory_service.js

Previously, columns with `type: "number"` would be assigned the numeric filtering syntax, date columns would be assigned date filtering syntax, and all other columns would be assigned text filtering syntax documented [here](https://docs.google.com/a/lbl.gov/viewer?a=v&pid=sites&srcid=bGJsLmdvdnxzZWVkfGd4OjNmNjI4ZmYxOTg3MTM4ZTE).
This PR combines text and numeric filtering for all non-date columns, which is very helpful for extra_data columns which are always assumed to be "text".
On the inventory list page try filtering any column with the syntax below.
- The filter supports multiple filters separated by commas.
- Date strings can be either a year (`2016`), a year and a month (`2016-05`), or a full date with no time (`2016-05-31`).
The filter syntax is as follows:
> abc
> 5
> ""
> "abc"
> …

Combined text/numeric filtering

---

seed/serializers/pint.py
seed/serializers/properties.py
seed/test_helpers/fake.py
seed/tests/test_api.py
seed/tests/test_views.py
seed/views/properties.py

Somehow some of the data on production got added to the Pint field. This fixes the error so that the user can continue working with the system. Note though, that the pint fields have been hidden for the most part, so it is recommended to fix the data to point to the 'non-pint' fields.
Fixes the serializer to work with pint quantity values.
unit tests, monkey tests.
PT 153866590

fix serialization of quantity

---

bower.json
config/settings/local_untracked.py.dist
docs/source/deployment.rst
seed/templates/seed/base.html

Sentry has been disabled for quite some time... time to reenable.
Add dependencies for frontend sentry.
On production/staging machines, add your SENTRY_JS_DSN variable to your local_untracked.py file.
N/A
N/A

Add Sentry to Frontend

---

seed/static/seed/partials/data_upload_modal.html

Hides the `Upload Green Button Data` button, since it's currently disabled anyway

Temporarily hid the `Upload Green Button Data` button

---

seed/static/seed/partials/mapping.html

Allows the mapping columns to be resizable with drag handles
Upload a file, go to the mapping page, drag the column dividers to resize
fixes #1337

Allow the mapping columns to be resizable

---

config/settings/common.py
seed/utils/api.py

* Swagger was not accessible to non-auth users causing sentry errors.
* Swagger logout was not working
* Fixes the swagger page to show the API endpoints that are available as an unauthenticated user. This is a shift from before where an unauthenticated user was able to see all endpoints.
* Fixes the Django Logout button on the swagger page.
* Log out of your seed instance
* Go to http://seed-instance.somewhere/api/swagger
* Verify that you can see /v2/schema
* Log in (via button on top)
* Verify that you can see the entire API
* Click Django Logout (via button on top) 
* Verify that you are now logged out.
Fixes #1603

fix swagger access

---

seed/models/data_quality.py
tox.ini

If there is a data quality rule that checks for numbers and the data is a string, then the data quality checking would error out and stop the mapping progress.
Check if the data are convertible to a number, if not, then log then error as a data quality rule error.
* Go to organization settings
* Create a data quality rule on a normally string field but set the type to number (e.g. city)
* Import some data that and verify that the data quality rules are now reporting that it is unable to convert city to number (or whatever field you are testing).
#1297

1297 data quality typeerror

---

config/settings/common.py
config/settings/local_untracked.py.dist
config/urls.py
requirements/base.txt
seed/filtersets.py
seed/landing/models.py
seed/models/certification.py
seed/renderers.py
seed/serializers/certification.py
seed/serializers/columns.py
seed/serializers/pint.py
seed/serializers/properties.py
seed/tests/test_certification_models.py
seed/tests/test_certification_serializers.py
seed/tests/test_properties_serializers.py
seed/tests/test_views.py
seed/utils/viewsets.py
seed/views/certification.py
seed/views/columns.py
seed/views/data_quality.py
seed/views/datasets.py
seed/views/measures.py
seed/views/meters.py
seed/views/organizations.py
seed/views/projects.py
seed/views/scenarios.py
seed/views/users.py

1.  adds an 'add_column_names' endpoint that allows Columns to be added based on an existing record. We found this to be necessary to make column selections available when records are upload through api endpoint rather than the front end.
2. adds OAuth2 functionality, with a JWT Grant option.  See https://github.com/GreenBuildingRegistry/jwt-oauth2 for additional details and JWT Grant base client side setup.  SessionAuthentication and SEEDAuthentication were left in place.  The 'authentication_classes' attribute was removed from the views that had set these two classes explicitly so that the default athentication classes, which includes all three would be use.
3.  Removed pint handling from SEEDJSONRenderer and updated PintQuantitySerializerField to handle the remaining cases requiring …

added oauth, add_columns endpoint, and adjusted pint handling

---

Dockerfile
bower.json
config/settings/common.py
docs/source/aws.rst
docs/source/linux.rst
requirements/base.txt

The docker containers were not building successfully (or any fresh installation) due to the newer version of FileSaver.js.
The oauth2 work did not work on new machines due to the missing libffi and libssl packages.
* Add libssl-dev and libffi-dev to installation instructions and docker containers.
* Restrict FileSaver.js to version 1.3.3
Only should impact deployment. Manually test.
n/a

Add libffi-dev and libssl-dev to docker and documentation

---

seed/api/v2/views.py
seed/api/v2_1/views.py
seed/building_sync/building_sync.py
seed/data_importer/views.py
seed/hpxml/hpxml.py
seed/landing/models.py
seed/test_helpers/fake.py
seed/tests/test_building_file_views.py
seed/utils/viewsets.py

BuildingSync and HPXML were displaying quantities in the elements.
Cast the Quantity fields to their magnitudes before persisting to the XML's (BuildingSync and HPXML).
Unit tests were added. 
Go to the following endpoints via the API:
*  <host>/api/v2.1/properties/234/building_sync/?cycle_id=x
*  <host>/api/v2.1/properties/234/hpxml/?cycle_id=x
N/A

Remove unneeded auth classes. Fix BuildingSync and HPXML API endpoints

---

seed/static/seed/js/controllers/inventory_settings_controller.js

Fixes a 500 error when the `pinned` parameter is missing due to the value being `undefined`.
1. Delete all settings profiles for one of the property/taxlot list views
1. Refresh the page
1. Select some columns to save
1. Click `New` and name the settings profile
1. Save
#1627

Fixed missing pinned parameter when the value is undefined

---

seed/models/cycles.py

The default new cycle range was `01-01-2017` to `12-31-2018`, now it's `01-01-2017` to **`01-01-2018`**
Create a new org and check the Existing Cycles org page to verify the end date.
#1586

New org cycle range

---

seed/tests/test_portfoliomanager.py
seed/views/portfoliomanager.py

The portfolio manager workflow was designed around using a single template, and having SEED generate and then download that report.  A new workflow was encountered, where the templates could have child data requests that behave a bit differently.
With this PR, we now checks to see if the current row in PM has any child rows such as these:
If those are encountered, we keep track of those rows as slightly different entities.  If the user selects a regular template row to report on, the code behaves as it has, and generates a report then downloads it and imports the data, exactly as it currently does.  So we haven't broken anything.  But if a child row is selected, there is no generation step, instead we just directly call the server with a query string and it gives us back the XML data.  So …

Fix some portfolio manager child data request stuff

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/show_populated_columns_modal_controller.js
seed/static/seed/js/services/inventory_service.js

The `Only Show Populated Columns` feature wasn't always requesting the correct inventory records if multiple cycles were present, and in that case could select the wrong columns.
Fixes the cycle id that was passed to the inventory data request.
- Create two cycles, e.g. 2016 and 2017
- Import different data into one or both cycles
- Run the  `Only Show Populated Columns` feature for both cycles
- Check that the correct columns are shown for data belonging to the current cycle

Fix `Only Show Populated` to use the current cycle

---

seed/data_importer/views.py

During PM imports, the value was converted to BTU and assigned a proper pint unit quantity.  Unfortunately, this unit did not persist with the data throughout the entire import process.  Because the data gets written to an import_file locally and then processed from there like a normal import, the unit did not get carried along.  I mistakenly thought Pint didn't have kBTU as it isn't listed in the definition file.  However, the btu unit can be tagged with a kilo prefix, so that's what I changed this to do.
When we import from PM, we now keep the numeric value as it was from PM, and tag it with kBTU (even though that isn't necessarily persisted).  This should allow the normal import process to grab the data in what it thinks is kBTU and everything will be good.
Test a pm import file …

Use kBtu during imports

---

seed/static/seed/js/services/pairing_service.js

After the backend column refactor, going to the pairing page for the first time (without ever modifying the saved settings) results in no columns shown.  This restores the default column visibility
- Create a new org
- Import a file
- Go to the pairing page
- Check that some default columns are visible (3 property, 2 taxlot)

Fixed showing of default pairing columns

---

seed/data_importer/tasks.py
seed/data_importer/tests/test_merge.py
seed/data_importer/views.py
seed/lib/merging/merging.py
seed/models/building_file.py
seed/test_helpers/fake.py
seed/views/properties.py
seed/views/taxlots.py

Pairing was not pairing on UBID.
This PR adds the UBID item to the list of columns to compare for pairing. This PR also adds several tests. The tests are for the current behavior.
It also corrects the handling of records within a single import file that are automatically merged together (with regard to unmerging and properly accumulating tax lot pairings)
Import file with UBID and jurisdiction tax lot id.
| UBID     | Jurisdiction Tax Lot ID |
|----------|-------------------------|
| ubid_001 | lot_1                   |
| ubid_002 | lot_1                   |
| ubid_003 | lot_1                   |
The resulting inventory list should have 3 property states, and one tax lot--all linked with each other.
Also follow the tests in #1639
#1633, #1639, #1649

1633 multiple ubids, single taxlot

---

bower.json

Running `bower install` installs 1.6.x Angular dependencies, except with 1.x.x Angular-Sanitize which is currently resolving to `1.7.0`
Corrects the version of angular-sanitize to 1.6.x
Remove the `bower_components` directory, run `bower install`, and check that SEED loads correctly

Fixed the angular-sanitize semantic versioning

---

seed/data_importer/tests/test_merge.py
seed/models/tax_lot_properties.py
seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_detail_settings_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/inventory_settings_controller.js
seed/static/seed/js/controllers/merge_modal_controller.js
seed/static/seed/js/controllers/pairing_controller.js
seed/static/seed/js/controllers/show_populated_columns_modal_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/inventory_service.js
seed/static/seed/tests/inventory_detail_controller.spec.js
seed/static/seed/tests/mapping_controller.spec.js
seed/static/seed/tests/property_detail_controller.spec.js
seed/static/seed/tests/taxlot_detail_controller.spec.js
seed/tests/test_column_views.py
seed/tests/test_property_views.py
seed/tests/test_views.py
seed/views/properties.py
seed/views/taxlots.py

- Previously we had an option to request only specific columns be returned from the backend to improve performance and reduce data transfer.  This PR restores that functionality.
- Passes an optional profile id to the inventory filter API to return data for the columns in that list settings profile
- Fetches all columns for only selected rows when opening the merge modal
- Added an API resource to return only columns that can be mapped
- Removed deprecated code that prepended `tax_` and `property_` to field names
- Commented unused `calculated_taxlot_ids` and `primary` fields
- On an org with no saved list settings, check that the data returned includes all columns
- Create a list setting (like with `Show only populated columns` and check that only those specific columns are returned.
- …

Return inventory records with only the columns specified

---

seed/models/column_list_settings.py
seed/models/tax_lot_properties.py
seed/static/seed/js/controllers/export_inventory_modal_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/tests/test_column_list_settings.py
seed/utils/organizations.py
seed/views/tax_lot_properties.py

* The export inventory was broken since the profile deployment
* Extra data was not being displayed in the inventory view (but the data was in the database)
* Fix export and extra data display
* Import data, making sure to map some of the data to extra data
* Go to the inventory page
* Select a few rows
* Go to Actions -> Export Selected
* Make sure file looks right (with all the data)
* Create a profile
* Re export the data
* Make sure only the selected columns exist
Also, verify that data in extra data are now in the GUI and in the CSV.
#1669

Fix Inventory Export and Displaying of Extra Data Fields in Inventory

---

seed/data_importer/views.py

PM import filenames were being named properly, but one of the views reported back a static "PortfolioManagerImport" string instead of the filename.  This fixes it.
Reports back a proper filename with date timestamp so the user can see when it was imported.
Test a PM import process, autogenerated filename reported on the site should have today's date in it.
#1548 
Mapping Page:
DataSet Detail Page:

Report proper filename for uploaded_filename during PM import

---

seed/utils/organizations.py

This fix prevents sub orgs from being created using existing names and changing org ownership.

Fix privilege escalation bug

---

seed/static/seed/js/controllers/menu_controller.js
seed/static/seed/js/seed.js
seed/templates/seed/index.html

The loading spinner that used to appear when clicking on new pages stopped showing up after upgrading the angular ui-router.
Restores the spinner behavior
Check that the spinner is visible during page transitions, particularly for long-running transitions like going to the inventory list view.
#1702

Fixed the spinner visibility during routing transitions

---

seed/data_importer/views.py
seed/lib/mappings/mapping_columns.py
seed/lib/mappings/test.py
seed/lib/mcm/mapper.py
seed/management/commands/create_default_columns.py

During migration, some organizations may not have received the default columns. Without the default columns many of the screens won't work correctly.
Adds a managed task to allow the user to manually create the default columns. Default columns will only be created in organizations that have no existing columns.
In a test database, remove all the columns of an existing organization. It is easiest to create a new org and remove the columns since the column list settings and column mappings do not exist in a vanilla organization.
```
./manage.py create_default_columns
./manage.py create_default_columns --org_id 8
```
None

Create default columns managed task

---

seed/serializers/labels.py
seed/static/seed/js/controllers/inventory_list_controller.js

The result of the /api/v2/labels/filter returns the property ID which makes little since due to the fact that other API calls typically use the property view id (e.g. /api/v2/properties/<property_view_id>.
`{id: 4142, name: "Call", color: "blue", organization_id: 278, is_applied: [498379]}`
Change the backend and frontend to return property_view_id
* unit tests.
* in existing database, add label, check to make sure it is assigned to the right property. 
* Check API call to ensure tha the is_applied id is the property_view id.
N/A

Return PropertyView ID from Label Filter API

---

bin/backup_database.sh
seed/models/building_file.py
seed/static/seed/partials/inventory_detail.html

When uploading a BuildingSync file to an existing property and the BuildingSync file has a scenario with no measures, the app would crash.
* Fixes the crashing when no measures are in a scenario
* Add backup for the media data
If you have a buildingsync file that has a scenario with no measures, then use that.
N/A

No measures in BuildingSync scenario

---

seed/static/seed/js/controllers/inventory_reports_controller.js
seed/static/seed/js/seed.js
seed/views/reports.py

The Inventory Report page had a bug where no data meant a bad HTTP request (404). Also on that same page, X-Axis choices were hard-coded.
The no data bug has been fixed, and X-Axis choices are now all columns with numeric types.
**NOTE**: I had a pretty limited dataset, and I'm less confident in my ability to map columns correctly - I'm not very familiar with building/energy terminology. 
Please test this locally by updating the type of one of the org's columns to be numeric. Then go back into the Inventory Report page to graph different columns.
Issue #421

421 reports no data and X-Axis options

---

seed/models/tax_lot_properties.py

Recent PR implemented the following the change: https://github.com/SEED-platform/seed/pull/1750/files#diff-d68816841c1896aa3594e2074b14f870R56
This and other logic within the PR allows for properties and tax lot list responses to include never-populated extra_data fields. Unfortunately, these specific logic introduced a bug in the case where `fields=None` (the default value).
```
Internal Server Error: /api/v2/import_files/107/filtered_mapping_results/
Traceback (most recent call last):
...
File ".../seed/seed/data_importer/views.py", line 868, in filtered_mapping_results
property_column_name_mapping
File ".../seed/seed/models/tax_lot_properties.py", line 57, in extra_data_to_dict_with_mapping
for field in fields:
TypeError: 'NoneType' object is not iterable
```
Fixes the bug.
Import a …

Add check for extra_data fields before iterating over fields in TaxLotProperty

---

.gitignore
requirements/base.txt
seed/tests/test_portfoliomanager.py

Due to reasons, PM is currently unavailable.  The SEED-PM connection is tested with several unit tests.  Once PM went down, these tests starting failing, as they should.  But this issue with PM should not really cause SEED's test dashboard to be red, so we'll skip these for now.
Adds some logic to try to determine whether ESPM is actually available.  Even during this "down" time, the site is still running, so we can't just check the return code from the request.  
Just run the entire test suite of SEED, it should now all pass, with a few skipped.
I don't believe there are any yet, I was just informed the tests were failing, and why.

Skip PM tests while PM is down

---

seed/data_importer/views.py
seed/lib/mappings/data/pm-mapping.json

There was an issue where only 'actual' database fields were showing up in the mappings review screen. 
* Enable showing of all columns on the mapping review page
* Allow "Gross Floor Area" to be a known column for ESPM. This prevents the column from being an 'extra data' column. 
Follow instructions on issue #1807 
#1807

1807 no extra data

---

.dockerignore
Dockerfile
config/settings/common.py

Collected static files were not loading correctly when deploying with Docker. This worked if the user installed the static files (`npm install`) on the base box before running docker compose commands.
* fixes the static files in docker
* deploy and verify all works as expected.
N/A

force running npm install inside the vendors directory

---

seed/static/seed/js/controllers/inventory_list_controller.js

1. When manually merging records from the inventory list view, the merge-modal dialog now shows all populated extra_data columns in addition to the defaults
2. If a column filter is set and you either change the current cycle or merge records then the updated inventory will appear correctly after that action
1. Set an arbitrary column filter
2. Change cycles and ensure that rows appear after doing so
3. Merge records that have extra_data fields and ensure that those fields appear in the merge preview in the merge modal
#1812

Fixed showing extra_data in the merge modal

---

config/settings/common.py
docs/source/conf.py

* Read the docs was not building since we migrated to python 3.x
* Swagger broke during the pipeline upgrade
* fixes the read the docs. Note that past versions of SEED will not be rebuilt in RTD.
* find the static assets using the AppDirectoriesFinder instead of specifying in the STATICFILES_DIRS.
Best to test by building in docker from scratch and ensuring that all the static assets are found when running SEED (and swagger).
N/A

Fix Read the Docs and swagger

---

deploy.sh
docker-compose.yml
seed/lib/mcm/cleaners.py
seed/views/column_mappings.py

If the user deleted a column using API, then the column mapping was not removed. This left a column mapping object that pointed to a null column resulting in errors with viewing the column mappings.
In addition, when mapping data that had quantity units attached, there was a case when the units would be multiplied twice, resulting in a dimensionality error.
* Only return column mappings where both the raw and mapped columns exist
* Do not multiple units twice when cleaning data upon import
N/A
#1837 #1838

Dimensionality Error and Column Mapping Fixes

---

.github/PULL_REQUEST_TEMPLATE.md
bin/backup_database.sh
docker-compose.local.yml
docker-compose.yml
docker/backup_database.sh
requirements/base.txt
requirements/test.txt

The latest release of Kombu breaks celery.
* lock version of Kombu
* Restrict size of docker logs
* Fix docker backup script to use TTY 
N/A
N/A

Fix backups, lock kombu

---

seed/models/data_quality.py
seed/static/seed/js/controllers/data_quality_admin_controller.js

Related dimensionality bug to #1837 
Fixes a corner case where the dimensionality of units could not be converted and data quality checks fail silently
Also fixes a bug where a data quality rule with units could not be saved as unit-less
1. Create a data quality rule for a field with units (e.g. `site_eui`) that the file you upload will definitely violate in at least 1 row
2. Follow the steps to reproduce from the dimensionality bug: #1837
3. On the mapping review page the data quality results should successfully load (no infinite spinner or 500 network error)
4. Test your `site_eui` data quality rule to have units, and again as unit-less

Data Quality Dimensionality Hotfix

---

seed/models/tax_lot_properties.py
seed/views/tax_lot_properties.py

Property and taxlot labels weren't being exported in csv files, resulting in an empty column.  This PR restores the expected behavior
From the inventory list view, select records that have labels applied to them, and click Export Selected.  The final column in the resulting csv should have the comma-separated labels
#1815

Fixed Label Export in CSVs

---

requirements/base.txt
requirements/test.txt
seed/static/seed/js/controllers/inventory_list_controller.js
seed/templates/seed/base.html
seed/templates/seed/jasmine_tests/AngularJSTests.html
seed/views/tax_lot_properties.py
vendors/package.json

Renders (and caches to prevent re-processing) building footprints when hovering over a property or taxlot footprint column
Import a file with footprints and hover over the footprint column in the inventory list view
(May require additional error handling around empty or malformed footprint fields)

Footprint preview

---

seed/tests/api/test_modules.py

Running api hosting tests were breaking on delete organization because of Redis password issues.  Attempts to rerun tests while troubleshooting would then break at creating an organization because the organization with the original hard coded name still existed. 
Uses uuid to ensure unique organization name for api create/delete organization tests.

ensure unique name for api TestOrg

---

seed/static/seed/js/seed.js

extra_data field data wasn't included on page load of the pairing page.  This PR changes it to include all fields
fixes #1875

Fix to include extra_data fields when loading the pairing page

---

config/settings/common.py
config/settings/dev.py
config/settings/docker.py
config/settings/local_untracked.py.dist
docker-compose.local.yml
docker-compose.yml
docs/source/migrations.rst
requirements/base.txt
seed/__init__.py

Redis has historically been configured to run in password free mode. In some cases, there are users that require/want to have Redis password protected.
This PR enabled the use of a Redis password.
* upgrade version of celery
* upgrade django-redis-cache
* add __all__ to init.py to start celery correctly
* fix the include dependencies of various celery configuration variables.
Note, you must now set the following in your local_untracked.py file: 
```
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
```
In development, run celery in not eager mode and make sure that the application imports data as expected.
In development, run the app in always eager mode and make sure that everything works.
Run the tests and make sure that everything works.
#1871

Enable Redis passwords

---

seed/management/commands/add_member_to_org.py
seed/models/data_quality.py
seed/models/properties.py
seed/models/tax_lots.py
seed/tests/test_labels.py
seed/tests/test_labels_api_views.py
seed/tests/test_views.py
seed/utils/generic.py
seed/views/labels.py

The goal of this PR is to include checks that ensure a Label organization and Property/TaxLot organization matches before they are associated together.
1. A pre_save check has been added for when the code starts from the Property (or TaxLot) model and associates labels that way `property.labels.add(label)`.
2. Custom logic has been added where associations were made with a `bulk_create` which bypasses any pre_save type signals. This happens via the Label API endpoint.
3. Custom logic has been added where an association is created using the through model (Property_label or TaxLot_label). This happens during DQ checks and Labeled Rules are broken.
Follow up Issue: #1887

Pairing hotfix label hooks

---

seed/lib/superperms/orgs/permissions.py
seed/tests/test_column_views.py
seed/tests/test_permissions.py

The newer viewsets do not allow for superusers to call commands on the columns and columnmappings.
Add the superuser logic to the SEEDOrgPermissions.has_perm.
Verify that users don't have excess permissions.
Verify that a user can delete column mappings as an admin to an organization that they don't belong to.
#1901

Allow superuser permissions

---

seed/api/v2_1/views.py
seed/models/column_list_settings.py
seed/models/tax_lot_properties.py
seed/serializers/properties.py
seed/test_helpers/fake.py
seed/tests/test_api_mixins.py
seed/tests/test_properties_serializers.py
seed/tests/test_property_views.py
seed/tests/test_views.py
seed/utils/api.py
seed/views/properties.py
seed/views/taxlots.py

Note that this is based off of master (called 2.5.2-patch0).
The listing of properties between version 2 and 2.1 of the API differed in the sense that there was not a way to remove fields in the 2.1 results using the profile_id setup.
* Adds the profile_id to the properties list for version 2.1 API
* Adds new helper method for extracting the show_columns from a profile_id
* Import data
* Create a profile on the properties list
* Go to the URL for the v2.1 API call and include profile_id in query param  
`{{SEEDURL}}/api/v2.1/properties/?organization_id={{organization_id}}&profile_id={{profile_id}}
* Make sure that the state data are only the fields in the profile_id.
#1879 
n/a

1879 profile id v21

---

seed/models/columns.py

Fixes two issues:
- New columns were not being created if even a single organization had a column with that name.  If the current org didn't have the column but another org did it could lose the data by adding it to extra_data without an actual column to access the data.  If no orgs had that column it would be created for the wrong org.
- Fixes a KeyError when trying to access extra_data keys that may not exist
- Have multiple orgs, and using the most-recently created org test renaming columns and verify that the data is correct afterwards.
- Rename an existing extra_data column to a different existing extra_data column, and then do the exact same rename a second time.  This should result in all `null` values for the new column
#1903 
Extra_data diff:

Fixes column renaming issues

---

config/settings/docker.py
docker-compose.local.yml
docker-compose.yml

Setting the postgresql port via an env var is consistent with the
other settings versus hard-coding.
This PR allows the port used by a SEED docker container to communicate with a postgres installation to be re-mapped eg. in a docker-compose file. Our use case was to allow a local dev installation of postgres to co-exist with one running in a container. (The local dev one typically claims 5432).
This should be a no-op if one's using the `docker-compose.yml` or `docker-compose.local.yml` provided at the root of the repo.
Testing:
1. Build a new docker container with `docker build .`
2. Change the `web` and `web-celery` images in `docker-compose.yml` to point at the image ID of the newly-created docker image.
3. Run `docker-compose up` and test that the SEED instance on …

Allows env to control postgres port in SEED docker image

---

seed/lib/mcm/reader.py
seed/lib/mcm/tests/test_data/greenbutton/example-GreenButton-data-gas-therms--3.xml
seed/lib/mcm/tests/test_reader_greenbuttonparser.py

SEED's GreenButton meter importer couldn't read files with specific units and power-of-ten-multiplier combinations. 
Specifically, this was an issue for units that the app only understands without prefixes. For example, the app understands the unit "therms" (as opposed to something like "kBtu", which has a prefix included in the name).  In that example, the application's GB meter import logic was not prepared to handle one of these un-prefixed units with a non-zero power-of-ten-multiplier. 
Notably, as of this writing, the only unit that falls in this case **and** can be found by GreenButton is actually "therms".
Logic is added to the GreenButton meter file parser to address the scenario described above.
Import GreenButton gas meters of "therms" along with 0 and non-0 …

GreenButton meter import unit reading fixes and improvements

---

docker-compose.local.yml
docker-compose.yml

Docker logs were getting too large causing out of space errors.
Limits logs to 5 files (50MB each)
* If deploying using a docker-compose file that is not under version control, then manually add `max-file: 5` to your docker file.
#1923 
N/A

Limit log count to 5 before rotating

---

requirements/base.txt
requirements/test.txt
seed/tests/test_utils_ubid.py
seed/utils/ubid.py

There was a small change to the API in the UBID API.
Enables use of new UBID API. Note that UBID-V2 is no longer supported, only V3.
The unit tests should cover the tests. Otherwise, import one of the covered building sample files and verify that the UBID imports and that the GeoJSON exports look correct in geojson.io.
#1930

Support latest API of Unique Building ID

---

seed/building_sync/tests/test_buildingsync.py
seed/building_sync/tests/test_buildingsync_views.py
seed/hpxml/tests/test_hpxml.py
seed/hpxml/tests/test_hpxml_views.py

Example files for BuildingSync and HPXML were in their respective project folders, but the tests were in the general seed/tests folder.
* breaks up the bsync and hpxml tests into their project folders
CI
n/a

move buildingsync/hpxml tests to respective dirs

---

docs/source/setup_osx.rst

Update documentation to reflect the necessary TimescaleDB version alignment (of 1.4.1) in order to allow for backups and restores of DBs.

Document recommended TimescaleDB version

---

seed/migrations/0112_refresh_matching_criteria.py

During the implementation of recent matching updates, users were given the ability to customize/choose matching criteria columns for each organization. In order to transition from pre-defined matching criteria to custom matching criteria, an initial set of matching criteria was specified for each org and the possible record types, properties and tax lots.
Unfortunately, the migration used to set this initial matching criteria across all organizations was not correctly defined. There were too many columns that were updated to be matching criteria, and some of these were extra_data columns 😨.
This caused all file imports to fail for some organizations because extra_data columns were being included in first-level database queries (i.e. `PropertyState.objects.filter(extra_data_1=...`).
This …

Refresh initial matching criteria for all orgs

---

seed/views/properties.py
seed/views/taxlots.py

Pairings should persist to both records produced from an unmerge. This was not happening, though the logic was in place - the execution wasn't quite right.  Specifically, deleting the original "target" record (the one being unmerged) occurred before the pairing relationships could be captured. 
Fixes the error above by capturing pairings sooner in the unmerge process.
Unmerge records having pairs and see that each resulting record has the pairs of the "target" record. 
Oddly enough, there is a passing test for this in the test suite, but that test seems to have been giving false positives. 
https://github.com/SEED-platform/seed/blob/200cca45bd5538b988ff9836b8133b993789a383/seed/tests/test_taxlot_views.py#L116
I suspect that this is caused by the automatic use of transactions in the test …

#1989 - Unmerge loses pairing

---

seed/views/properties.py
seed/views/taxlots.py

Attempting to edit a new record that has never been merged that came from an import file that has since been deleted from the dataset will cause the edit to fail.
Instead of saving the `import_file_id` from the original PropertyState or TaxlotState on the first edit this change will remove it.  It's not used anyway, and all other actions, like merging, similarly set this field to None when that happens.
1. In an empty organization import a file (empty org just to ensure the records don't merge with anything)
2. Delete the import file from the dataset (or delete the dataset)
3. Attempt to edit any of the imported records - it should now succeed
#1979

#1979 - Record edit failure

---

docker/postgres/Dockerfile

The version of PostGIS was over specified
Relaxes the constraint to be only the major version of postgres and postgis.
* `docker-compose build --no-cache`
* Monkey testing
#1996

Relax PostGIS contraint in docker container

---

seed/static/seed/js/controllers/inventory_list_controller.js

On the list page, whenever labels were refreshed (without the whole page refreshing), the possible labels list to choose from inadvertently included labels used in other cycles (and not the current cycle).
This happened after labels were added or removed from records and right after DQ checks (regardless of whether checks resulted in labels being applied to records).
See ticket listed below.
Generalized the "load labels" logic to scope the relevant labels to those within the current cycle. Applied this logic on page load as well.
For an org with label-having-records, identify labels that are unique to different cycles. When any of the above mentioned actions are taken, see that only the labels unique to the current cycle show up in the cycle options dropdown.
#1818

Inventory list labels scoped whenever labels are reloaded

---

seed/models/tax_lot_properties.py
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/scss/style.scss
seed/tests/test_property_views.py
seed/tests/test_taxlot_views.py

See ticket linked below.
- TaxLotProperty's get_related returns merged_indicator for both "base" and related records
- Inventory List pages show merged indicator for records
Visit one of the inventory list pages and for all records that were products of automatic or manual merges, see a merged indicator. 
#1409

Merged indicator

---

Dockerfile
package.json

The latest version of libgeos (released 10/5/2019) does not work with the shapely library. It actually appears that libgeos.so does not work at all on alpine.
```
/ # ldd /usr/lib/libgeos.so
ldd (0x7fcc14fd7000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fcc14c84000)
libc.musl-x86_64.so.1 => ldd (0x7fcc14fd7000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fcc14a72000)
Error relocating /usr/lib/libgeos.so: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/libgeos.so: _ZNSt13runtime_errorC2EOS_: symbol not found
Error relocating /usr/lib/libgeos.so: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```
* Pull the base image from Docker hub (SEED Version 2.6.1)
* Comment out installing all the OS …

Docker build failes with libgeos error

---

seed/static/seed/js/controllers/mapping_controller.js
seed/static/seed/partials/mapping.html

During file import, the property and tax lot matching criteria was presented in one list, which wasn't very clear for users.
Splits out the matching criteria by inventory type.
Visit the import mapping page and see that current matching criteria is displayed by inventory type.
#2028

Import mapping page - Group matching fields by table name

---

seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/show_populated_columns_modal_controller.js
seed/static/seed/partials/inventory_detail.html
seed/static/seed/scss/style.scss

Adds "Only Show Populated Columns" to inventory detail page. 
**NOTE**: The current and historical states of a record are considered when looking for populated fields (as well as the extra data for each).
Test the new button works just like the one in the inventory list page.
#1715

1715 inv detail pop cols only

---

seed/tests/test_property_views.py
seed/tests/test_taxlot_views.py
seed/views/properties.py
seed/views/taxlots.py

See issue linked below.
This PR adjusts the initial edit process for records (both properties and tax lots).
Just like before, for an initial edit, a copy of the record is created and used to preserve the initial import history. Now, this copy is created as the very first step, without the "initial edit" changes **first**, as opposed to creating the copy with the changes included. The new copy is then run through the normal (non-initial) edit flow.
This allows the presave hook to trigger.
For "new" (just imported) records that were geocoded on import, edit them while removing latitude and longitude. See that the `geocoding_confidence` and `long_lat` are no longer populated.
For "new" records that were not geocoded on import, edit them while changing a latitude and longitude. See that the …

1998 lat long initial edit

---

seed/static/seed/js/controllers/export_inventory_modal_controller.js
seed/static/seed/partials/export_inventory_modal.html
seed/tests/test_tax_lot_property.py
seed/views/tax_lot_properties.py

Appends Notes to records when exporting records.
**Issue/Caveat:** Since the file exports are generated in the backend, the "created" time for each note is always provided in the app's default timezone, 'America/Los_Angeles'. I've spent some time trying to prevent this, but was not successful. Since the users requesting this are from San Jose (within that timezone), I'll just be creating an issue for this.
Extra details regarding this: When a note is created via the browser, the DB entry for this note seems to use the machine's current local timezone. When that note is read from the DB into Django (and subsequently, into the export file), it's automatically converted to 'America/Los_Angeles' regardless of my own actual timezone.
**Also**, this hides the tax lot excel …

Notes are added to record exports

---

seed/static/seed/js/controllers/mapping_controller.js

When a new preset created within the import mapping process, it's now given defaults for each raw_column as follows:
- DB-aware column
- string provided by user (not in DB yet)
- empty string
#2060

Mapping preset creation during import has correct initial snapshot

---

seed/tests/test_api.py

A hardcoded year within a test was referencing a value generated by the current calendar year. 
The value is generated here: https://github.com/SEED-platform/seed/blob/develop/seed/models/cycles.py#L34
Update the value in the test to also be generated by current calendar year.
- See that test suite passed

Update hardcoded date within test

---

CHANGELOG.md
seed/views/portfoliomanager.py

The latest round of ESPM updated broke the ESPM import for SEED.
* Use new endpoints for retrieving ESMP data
* Parse the new result of the unofficial API
* Click add data file
* Select import from Portfolio Manager
* Verify that both a normal report and a child report can successfully import
#2076

Update ESPM Endpoints

---

seed/static/seed/js/controllers/inventory_detail_notes_controller.js
seed/static/seed/js/controllers/inventory_detail_notes_modal_controller.js
seed/static/seed/js/services/note_service.js
seed/static/seed/partials/inventory_detail_notes.html
seed/static/seed/partials/inventory_detail_notes_modal.html

Add update and delete buttons for notes, making use of the same modal to help users accept/use new functionality. See screenshots below.
Update and delete notes.
#2013 
Initial Buttons
Update modal
Delete modal

Ability to delete notes

---

seed/models/data_quality.py
seed/static/seed/js/controllers/data_quality_modal_controller.js
seed/static/seed/partials/data_quality_modal.html
seed/tests/test_data_quality_checks.py
seed/tests/test_labels.py
seed/views/data_quality.py

During Inventory List DQ check, show the labels that were applied to records (added to -Views) in the results and the export.
For each inventory, add a label to a DQ check/rule. Trigger that check with a record(s) via Inventory List DQ check. See the label in the modal, then export the results to see the label in the export.
#1819

Applied Labels show up in DQ checks results and results export

---

seed/static/seed/js/controllers/column_mappings_controller.js
seed/static/seed/js/controllers/mapping_controller.js

Within the organization presets page, a bug was preventing presets from being saved after switching between presets via the dropdown.
To provide more technical detail, the issue related to an assumption I made that I was passing the POST request a collection of mappings using a variable with a _reference_ vs a value.
Fixes the bug mentioned above.
AND also, includes a small clean up that disables the "Map your data" button the import mapping page on initial load. This wasn't needed before since the page previous loads with suggestions preloaded.
Edit and save mapping presets.
I'd also suggest monkey testing all aspects of CRUDing mapping presets.
This is a clean up for #1759

1759 column mapping presets bug fix

---

seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/services/inventory_service.js

Stores the choice of an item from the cycles dropdown menu in local storage.  
`Data` > `Add Data to Files` > `Select` > `Dismiss` Repeat to find your selection is cached
Addressing #2023

Persistant drop down cycle choice

---

seed/static/seed/js/controllers/data_quality_admin_controller.js

Save changes button inconsistency: if a user delete a rule for the first time, save button activate for saving the change. Upon clicking on "save" button and if user deletes another rule right after, "save" button stays gray and inactivate.
Reactivate "save" button after user delete a rule/rules and save changes.
1. Delete a rule, hit "save";
2. Right away, delete another rule;
3. Should see "save" button is reactivated.
#2114 
1. Before deleting a rule (address line 1):
2. Delete address line 1, save button lit up for click;
3. Save changes after deleting address line 1:
4. Immediately, delete another rule (conditioned floor area), save button is reactivated:

Issue #2114 - Reactivate save button after deleting a rule and save changes.

---

.travis.yml
CHANGELOG.md
config/settings/travis.py
seed/tests/test_api.py
seed/views/portfoliomanager.py

While SEED 2.6.1 was deployed to `prod`, there were several, loosely related code changes involving fixing broken tests. The most meaningful of those was a patch to update the ESPM login view within SEED. The other two changes involved the calendar year change from 2019 to 2020 as well as TravisCI expecting Postgres to use port 5433 (vs 5432).
For 2.7. 0, cherry-picks 3 commits for each of the 3 required changes listed above.
Here's the source of each of the 3 commits:
- [add changelog entry](https://github.com/SEED-platform/seed/pull/2077/commits/c1b51b943036f8e47450262a39c8332dba9b3dd0)
- [Update hardcoded date within test](https://github.com/SEED-platform/seed/commit/9204fcd504d52e6424a8de17fac4b98542f6568c)
- [Update TravisCI config for Postgres to use port …

Espm and tests 270

---

seed/migrations/0111_rehash.py
seed/migrations/0120_created_updated_col_objects.py
seed/migrations/0121_update_updated_timestamps.py
seed/models/columns.py
seed/models/tax_lot_properties.py
seed/static/seed/partials/inventory_detail.html

-State created and updated values needed to be enabled/used on the FE.
See the associated PR below for more details.
This is a direct cherry-pick of the merge commit from https://github.com/SEED-platform/seed/pull/2149 with no modifications: 
`git cherry-pick -m 1 eb9a7ccd912cb70396eac7d5a7401455659cd378`
Ideally this would be run on a recent copy of the production database. The `created` and `updated` values produced for existing records should be relatively close to those on the production server. 
Spot checking should be conducted:
Also, historical -States should have created and updated values.

Enable and use created and updated for 2.7.0

---

seed/data_importer/tasks.py
seed/data_importer/tests/integration/test_data_import.py
seed/data_importer/views.py
seed/models/building_file.py

After moving BuildingSync import into the normal import/mapping flow, I realized there were a few issues:
1. the mapping task was not idempotent - multiple building files, property states, etc were duplicated each time
2. we created the Scenarios, Meters, and other models associated with the property too soon (during the mapping), and should defer until the user is done and wants to finish the import.
Addresses the issues above:
1. ensures mapping can get called multiple times
2. defers the creation of additional models by creating a new task that BuildingSync imports will take, rather than the property merging/matching step.
NOTE: as mentioned above, BuildingSync imports don't go through the merging step. This is how the import of BuildingSync files worked originally before moving it …

fix(buildingsync): defer creation of bsync models until last task

---

seed/static/seed/js/controllers/menu_controller.js
seed/static/seed/js/controllers/modified_modal_controller.js
seed/static/seed/js/seed.js

Since late February URLs have had a ton of unnecessary params added on:
`https://dev1.seed-platform.org/app/#/properties?=%2F%7Binventory_type:properties%7Ctaxlots%7D`
instead of
`https://dev1.seed-platform.org/app/#/properties`
Fixes it.  The main issue was calling $location.search.
Related bug: https://github.com/angular-ui/ui-router/issues/3416
Look at the address bar

Fixed unnecessary URL params

---

seed/api/base/urls.py
seed/api/v3/__init__.py
seed/api/v3/urls.py
seed/utils/api_schema.py
seed/views/data_quality.py
seed/views/v3/data_quality.py

With this PR, I'm looking to establish a pattern to build, maintain, and standardize the API definitions that will be used by Swagger. We'll likely iterate on this pattern as we come across different cases while building out v3.
**Note, the FE code doesn't reference the new data_quality_checks endpoints nor are they updated as required for v3. This is only to be used as a reference for using AutoSchemaHelper.**
The AutoSchemaHelper class will be used to create Schema classes that will be applied to ViewSets.
Given that some v1, v2, v2.1 endpoints will be updated heavily changed, we'll be copying/creating ViewSet classes to the `./seed/views/v3` directory as shown in this example.

Initial AutoSchemaHelper example

---

config/settings/common.py
config/urls.py
requirements/base.txt
seed/static/seed/js/controllers/api_controller.js
seed/static/seed/partials/api_docs.html
seed/static/seed/scss/style.scss
seed/utils/api_schema.py
seed/views/v3/data_quality.py

We needed to move away from the, now deprecated, django-rest-swagger as a schema generator/renderer. (Not to be confused with django-rest-**framework**, which is still being used 😄 .)
Swagger page now uses drf_yasg.
**Reminder to refresh installed packages.**
Check the Swagger page still renders. See that the v3 DQ endpoints are documented and "trying" each of the endpoints should work.
For code review, each commit can be used to break up and partition review. The last commit is a small clean up item.
For the https://github.com/SEED-platform/seed/pull/2188/commits/78fb1a849009978b549265b5076970d992b48e88 commit, it might be easier to review the resulting code as opposed to code diffs as the diffs shown by GH are not as readable in my opinion.
Also note that there are AssertionErrors being …

Shift Swagger Schema Generator to drf-yasg

---

seed/data_importer/tests/integration/test_data_import.py
seed/models/building_file.py
seed/models/scenarios.py
seed/tests/test_building_file.py
seed/tests/test_property_views.py
seed/utils/meters.py
seed/views/meters.py

Bug: update with buildingsync resulted in scenarios from new file not getting linked to new property state
Fixes that
Also adds tests for BuildingFile that were taken from the bricr branch
- Upload bricr workflow buildingsync file, verify scenarios were uploaded on the property details page. Also go to Meters page and verify that you see the meter data and can filter by scenario.
- Do an "Update with buildingsync" with the same file again, and verify you still see scenarios as well as the meter data
- Do an "Update with buildingsync" with ex1.xml (has no scenarios or meter data) and the scenarios and meters should not be shown (they are no longer linked to the current property state)

patch(building_file): update buildingfile property state to link scenarios

---

seed/utils/meters.py

Small patch for mistyped query parameter. This isn't a current issue (ie it should not actually cause runtime exceptions) but is an error nonetheless.

patch(meters.py): handle mistyping

---

seed/views/properties.py

After merging and deploying to dev1, the current temporary fix of redirecting to maintenance page should be removed.
Swagger page was slow. Lately, it's been enough to crash dev1.
Remove select_related slowing down swagger page.
This will slow down the actual endpoint for anyone that uses it. But it doesn't seem to be used on the frontend. Also, tests pass when the endpoint is disabled. As to whether this is old and should be deprecated, that conversation should be had in building API v3.
Load the swagger page and see it loads much faster.

PropertyViewViewSet - remove select_related slowing down swagger page

---

seed/building_sync/mappings.py
seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml
seed/management/commands/create_geojson_test_data.py
seed/models/column_list_settings_columns.py

ATT added parsing of Assessor parcel number from City Custom Building ID.
Parses premise_id from City Custom Building ID
Upload bricr workflow xml, verify that the premise_id contains the SF parcel number (should be SF000011).

chore(mappings.py): get premise id from city custom building id

---

seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml
seed/building_sync/tests/test_validation_client.py
seed/building_sync/validation_client.py
seed/data_importer/tasks.py
seed/data_importer/views.py
seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/services/uploader_service.js
seed/static/seed/partials/data_upload_modal.html

Adds an extra step to validate schema and use case when importing BuildingSync files
Also removes some vestigial front-end code for the old buildingsync import flow.
These tests should probably be run with and without celery workers, ie in local config include/exclude these lines
```bash
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
```
When testing celery workers, it might be worth setting the log level to debug so messages can be seen: `celery ... -l debug`. Note that you WON'T see any messages when not running workers
Files for testing:
[use_case_data.zip](https://github.com/SEED-platform/seed/files/4704360/use_case_data.zip)
- navigate to the data upload modal, click upload buildingsync
- select the file `buildingsync_v2_0_bricr_workflow.xml`
- if looking at the …

Using selection-tool for bsync validation

---

seed/tests/test_data_quality_rules.py
seed/views/data_quality.py

DQ Rules could inadvertently be deleted. See tagged issue for more details.
Cherry-pick changes from 2.7.0-patch1.
- Performs validity checks on incoming DQ Rule updates _before_ the teardown and rebuild of DQ Rules (a pattern that is slated to be removed).
- Skips over DQ Rules that could not be recreated instead of stopping the recreation process entirely.
Try to save a "Valid Data" Rule without a label. See that nothing gets saved, and we get the same 400 we got from before. Refresh the page and see that nothing was lost either.
Try to save a Rule as Must Contain or Must Not Contain while keeping the text field blank. See that nothing gets saved, and we get the same 400 we got from before. Refresh the page and see that nothing was lost either.
For code review, commits can be reviewed …

2202 deleted dq rules

---

seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml
seed/building_sync/tests/test_validation_client.py
seed/building_sync/validation_client.py
seed/data_importer/tasks.py
seed/data_importer/views.py
seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/services/uploader_service.js
seed/static/seed/partials/data_upload_modal.html

This is the sister-pr to https://github.com/SEED-platform/seed/pull/2234
Adds an extra step to validate schema and use case when importing BuildingSync files
Also removes some vestigial front-end code for the old buildingsync import flow.
These tests should probably be run with and without celery workers, ie in local config include/exclude these lines
```bash
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
```
When testing celery workers, it might be worth setting the log level to debug so messages can be seen: `celery ... -l debug`. Note that you WON'T see any messages when not running workers
Files for testing:
[use_case_data2.zip](https://github.com/SEED-platform/seed/files/4718996/use_case_data2.zip)
- navigate to the data upload modal, click upload buildingsync
- …

Using selection tool for bsync validation

---

seed/models/data_quality.py

To give rule "Address line 1" a default data type so that a text field is given to this specific rule instead of min/max values.
Go to dq taxlots view. Hit "Reset Rules" or "Restore default rules". Should expect to see rule "Address line 1" prompts with a text field for input.
#2238

#2238 Added data type to taxlots rule "Address line 1"

---

seed/api/v3/urls.py
seed/views/v3/import_files.py
seed/views/v3/meters.py
seed/views/v3/properties.py

Moves and refactors v2 meters endpoints into v3
Test the endpoints on the swagger page:
- `api/v3/meters/valid_types_units`
- `api/v3/import_files/{id}/greenbutton_meters_preview`
- `api/v3/import_files/{id}/pm_meters_preview`
- `api/v3/properties/{id}/meter_usage`
- `api/v3/properties/{id}/meters`
#2252

2252 refactor/api v3 meters

---

seed/static/seed/js/services/uploader_service.js

Fixes a bug where anyone who is not a superuser is not able to upload a buildingsync file. Issue was the view had `has_perm_class('can_modify_data')` but the service on the frontend was not adding `organization_id` as a query parameter, so authz fails.
Log in as an Owner or Member, you should be able to navigate to the data upload modal, select buildingsync, then get a validation response.
Addresses Robin's comment from #2024 where the page returned a 403

fix(uploader_service): add org id as query param for authz

---

seed/api/v3/urls.py
seed/serializers/taxlots.py
seed/utils/api_schema.py
seed/views/v3/notes.py
seed/views/v3/taxlots.py

Moves and refactors api v2 taxlot endpoints to api v3. Note that the v2.1 endpoints are _not_ included in this PR
Go through all `api/v3/taxlots/*` endpoints on swagger page
#2251

2251 refactor/api v3 taxlots

---

seed/api/v3/urls.py
seed/views/v3/building_files.py
seed/views/v3/properties.py

Adds the building_files endpoint to v3 api, and fixes an issue with the hpxml export
Test the `api/v3/building_files/*` endpoints. Additionally, test `api/v3/properties/{id}/hpxml` for a view that _was_ imported using hpxml, and for a view that was not (ie made from or updated with buildingsync file). For the second case it should still succeed, whereas previously this would fail b/c it was trying to parse the BuildingSync file as an hpxml file.
#2253

2253 refactor/api v3 building file

---

config/urls.py
seed/api/v3/urls.py
seed/views/v3/portfolio_manager.py
seed/views/v3/progress.py
seed/views/v3/tax_lot_properties.py

Make changes per tagged issue.
Test endpoints on Swagger page
#2254

2254 api v3 misc

---

seed/views/v3/properties.py

Originally I dropped the v2.1 properties list view. This adds it to v3
Add a search view for advanced filtering of properties
Test filtering at `v3/properties/search`
#2250

feat(v3/properties): move v2.1 filtering to v3 search view

---

seed/views/v3/properties.py

There were errors on the Swagger page that were cleaned up. A new one was introduced when a -ViewSet began inheriting from DRF's GenericViewSet. This inheritance required that a `queryset` attr be set or the `get_queryset()` method be defined for that ViewSet class.
Fixes that most recent issue.
Load the Swagger page and see that no errors are shown.
#2232 - original ticket to clean up Swagger page errors
and
#2279 - PR that inadvertently introduced these errors

API v3 properties - queryset attr set as empty QS for swagger

---

seed/models/data_quality.py
seed/static/seed/js/controllers/inventory_list_controller.js

In cases that a Rule with "valid" severity and a "range" condition is triggered, a line is **not** included in the DQ Check results. Because of this, it's possible for SEED to hang when trying to display the label that is accompanied with that triggered rule.
See the attached issue to see how this was discovered.
This PR implements a flag to allow for the application of the label to the record while avoiding the attempt to display the applied label in the result.
In addition, the following inventory list label clean ups are included here as well:
With labels applied, the following actions would remove selected and valid (is_applied) labels.
- Run DQ check - Now selected labels should remain.
- Switch cycles - Now, only no-longer-applicable labels are filtered out.
- Remove selected label …

2290 dq valid label results fix

---

seed/static/seed/js/controllers/column_settings_controller.js
seed/static/seed/js/controllers/data_quality_admin_controller.js
seed/static/seed/js/controllers/rename_column_modal_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/columns_service.js
seed/static/seed/js/services/inventory_service.js
seed/static/seed/partials/data_quality_admin.html
seed/static/seed/tests/data_quality_admin_controller.spec.js
seed/views/properties.py
seed/views/taxlots.py

When defining DQ Rules, we realized it would be helpful to flag fields that were not mapped by an organization. 
See attached issue for more details.
This PR introduces an indicator on the DQ admin page that shows which fields have been mapped to during file imports. In the backend, the mapped, or "used", columns are flagged by checking if `ColumnMapping.objects.filter(column_mapped=[col_object]).exists()`. [This check existed already and didn't need to be written.](https://github.com/SEED-platform/seed/blob/4baeb3441f92a4e886d2d28c515dde39289f05c7/seed/models/columns.py#L1321-L1323)
Note that no checks are performed on the actual inventory records as that operation could potentially be very expensive.
Visit the DQ admin page, and see that a ** is added to indicate fields that have not …

2286 dq indicate mapped fields

---

seed/serializers/labels.py
seed/tests/test_labels_api_views.py

For label read endpoints, we were missing some tests to ensure a vital aspect of these endpoints worked. That is, the addition of an "is_applied" key to serialized label records.
As a followup point, it was decided that the "is_applied" key should only really be present when the search for records actually happened. When the search did not happen, SEED would still provide the key without any record IDs, giving the impression that a search did actually happen, but no record IDs were found.
Add testing for the is_applied field.
Also, make updates to the serializer to remove the "is_applied" key when the search for is_applied records did not occur. 
Ensure that the API v3 label read endpoints still work on the Swagger page.
Test that the inventory list page still can fetch labels that are …

2164 label is applied

---

seed/api/v3/urls.py
seed/serializers/properties.py
seed/views/v3/property_views.py

See related Issue and PR.
Add property_views endpoints to API v3.
Also, fix a related serializer affecting write operations (essentially cherry-picked from linked PR) for these endpoints as well as another serializer affecting the write operation for canonical Property endpoints (gbr_properties).
Test the property_views endpoints on the Swagger page. For the /v3/property_views/ POST endpoint, remove the _data fields from the nested State object to be created (created by not providing the "id" key (from `"state": { "id"...`). 
Also test the /v3/gpr_properties/ POST endpoint while removing the "created" and "updated" fields.
Issue #2263 
PR #2288

2263 api v3 add property views

---

seed/static/seed/js/controllers/data_quality_admin_controller.js
seed/static/seed/partials/data_quality_admin.html
seed/static/seed/tests/data_quality_admin_controller.spec.js

On the DQ admin page, it was possible for the the "Save Changes" button to not be re-enabled when expected.
See attached issue for a specific case.
Removes extra logic around deciding whether a rule change has happened on the DQ admin page and clean up relevant methods (rename and delete no longer used variables).
Make changes on the DQ admin page, see that the Save Changes button is enabled.
Also, take the steps detailed in the attached issue to ensure that the original "steps" taken to discover this bug no longer yields this bug.
#2289 
Should also address #1848

2289 dq admin save button fix

---

seed/static/seed/js/controllers/column_settings_controller.js
seed/static/seed/js/controllers/data_quality_admin_controller.js
seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_settings_controller.js
seed/static/seed/js/services/inventory_service.js
seed/static/seed/js/services/label_service.js
seed/static/seed/js/services/uploader_service.js
seed/static/seed/partials/data_quality_admin.html
seed/static/seed/scss/style.scss

See issue
The DQ Admin page doesn't guess condition when Field values is changed for one of the rules.
In addition, validations have been added to `condition` and `data_type`. These are triggered whenever `condition`, `field`, and `data_type` values are changed. Warning messages are provided to help users "fix" any invalid rules.
Visit DQ admin page, and change the Field value for one of the rules. See that the Condition doesn't change.
In addition, monkey test changing the `condition`, `field`, and `data_type` values for rules.
#2281

DQ Admin page - doesn't guess condition when field changes

---

seed/static/seed/js/controllers/column_settings_controller.js
seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js

Could not save Column display_name since that particular key was being converted to `displayName` once columns were received from the backend. 
Previously, `displayName` was being converted to `display_name` when the `diffs` were built. This worked before since we were sending the `diffs` with PATCH requests. 
Now, we're sending PUT requests with all the model details, and diffs aren't being used directly. Instead, the diffs are being used to find the relevant objects.
Just before the PUT requests are sent, use the `displayName` to provide the `display_name` for each object.
Test that you can change `display_name` for Column objects. Also verify that the change is still shown in the column save confirmation window.
#2324

Col settings - "display_name" is only re-added before save

---

seed/serializers/pint.py
seed/tests/test_views.py

Non-default display settings for an organization can cause issues when hand editing and updating affected fields. See the attached issue for more details.
When updating a record, the values provided from the frontend are considered to be in the appropriate units. For example, if the area display setting is meters squared, the value entered for gross_floor_area is taken as meters squared.
On the organization settings page, use a non-default display unit for either areas or EUIs.
Hand-edit any record to change an area or EUI field value and see that the value is saved and displays as expected (i.e. if you input "100", you see "100").
#2333

2333 - Hand edit QuantityField bug

---

seed/static/seed/js/controllers/mapping_controller.js

See tagged issue.
On the import mapping page, when applying a preset, checks are now performed.
Also, clean up the inventory type dropdown check on that page.
Make sure these work as expected when importing a file:
- apply a preset that would trigger duplicate mappings to happen for different raw fields.
- apply a preset with a mix of tax lot and property fields.
#2371 
Note that https://github.com/SEED-platform/seed/pull/2372/commits/e2c4a49a1c5091d68f5a8616c5985f4d2e9641c3 needs to be cherry-picked into 2.7.2.1

2371 dup mapping develop

---

seed/api/v2/urls.py
seed/views/projects.py

Our swagger json was invalid, but we could never actually test it because it requires you to be logged in (and the third-party validator can't access it)
Small tweak to the unused _projects_ api just to get the json to a valid state
```json
{
"messages": ["attribute paths.'/v2/projects/{id}/move/'(put).operationId is repeated"]
}
```
```json
{}
```
Browse to `/api/swagger/?format=openapi`, copy the raw json to a web server that is open to the internet, and submit to `https://validator.swagger.io/validator/debug?url=URL_HERE`
#2375 adjacent

Fix Swagger Validation

---

seed/api/v2_1/views.py
seed/views/properties.py

Leaving out the `organization_id` parameter or providing an invalid one would result in a 500 error for `/api/v2/properties/columns/`
Returns proper 400 and 404 errors
Test the following URLs with valid and invalid org ids, make sure json is always returned:
/api/v2/properties/columns/?only_used=false&organization_id=1
/api/v2/properties/columns/?only_used=false&organization_id=9999
/api/v2/properties/columns/?only_used=false

500 errors for /api/v2/properties/columns/

---

seed/static/seed/js/services/dataset_service.js
seed/static/seed/js/services/uploader_service.js
seed/tests/api/test_modules.py
seed/tests/api/test_seed_host_api.py
seed/tests/test_api.py
seed/tests/test_project_views.py
seed/tests/test_views.py

Part of the effort to move FE and tests to v3 APIs
Update tests and frontend _services to use API v3 dataset endpoints
- On the dataset list page, CRUD datasets
- On the dataset detail page, CRD import_files
- On the inventory detail meter page, upload GreenButton data, see a list of datasets
- On any page, expand the left menu to view the count of datasets
#2310

2310 datasets v3 transition

---

seed/tests/test_portfoliomanager.py
seed/views/v3/portfolio_manager.py

When an espm template has only one property, it is returned as a dictionary object as SEED expected a list of records. Import espm with single property failed to proceed to data mapping.
Append single property espm template/record to a list object for upload.
Create an espm with 1 property. Import a espm template with one property and expect it to be successfully imported for mapping.
#2384 
Create an espm with 1 property:
From SEED, import espm:
Expect to see report successfully added:

ESPM single property report for upload and test

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/tests/api/test_modules.py
seed/views/v3/tax_lot_properties.py

Fixes problem where exporting from the property detail page resulted in empty files. This was fixed by refactoring the `taxlot_properties/export` endpoint to accept View IDs rather than canonical IDs. This change required updating the frontend for the list view, as it was using canonical IDs.
1. Upload properties and taxlots
1. From inventory list page, select multiple properties and choose the "export selected" action. Verify that:
- all selected properties were exported
- the properties are in the same order as they appeared in the table
1. On a property details page, select "export buildingsync (excel)". Verify it exported correctly
1. Verify other export options still work as expected (CSV, geojson, etc)
1. Repeat for Taxlots (note you can't export excel for taxlots, and cant export …

2370 fix/bsync excel export

---

seed/static/seed/js/controllers/mapping_controller.js

Cherry-picks changes made into `develop` into 2.7.2.1 (#2372)
The bug was the result of a lack of duplicate column mapping checking when applying a mapping profile.
See issue for more details on the bug.
Add dup check when applying a profile.
Test on 2.7.2 database.
1. Import a file. 
2. Map to the same column twice.
3. Save preset.
4. Refresh page.
5. Apply that previously saved preset.
6. See an error.
#2371

Import mapping - check for duplicates when applying profile

---

seed/migrations/0130_auto_20200924_1337.py
seed/models/column_mappings.py
seed/static/seed/js/controllers/column_settings_controller.js
seed/static/seed/js/controllers/delete_column_modal_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/columns_service.js
seed/static/seed/partials/column_settings.html
seed/static/seed/partials/delete_column_modal.html
seed/templates/seed/_scripts.html
seed/views/v3/columns.py

- Limits `DELETE /api/v3/columns/XXX/` to only extra_data columns
- Adds a delete button to extra_data columns on the org's column_settings page
- Import a file with columns mapped to extra_data fields (new or existing)
- Go to the column_settings page for the org and click the delete button next to extra_data fields
- Monkey test with deleting columns, reimporting data and recreating the column, attempting to delete non-extra_data columns, etc
#1904
When a column is deleted the column mapping with the raw column_name also has to be deleted.  If you go back to the Data Mapping for an imported record from the dataset the original data will still appear in the preview, but if you click the button to review the mapping the deleted column will no longer appear (which is expected once the …

#1904 - extra_data columns can now be deleted

---

seed/views/v3/column_list_profiles.py

Before, when the ComStock list profile feature was built, it originally injected data before serialization of response data.
Since then, the serializer was updated to expect data in a different format.
As a quick fix, the "fake" ComStock list profile is injected after serialization.
Enable ComStock in org settings.
Navigate to Column Settings and set some ComStock Mappings
Visit the property inventory list page and see that the ComStock profile works
Visit the column list profile page and see the ComStock profile is uneditable.

API v3 - Append ComStock list profile after serialization

---

docs/source/developer_resources.rst

When restoring a dump to a different deployment the site's URL and name will likely no longer match (e.g. SEED v2 ->Dev1).  If this URL is incorrect then password reset emails will link to the wrong site (and won't function).
Adds instructions to `developer_resources.rst` with the steps to update the site name and URL.

docs: restore site settings

---

.gitignore
lokalise.cfg.example
lokalise.yml.example
script/get_angular_translations
script/get_python_translations

Regarding lokalise v1:
"This version of CLI tool is depreciated. We will stop supporting requests sent using this version of CLI at November 1st 2020. Use Lokalise CLI v2 instead."
From:
https://docs.lokalise.com/en/articles/1400697-lokalise-cli-v1
Updates scripts and related files to use v2 instead of v1

fix: updated scripts to use lokalise2

---

.github/workflows/ci.yml

Travis is mean, and this is a temporary workaround.
EDIT:
Travis is forcing public repos to move from .org to .com, see here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
We moved seed's repos to the .com site, and then they announced a new pricing model: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
TLDR; is that you have to request credits now if you're OSS, I reached out to them about this but haven't heard back yet.
Important part:
> Building on a public repositories only
We love our OSS teams who choose to build and test using TravisCI and we fully want to support that community. However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators …

feat(ci): use github actions for ci

---

seed/views/v3/organizations.py

The test `test_report_export_excel_workbook` randomly failed, and we were able to reproduce by changing the ordering of property views in `get_raw_report_data`.
Adds an order_by condition to deterministically order property views

fix: order exported results by property view id

---

seed/data_importer/tasks.py
seed/data_importer/tests/integration/test_case_a.py
seed/data_importer/tests/integration/test_case_b.py
seed/data_importer/tests/integration/test_data_import.py
seed/data_importer/tests/integration/test_demo_v2.py
seed/data_importer/tests/integration/test_matching.py
seed/data_importer/tests/integration/test_merge_duplicate_rows.py
seed/data_importer/tests/integration/test_properties.py
seed/data_importer/tests/integration/test_tax_lots.py
seed/data_importer/tests/test_link_incoming.py
seed/data_importer/tests/test_match_incoming.py
seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/tests/test_import_file_views.py
seed/tests/test_match_existing.py
seed/tests/test_meter_usage_import.py
seed/tests/test_organization_views.py
seed/tests/test_property_views.py
seed/tests/test_taxlot_views.py
seed/utils/geocode.py
seed/views/v3/import_files.py

When importing a large file, you can experience timeouts when starting the final saving process by clicking "Save Mappings". This was happening because in the `start_system_matching_and_geocoding` endpoint, we would start the geocoding task, then block until we got the result, before finally kicking off the matching task and returning the progress data. If the geocoding task took a while to run, or was blocked itself because the worker(s) were already occupied (data quality checks are probably still running for a large file) then it's going to block for a long time. In our case, ELB would timeout after 60s and return an empty HTTP response (which cloudflare doesn't like, and ends up giving a 520 response).
This address the timeout by not blocking on the geocoding task. Specifically, I …

#2079 refactor(tasks): run geocoding task in celery

---

docker/nginx-seed.conf
docker/uwsgi.ini

We've seen occasional error messages over time like `OSError: write error`.  uWSGI documentation classifies this primarily as an "annoyance", like if the user disconnects and nginx closes the socket but uWSGI is still working.  The following SO links suggest config improvements to handle these:
https://stackoverflow.com/a/45393743/2730450
https://stackoverflow.com/a/40375474/2730450
Adds the recommended settings based on SO results

fix: add nginx/uwsgi protections for oserrors and ioerrors

---

seed/models/columns.py

For organizations in the production database, there existed multiple Column records for a single raw header. These "duplicate" Column records were technically different because of their `unit` values. SEED had some logic to help deduplicate these records, but that logic included an invalid Django command that threw an error.
Fix the invalid Django command and close up known ways that "duplicate" Columns are created again in the future.
For an organization, find or create 2 or more Column records for the same raw field header.  Import a file that uses that header. See that the mapping step of the import process is successful.
This error came up in production, and it was initially difficult to debug because of the deduplication logic. As a first step to deduplication, all the duplicate …

fix(columns): dedup raw col objs caused by units

---

seed/tests/test_match_existing.py

Intermittent failed test re: merging properties with meters.
The testing logic implicitly relied on querying Properties in ID order. That is made explicit with this PR.
Nothing to do but wait and see if this intermittent failure happens again.
```
Traceback (most recent call last):
File "/seed/seed/tests/test_match_existing.py", line 1342, in test_match_merge_link_for_properties_meters_persist_in_different_situations
self.assertTrue(agg_meter.meter_readings.filter(reading=100).exists())
```

fix(intermittent failed test): implied ordering is explicit

---

config/settings/common.py
requirements/base.txt
requirements/test.txt
seed/utils/viewsets.py

Test weren't able to run because pip couldn't install several packages. See the list of errors faced and steps taken during debugging: 
```
ERROR: Requested pnnl-buildingid from git+https://github.com/SEED-platform/buildingid.git@f68219df82191563cc2aca818e0b0fa1b32dd52d#egg=buildingid (from -r requirements/base.txt (line 64)) has different name in metadata: 'pnnl-buildingid'
```
Fixed by adding `pnnl-` to `egg` value.
```
ERROR: Cannot install -r requirements/base.txt (line 72) and oauthlib==2.0.2 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested oauthlib==2.0.2
django-oauth-toolkit 0.12.0 depends on oauthlib==2.0.1
```
Fixed by upgrading to `django-oauth-toolkit` to 1.0.0, since `jwt-oauth2` requires `oauthlib==2.0.2`.
```
ERROR: …
```

fix(python-deps): upgrade packages with conflicting versions/specs

---

seed/analysis_pipelines/bsyncr.py
seed/analysis_pipelines/pipeline.py
seed/serializers/analyses.py
seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/partials/inventory_detail_analyses_modal.html
seed/tests/test_analysis_pipelines.py
seed/views/v3/analyses.py

SEED is adding ability to run analyses on properties.
Adds endpoint to create an analysis and start its preparation. Also adds FE logic for the analysis modal so you can create an analysis.
Go to a property's analysis tab, click new analysis and create a bsyncr analysis. For it to actually work you'll need to have bsyncr configured (see #2477 ) and the property will need to have 12+ electricity meter readings.
#2475

#2475 feat: analyses create view

---

seed/analysis_pipelines/bsyncr.py
seed/analysis_pipelines/pipeline.py
seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/partials/analyses_table.html
seed/views/v3/analyses.py

Adds FE functionality for starting an analysis from org and property detail pages.
- on property detail page, create a bsyncr analysis
- click the play button next to the analysis name
- create another one on property detail page, then go to the org analysis page and start it from there.
#2499

2499 feat: start analysis frontend

---

seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
seed/static/seed/partials/analyses.html
seed/static/seed/partials/inventory_detail_analyses.html
seed/static/seed/scss/style.scss

I am bad at css and javascript
Adds disabled status for play button if analysis is being prepared.
Verify start button is disabled when creating analysis. Verify no play button when state is past creating.
#2502

feat: disable analysis start button if not ready

---

.github/workflows/publish.yml

Currently we only publish to dockerhub on push to master or develop. Sometimes we create tags that aren't part of this flow.
Publishes images whenever there's a push to develop (which is tagged as `develop`, or if a release is published (tagged with the tag).
Post-merge, we should see the develop branch get published again. We should publish a temporary test release to verify it's also triggering the workflow and properly tags the image.

refactor(workflows): publish image on push to develop or release

---

.github/workflows/publish.yml

Publish fails when triggered by release
https://github.com/SEED-platform/seed/runs/1627398200?check_suite_focus=true#step:7:16
fixes bug where tag had `refs/tags` prefix when triggered by a release.

fix(workflows): fix release tag parsing for publish

---

seed/analysis_pipelines/bsyncr.py
seed/analysis_pipelines/pipeline.py
seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/partials/analyses.html
seed/static/seed/partials/inventory_detail_analyses.html
seed/tests/test_analysis_pipelines.py
seed/views/v3/analyses.py

Adds method for stopping a pipeline, and the analysis endpoint for triggering this stop.
Note that the implementation does **not** stop a running celery task, but prevents future tasks from running (assuming multiple tasks were chained for the pipeline and there are tasks remaining after it was stopped) - see the new `check_analysis_status` decorator used. When `stop` is called, it sets the status to `Stopped`, "ending" the analysis.
The biggest implication of the implementation is that the background task might still update the analysis/analysis property views even after it's been stopped.
This assumes you have bsyncr server setup.
Tweak bsyncr.py to take a long time after starting the analysis. e.g. on line 324 insert
```python
import time
time.sleep(30)
```
create an analysis for a …

#2478 feat: stop analysis

---

seed/analysis_pipelines/bsyncr.py
seed/analysis_pipelines/pipeline.py
seed/models/analysis_messages.py
seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/partials/analyses.html
seed/static/seed/partials/inventory_detail_analyses.html
seed/tests/test_analysis_pipelines.py
seed/views/v3/analyses.py

SEED is adding ability to run analyses on properties.
- refactor bsyncr celery tasks (and task wrapper) to more gracefully handle unexpected issues (e.g. someone deleting the analysis). In addition, avoid as much as possible raising unhandled exceptions that are unnecessary
- add a view for deleting an analysis
- add icon for deleting analysis from the frontend
- fix cases where user message or debug message for AnalysisMessage is too long by truncating the message
Monkey test the analysis functionality, deleting analyses in different statuses and see if you can break anything. After deleting an analysis you should no longer see it.
#2476

2476 feat: delete analysis view

---

seed/static/seed/partials/analyses.html
seed/static/seed/partials/analysis_details.html
seed/static/seed/partials/inventory_detail_analyses.html
seed/views/v3/analyses.py

We are demoing the analysis functionality soon and would like to make some tweaks on the SEED side.
I would consider this a temporary method of displaying the configuration of an analysis, purely for the demo. We will probably want to find a better way to display the json config down the road.
- returns analyses from the list endpoint ordered by _reverse_ id (ie newest comes first)
- add the analysis configuration json to the tables that show analysis info
- check all views of analyses to verify configuration is properly being displayed (analysis detail, analyses (org level list), inventory detail analysis list)

feat: misc analysis tweaks

---

config/settings/common.py

See related issue
https://www.django-rest-framework.org/api-guide/renderers/#setting-the-renderers
Removes the DRF `BrowsableAPIRenderer`, leaving only `JSONRenderer`
While logged out browse to `/api/version`.  Ensure that json is returned rather than html
#2558

fix: ensure drf always returns json

---

seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/services/uploader_service.js
seed/static/seed/partials/data_upload_modal.html

When users are importing/mapping large files some users think SEED is broken b/c we aren't updating the progress bar.
Adds a note to the geocoding/mapping progress bar which will appear to users if the progress hasn't been updated recently.
Import a large file (or add a long time.sleep in seed.data_importer.match.match_and_link_incoming_properties_and_taxlots). and when mapping (which should take a while) you should eventually (after 1 minute of starting the matching task) see the notice shown in the screenshot below.
This is a bandaid for #2515 , doesn't fix it as well as we might want but is a nice thing to have for now.

#2515 feat: track updates to progress data on frontend

---

seed/static/seed/js/controllers/export_inventory_modal_controller.js
seed/static/seed/partials/export_inventory_modal.html
seed/views/v3/tax_lot_properties.py

The property_notes field was large enough to break Microsoft Excel's cell character limit, causing overflow that would prevent the remaining data from being displayed correctly.
Adds an option to exclude property notes when exporting.
See the original ticket.
https://github.com/SEED-platform/seed/issues/2519
<hr>

feat: add option to exclude notes when exporting properties

---

seed/static/seed/js/controllers/cycle_admin_controller.js
seed/static/seed/js/controllers/delete_cycle_modal_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/cycle_service.js
seed/static/seed/js/services/inventory_service.js
seed/static/seed/partials/cycle_admin.html
seed/static/seed/partials/delete_cycle_modal.html
seed/templates/seed/_scripts.html

Users cannot delete cycles from the frontend
Adds ability to delete cycles from the frontend.
Create cycles with and without properties/taxlots. Navigate to the org cycles page, try to delete each cycle. You should be shown buttons to view the properties or taxlots depending on what's in the cycle. If you delete all properties and taxlots you should be allowed to delete the cycle.
#1113 
Note that it now says "Delete Cycle?" instead of "Delete User?" but I haven't updated the screenshots.

feat: add ui for deleting cycles

---

.github/workflows/publish.yml

SEED currently publishes to dockerhub on pushes to develop and publishing releases.
Publishes to dockerhub on tag push (ie no release needed) and manual triggering.
Once merged, try to push a tag and manually trigger the build. Verify it was built and tagged properly for dockerhub

build: allow manual publish and publish on tag push

---

seed/static/seed/js/controllers/inventory_list_controller.js

Adds the combined filter for the affected columns
Check that `eui` and `area` columns can filter for empty (`""`) and non-empty (`!""`) records
#2574

fix: add combinedFilter for eui and area columns

---

seed/models/tax_lot_properties.py

Uses the PropertyView/TaxlotView ID instead of the TaxLotProperty join ID
1. Add a note to child rows in both the property and taxlot tabs
2. Refresh the inventory list view and check that the note counts on child rows are correct
#2577

fix: use the correct id for related note count lookups

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/scss/style.scss

Adds the ability to click the header cell for the notes count (or shift-click to sort by multiple columns)
1. Check that the `notes_count` column now has a visible sort icon by default
2. Check that sorting (and prioritized shift-click sorting works as expected)
3. Check that sort is maintained between page refreshes
#2509 
Translucent by default:
Sorted:
Prioritized sort:

feat: add sorting for the inventory list notes count

---

seed/building_sync/tests/test_validation_client.py
seed/building_sync/validation_client.py

https://lgtm.com/projects/g/SEED-platform/seed/snapshot/4137da45f19ece8d98493897fbb54839dade5de1/files/seed/building_sync/validation_client.py?sort=name&dir=ASC&mode=heatmap#L65
Previously the buildingsync validation client was not raising some exceptions it created. This fixes that.

fix(building_sync): raise created exceptions

---

seed/views/v3/uploads.py

SEED has a check to determine if an Excel file is empty when uploading
Fixes issue where it would reject meter spreadsheets that have an empty first sheet (supposedly allowed according to example files).
Upload `seed/seed/data_importer/tests/data/example-pm-monthly-meter-usage.xlsx` and it should work (has an empty first sheet). Upload a spreadsheet where all sheets are empty and it should fail.
#2634

fix: allow pm meter xlsx to have empty first sheet

---

seed/building_sync/mappings.py
seed/models/building_file.py

Also correctly parse "auc:Recommended" for measure
We weren't properly getting all linked measures for scenarios (bad xpath). Also our check for "recommended" was bad for measures.
Fixes bsync import
Import [this file](https://gist.github.com/macintoshpie/4ffe5e66d43aba9e4735b048dcb8c567) (an tweaked version of buildingsync_ex01_measures.xml -- added extra measures to one of the scenarios and set recommended = false for one measure). Just use the default bsync column mapping.
Verify that:
- the measure "Retrofit with light emitting diode technologies" has recommended == false and all other measures have recommended == true
- the scenario "LED Only" points to 3 different measures
#2666

fix(building_sync): get all linked measures for scenario

---

seed/views/v3/organizations.py
seed/views/v3/properties.py

Org users with "viewer" role could not view the inventory list page
Allows org viewers to view inventory list by tweaking some API permission requirements
Create a viewer role, log in, try to view inventory list page.
#2669

#2669 fix(authz): let viewers view inventory list page

---

seed/api/v3/urls.py
seed/serializers/derived_columns.py
seed/static/seed/js/controllers/derived_columns_admin_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/derived_columns_service.js
seed/static/seed/partials/accounts.html
seed/static/seed/partials/accounts_nav.html
seed/static/seed/partials/derived_columns_admin.html
seed/templates/seed/_scripts.html
seed/views/v3/derived_columns.py

Seed is adding ability for users to define columns derived from other columns
Adds a list API endpoint and an initial iteration of displaying them on the Frontend
Create some derived columns then browse the page. Note the edit/delete buttons do not work yet.
You can create some derived col data by running this command (note you should update the `organization_id` variable if your's isn't `1`)
```bash
python manage.py shell <<-'EOF'
"""
Creates derived columns (but does not create DerivedColumnParameters)
"""
from random import randint
from seed.models import *
BASE_NAME = 'Fancy Column'
organization_id = 1
expressions = [
'$a + $b + $c',
'$a / $b * 100',
'$a * 3.14 + 123 % 100',
'($a - $b) / ($c + $d)',
]
for i in range(10):
dc = DerivedColumn.objects.create(
name=f'{BASE_NAME} …
```

feat: add derived columns list view

---

charts/seed/templates/web-celery-deployment.yaml

SEED is using post-office for some email services which sends emails in celery. For K8s deployments this means the celery container needs email credentials
- update web-celery-deployment to include AWS SES email creds
None needed
#2728

build(helm): pass SES aws creds to celery deployment

---

seed/static/seed/partials/analysis_run.html
seed/static/seed/partials/analysis_runs.html
seed/static/seed/scss/style.scss

Renders any HTML analysis output files in an iframe.
Run a BETTER analysis on a property with sufficient meter data, then view the analysis details.
https://github.com/SEED-platform/seed/issues/2759

feat: rendering HTML output files in an iframe

---

.github/workflows/ci.yml

We pinned the chrome version for testing previously. Now apt is complaining b/c when we try to install the package it would downgrade chrome.
Install latest stable chrome, then parse that version out to install the webdriver
NA

chore: always use latest chrome in CI

---

seed/building_sync/building_sync.py

Skips the import of buildingsync energy_uses that don't have a type.
See ticket.
https://github.com/SEED-platform/seed/issues/2696

fix: skipping resource_uses with no type

---

seed/building_sync/building_sync.py
seed/building_sync/mappings.py
seed/models/building_file.py

SEED is improving integration with AT
- skip meters which are missing readings
- skip meter readings missing start, end, or reading value
- warn users after import about skipping these things
Try to upload the following file, you'll get a warning that it skipped some meters. This is b/c some aucResourceUses don't include TimeSeriesData, or it does but the TimeSeries readings are missing actual reading values e.g.
After importing the file, go to meters tab and verify there are no completely empty meters columns.
[buildings_xml_report (12) (1).xml.zip](https://github.com/SEED-platform/seed/files/6976957/buildings_xml_report.12.1.xml.zip)
#2814 
Also #2743 
Full warning text:
```json
Warning(s)/Error(s) occurred while processing the file(s):
{
"buildings_xml_report (12) (1).xml": { …
```

2814 refactor: improved handling of BSync skipped meters

---

seed/analysis_pipelines/better/buildingsync.py
seed/analysis_pipelines/better/client.py
seed/analysis_pipelines/better/helpers.py

SEED is improving BETTER integration
- only pass meters and readings with 12 readings of values >= 1.0
- dont fail pipeline if one building fails to be created in BETTER
Import the CSV of PM data and meters (shared by Nick, ask me for access if you need it). Select all buildings and run the analysis. The analysis should skip some buildings b/c of two issues with these properties:
- they have meters with readings of 0.0 (you should see an explicit message about this next to the property)
- they have a location which BETTER fails to geocode (SEED doesn't know when this happens though, we just treat it as an unexpected error and continue)
The analysis should complete, and you should be able to view both the portfolio and building reports

fix: handle additional edge cases for BETTER analysis

---

seed/static/seed/js/controllers/analysis_run_controller.js

UI/UX tweaks for analysis
adds the has_children helper function to the run controller.  
view single analysis runs. 
#2818

fix: add helper has child function to the run controller

---

seed/static/seed/js/controllers/inventory_list_controller.js

- updating the column list profile was broken on the inventory page when dragging/dropping column headers. This fixes that by properly filtering columns before POSTing
- go to inventory list page
- drag and drop one of the columns (should successfully update the column profile)
- go to column list profile page and verify it was updated
- go back to list profile and it should be correct according to your updated ordering
#2790

fix: correctly filter columns when updating column profile

---

seed/analysis_pipelines/better/buildingsync.py
seed/models/building_file.py

Building file meters are linked to scenarios but not canonical properties currently
Links building file meters to canonical properties.

refactor!: link building file meters to property

---

seed/analysis_pipelines/better/client.py

BETTER HTML reports have unitted values. Previously those defaulted to SI, but an update to BETTER allows the API user to specify what they want
- request IP units from BETTER for standalone html reports
NOTE: future work would be to look at the seed org settings and request the units according to their settings.
Run a better analysis, the report should use IP units.
#2835

refactor(better): use IP units in standalone HTML report

---

.github/workflows/ci.yml

Only run CI workflow when:
- someone pushes to main or develop (ie merge into main or develop)
- any pull request
#2858

refactor: dont run CI on arbitrary pushes

---

seed/analysis_pipelines/better/pipeline.py
seed/analysis_pipelines/bsyncr.py
seed/analysis_pipelines/eui.py
seed/analysis_pipelines/pipeline.py
seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/js/controllers/analysis_details_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/partials/analyses.html
seed/static/seed/partials/analysis.html
seed/static/seed/partials/analysis_card.html
seed/static/seed/partials/analysis_details.html
seed/static/seed/partials/analysis_run.html
seed/static/seed/partials/analysis_runs.html
seed/static/seed/partials/inventory_detail.html
seed/static/seed/partials/inventory_detail_analyses.html
seed/templates/seed/_scripts.html
seed/views/v3/analyses.py

TLDR: for any page showing an analysis in a list or detailed view, SEED will now begin polling its status for updates so that it knows when to refresh it. This involved updating how progress data are created/tracked in the analysis pipelines.
SPECIFICALLY:
- add a method the the analyses_service which will continuously poll the status of an analysis until it determines theres no more progress data to track (`analyses_service.check_progress_loop(...)`)
- use method above in all views that render analyses so that they're refreshed when the status of the analysis changes
- part of accomplishing the above was adding a new endpoint `/analyses/<analysis id>/progress_key/` which returns the current `ProgressData` key (or null if there's no current `ProgressData` for the analysis).
- This …

feat(analyses): auto-poll analysis progress on frontend

---

config/settings/dev.py

Media is often served by NGINX, however in dev mode the path was not found.
Add in the media path to `dev.py`. Path points to the users local `media` folder.
Run a BETTER analysis locally (not in docker) with the dev settings
N/A

add explicit media path for dev users

---

seed/analysis_pipelines/better/helpers.py
seed/analysis_pipelines/utils.py
seed/models/analyses.py

SEED has analysis cards with highlights on some pages. The highlights of the cards were always the same and showed the most recent results.
- fixes issue of different analyses showing the same highlights.
- this was fixed by pulling analysis results from the AnalysisPropertyView's parsed results instead of the PropertyView's PropertyState. PropertyState will always be updated with the most recent results, so pulling info from there will always get you the most recent data.
- added some formatting to the cards to show `N/A` for some highlights
Run an analysis twice for a property that should get different results (e.g. run one then edit gross floor area then run again). Verify the cards show different values.
#2873

fix: get analysis highlights from analysis results

---

seed/static/seed/js/controllers/inventory_list_controller.js

SEED displays selected labels in the inventory list as a collapsable column
- fixes issue where initially loading the inventory list page with few columns (ie col profile with few columns) resulted in a really wide label column (see linked issue)
- add some labels to properties, make sure the labels are "show in list"
- update your col profile to only include a few columns
- load the inventory list page
#2748

fix: initialize label column width

---

seed/migrations/0151_seeduser_20210923_1337.py
seed/tests/test_analysis_pipelines.py

Django 3.1 broke the usage of "json" type, which SEED had historically used before Django added it.
See how we fixed this for extra_data: https://github.com/SEED-platform/seed/pull/2407#pullrequestreview-496042761
See more info about 3.1's issue: https://code.djangoproject.com/ticket/31973?cversion=0&cnum_hist=4#comment:4
This should fix the issue we saw in Sentry when we rolled the Django 3.2 instance on dev1 (#2900 )
- converts the SEEDUser json fields to `jsonb` type in the postgres database
- ⚠️  This PR disables a test due to an issue fetching the gbXML schema (see logs [here](https://github.com/SEED-platform/seed/pull/2901/checks?check_run_id=3695819939) or snippet [here](https://gist.github.com/macintoshpie/beca55b7ba9e23597292c0c47083548b)). I'm not sure why this just started …

fix: alter seeduser json columns to jsonb type

---

seed/static/seed/partials/accounts_nav.html

- Derived columns tab was commented out on the org page -- this fixes that
Go to org page, you should see the derived columns tab

fix: uncomment derived columns org tab

---

charts/seed/templates/web-deployment.yaml

Kubernetes deployment env var values must be strings, but yaml treats `TRUE` as a boolean. This was causing errors when trying to run the `kubectl apply -f` command
Fixes that
N/A

build: env vars for k8s must be strings

---

.github/workflows/stale.yml

SEED is using a stalebot for closing old issues. The stalebot is configured by default to do 30 "actions" per run (ie per day). This is slow to go through our issues, e.g. from a recent run:
```
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the operations-per-run (​https://github.com/actions/stale#operations-per-run​) option which is currently set to 30
```
Increase our actions per day to `500`. If we hit our rate limit then GH will just pause the GH actions ability to make requests for 1 hour, and I can bump it down tomorrow.
> GitHub has a rate limit and if reached will block these API calls for one hour (or API calls from other actions using the same user (a.k.a.: the …

refactor(ci): increase operations per run

---

seed/building_sync/building_sync.py
seed/building_sync/mappings.py
seed/building_sync/tests/data/example_SF_audit_report_BS_v2.3_081321.xml
seed/building_sync/tests/test_buildingsync.py
seed/models/building_file.py

- tweaks the import of scenarios from Audit Template so that we skip scenarios that don't have meters or measures. Note that this does _not_ apply to non-AT files!
- start importing TemporalStatus from BuildingSync scenarios
Import the example SF AT file here: https://buildingenergyscore.energy.gov/documents/example_SF_audit_report_BS_v2.3_081321.xml
You should only see it import the 4 "valid" scenarios which are:
- lighting package of measures
- HVAC package of measures
- electricity meter data
- fuel oil "meter" data
#2961 
Closes #2830

refactor: only import AT scenarios with measures or meters

---

seed/static/seed/js/controllers/data_upload_modal_controller.js

The process for importing new Data Files from the Data Set List view kicks off a sequence of events to ensure the correct data is imported. The majority of information is presented via a modal overlayed above a relevant page. After the Data File has been imported and matched the background page remains on the Data Mapping screen. This is confusing as a user might be inclined to re-save their mappings. It would be preferable to have the Data Set List as the background page after the Data File has been mapped. 
Upon completion of the data mapping, the Data Set List view will be set as the background page allowing the user to add more files. A user has the option to view properties by clicking 'View my properties' or import meters from the same file.
Add a new Data File to a Data Set and …

refactor: navigate to data set list view after saved mapping

---

seed/static/seed/partials/inventory_nav.html

We decided to hide the "Summary" tab until we get the chance to polish it a bit more.
- hide the "summary" tab (keep everything else though)
- load the properties page, should see no "Summary" tab

refactor: disable the summary tab

---

seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/seed.js

see ticket
fixes taxlot inventory detail link
click on a taxlot's info icon in the inventory list
https://github.com/SEED-platform/seed/issues/3001

fix: load taxlot instead of property for analyses

---

docker/backup_k8s/Dockerfile
docker/backup_k8s/backup_database.sh

Filenames sent to slack where in the form of `s3://<bucket>/<date>//<path-to-file-on-backup-pod>` and need to be `s3://<bucket>/<date>/<filename>`.
Fixes filename using `basename` base method.
Look at slack messages for new format.
#2971 <-- this is an old ticket, but still valid.

Fix k8s backup filename

---

config/urls.py
requirements/base.txt
seed/api/base/urls.py
seed/api/v1/urls.py
seed/api/v2/urls.py
seed/api/v2_1/urls.py
seed/api/v3/urls.py
seed/docs/urls.py
seed/landing/urls.py
seed/urls.py

done in tandem with [jwt-oauth2 #1](https://github.com/macintoshpie/jwt-oauth2/pull/1), which replaces deprecated functions in a dependencies
Replace deprecated function django.urls.url
```
python -Wd manage.py test
```
has no  warning for this function, in contrast to the same command on master.
#2891

Replace deprecated function django.urls.url

---

seed/static/seed/js/controllers/menu_controller.js
seed/static/seed/scss/style.scss
seed/templates/seed/_header.html

See issue #3050
- This PR updates the function and appearance of the `_header` navigation buttons. 
- The `+` button will now direct users to the organization settings of the current organization based on their authorization role 
- The current organization has been reformatted to show the current (selected) organization
- When the user hovers over an organization in the drop-down the organization id will appear above the mouse
- From any page, use the `+` button to navigate to the organization's various settings. Ensure it is the correct organization (check URL for organization id) 
- with an Admin account (role_level = 20) see all child organizations
- with a nonauthorized user check the available settings and organizations. If they do not have permission (role_level = 0) the `+` button …

3052 refactor/top right nav update

---

seed/static/seed/js/controllers/inventory_list_beta_controller.js

SEED is creating a paginated version of the inventory list
- fixes bug where the inventory was being fetched multiple times on page load. TLDR there's an issue where loading ui-grid settings it triggers our filter/sort event handlers when we don't want it to.
- test loading the beta inventory page with filters applied, then go to a different page, then go back. The network tab in dev tools should only show a single fetch to `/filter`
#3071

refactor: avoid multiple calls to load inventory

---

seed/utils/filter_state.py
seed/views/v3/properties.py
seed/views/v3/taxlots.py

When viewing the property or taxlot inventory a user may filter by column contents. The backend code to filter properties or taxlots is identical and duplicated across two functions. 
This PR moves the functionality to a single helper function that can be imported to both property and taxlot files. There are slight differences between the two and a new argument `state_type` has been introduced to differentiate between 'property' and 'taxlot' filtering. 
Filter the inventory for both properties and taxlots and ensure correct functionality.
#3081 
n/a

3081 refactor/util property taxlot fiter

---

docker-compose.dev.yml
docker-compose.local.yml
docker-compose.yml

We fixed this in helm, but missed doing it in these files. For unknown reasons, the `pgdata` field needs to be passed to the containers now. The postgres base image may have changed.
* update the docker-compose files by adding in the `pgdata` env var.
* create required docker volumes (seed_pgdata, seed_media)
* docker-compose up 
* verify that the database authorization works and that you can log into the site
n/a

Update docker's pgdata path

---

seed/static/seed/js/services/inventory_service.js
seed/tests/test_views.py
seed/utils/filter_state.py
seed/utils/inventory_filter.py
seed/views/v3/properties.py
seed/views/v3/taxlots.py

With paginated inventory lists, it's not critical to return the entire column data when selecting properties or taxlots that are not on page 1.
Based on a query parameter `?ids_only=true`, the backend will return a json list of property or taxlot ids. If this query param is not passed the function will default to the existing functionality allowing backward compatibility. This should improve performance when applying filters to the entire inventory.
- Run new test /seed/tests/test_views.py:InventoryViewTests.test_get_properties_select_all. 
- Can be tested when the front end "select all" features are implemented.
#3093

3093 refactor/inventory filter ids only

---

docker-compose.local.yml
docker-compose.yml

We added PGDATA to docker compose b/c that's what we're doing in our k8s deployment. But that's not necessary for our local docker-compose, and prevents us from creating new (i.e. empty) volumes and using them with the postgres container.
The changes originally occurred in #3101 
- removes PGDATA from docker-compose files
- spin it up locally with an existing DB, also try creating a new empty volume and using that for the postgres volume

fix(docker): use default PGDATA for postgres

---

docker/backup_k8s/backup_database.sh
docker/backup_k8s/tar_backup_database.sh

This PR modifies the pgdata directory backup process to be 1:1 with a running instance of seed
Some of the issues with the initial process:
- In the original backup there were two users in the db (postgres & seeduser) instead of just seeduser, and all roles were incorrectly assigned to postgres
- Some tables were owned by postgres
- Timescale pre/post restore steps were missing
- pgdata was nested
- pg_hba.conf restricted nearly all access to the instance
Additions:
- Adds xz ultra compression (16.1 GB -> 2.8 GB per backup)
1. Run the backup process
2. Download and extract the new backup: `tar -xf backup.tar.xz --strip-components 3`
3. Launch a container using that directory as a shared volume: `docker run --name=seed -p 5432:5432 -v /my/extracted/dir/data:/var/lib/postgresql/data …

Changes to the pgdata backup process

---

docker/backup_k8s/tar_backup_database.sh

Fix the tar backup of database. Needed to make sure that the scratch volume had no prior dumps.

cleanup scratch dir before starting restore

---

seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/controllers/dataset_list_controller.js
seed/static/seed/partials/dataset_detail.html
seed/views/v3/import_files.py

If a property file with meter data is imported, SEED generates two different import records. One for the property import, and one for the meter data import. The "# of records" listed in the view indicates the number of properties that were in the imported file. This works fine for the property import, but the meter data import returns 0 for "# of records". 
ImportFiles are SEED models representing a property file that has been imported. SEED reuses this model for meter imports for display purposes but most of the model fields are left blank. The model column `num_rows` is used to populate "# of records". This field was left as None during the meter import.
Attaches the rows of the proposed meter import file to the `ImportFile.num_rows` property, and updates any conditionals to prevent …

3128 feat/dataset feedback number of meters

---

seed/static/seed/js/controllers/data_upload_modal_controller.js
seed/static/seed/js/controllers/green_button_upload_modal_controller.js
seed/static/seed/partials/data_upload_modal.html
seed/static/seed/partials/green_button_upload_modal.html
seed/static/seed/scss/style.scss

After importing meters from a property file there is a display describing which meters and their properties were imported. There is no indicator showing how many meters or properties containing meters were imported. This same flow is repeated for the GreenButton upload.
Adds property and meter counts to the data upload modal during the meter import and GreenButton upload steps.
Test Property Upload:
- Import a Property file with meter data. Following the property import click "Import Meters from the same file". Note this may take several seconds to appear, and several seconds to prompt the next modal screen.
- Ensure there are proposed counts for meter counts and unlinkable properties. 
- Click confirm 
- Ensure there is an imported meter count.
Test file: …

3127 feat/meter import count

---

seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/partials/inventory_detail.html

See ticket
Makes popovers on the inventory detail page only show one at a time, and scrolling will clear them.
Load any detail view, click on a field, click on another field, scroll the page.
https://github.com/SEED-platform/seed/issues/2508
see ticket

fix: popovers now open one at a time and disappear with scrolling

---

seed/static/seed/partials/organization_settings.html
seed/views/v3/organizations.py

On development, or any custom configured `BETTER_HOST` the URL link would always go to production.
* Adds BETTER_HOST to the org API
* Point to the documentation based on the host URL and display it in the text.
Load settings page for an org and look at the BETTER key section.
n/a

Update display of BETTER host configuration

---

seed/static/seed/js/controllers/inventory_list_beta_controller.js

The beta inventory filters stopped working.
Fixes the beta inventory filters:  there was a function call that was no longer needed as loading the labels happens on init instead of on loading the inventory.
Use the beta inventory page and filter the list down.
---
---

fix: removed unused function call

---

seed/static/seed/js/controllers/inventory_cycles_controller.js
seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_detail_cycles_controller.js
seed/static/seed/js/controllers/inventory_list_beta_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/mapping_controller.js

See ticket.
Checks for field type 'number' as well when rounding a display value.
Check the list view to ensure all extra_data numbers are being rounded as per the organization setting.
https://github.com/SEED-platform/seed/issues/3146

fix: fields marked 'number' also get rounded

---

requirements/base.txt

Update lxml to 4.7.1 to match the BAE dependency

update lxml to 4.7.1

---

Dockerfile
Dockerfile-dev

Recent versions of git no longer allow users to interact with local git repos when the file owner permissions differ from the current user.
Updates the system-wide git config for all users (`/etc/gitconfig`) to mark `/seed` as a safe directory, so that the `uwsgi` user can query the current git revision despite the files being owned by `root`.
1. Run `docker-compose up -d`
2. Check that the About page loads the git sha correctly, instead of returning a 500 error.

Mark /seed as safe

---

seed/static/seed/js/controllers/inventory_list_beta_controller.js
seed/static/seed/partials/inventory_list_beta.html

The "Refresh Metadata" action was only added to the inventory list actions.
Adds "Refresh Metadata" action to inventory beta list actions.
To test user experience: 
inventory > select a number of properties > actions > refresh metadata > refresh_metadata > watch progress bar go to 100 and modal will close 
To check actual property values 'updated' attribute (more involved):
```
docker exec -it seed_web /bin/bash
python manage.py shell
from seed.models import PropertyState
PropertyState.objects.get(pm_property_id=<PM Property ID of your choice>).propertyview_set.first().property.updated 
>>> old time 
```
inventory > select property with same PM Property ID > actions > refresh metadata ...
... back to shell 
```
PropertyState.objects.get(pm_property_id=<Same PM Property …
```

3228 feat/refresh metadata inventory beta

---

seed/analysis_pipelines/co2.py
seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
seed/static/seed/partials/inventory_detail_analyses_modal.html

see ticket
adds a checkbox when making a CO2 analysis to enable saving results to the property
- run a CO2 analysis without the option checked and verify no value is saved to the property state
- run another with the option checked and see the value
https://github.com/SEED-platform/seed/issues/3175

feat: added an option for saving data

---

seed/models/columns.py
seed/models/properties.py
seed/models/tax_lots.py

Looks like the coparent method was missing the new GHG fields.
* Adds the new GHG canonical fields to the coparent method call which is used in the views. 
* removes the term master record in coparent methods
Unit tests should suffice
#3174

Add GHG fields to coparent call

---

.gitignore
docs/environment.yml
docs/source/developer_resources.rst
readthedocs.yml

read the docs isn't building (and hasn't ever ???) built the documentation correctly. Instead of trying to fix read the docs, maybe we should just put the code documentation on the seed website.
* remove read the docs related files
* add instructions to release on building documentation
* try building the documentation per the instructions.
#3275

update release notes and remove rtd related files

---

requirements/base.txt

Some BuildingSync files were not importing correctly...giving a "Failed parsing BuildingSync Data 'Conditioned'". This PR fixes that with an updated BAE (v0.1.8)

fix checking for section floor areas in BAE

---

seed/management/commands/create_test_user_json.py

Current format of the `create_test_user_json` managed task is 
```
{
"name": "seed_api_test",
"host": "http://127.0.0.1:8000",
"username":  "user@seed-platform.org",
"api_key": "<mykey>"
}
```
However, this doesn't easily work for py-seed because it requires the host to be broken up into `port` and `use_ssl`
* Adds a --pyseed arg to the create_test_user_json to save as
```
{
"name": "seed_api_test",
"base_url": "http://127.0.0.1",
"username": "user@seed-platform.org",
"api_key": "<mykey>",
"port": 8000,
"use_ssl": false
}
```
* Run `./manage.py create_test_user_json --username user@seed-platform.org --host http://localhost:8080 --file api_test_user.json --pyseed`
#3316

allow generation of credential json for pyseed format

---

.github/workflows/ci.yml
.github/workflows/publish.yml
docker-compose.dev.yml
docker/start_celery_docker.sh

See ticket
* creates two tags on version releases
* update text on celery log
This is difficult to test. I recommend that we merge, then create a pre-release of the next version. A prerelease (for better or worse) will also be tagged with latest. 
After a new GitHub tag is created, verify (after some time) that docker hub has an updated version release and latest release.
#3318 
n/a

tag docker hub images with latest and version on release

---

requirements/base.txt

Update lxml to 4.9.1
BAE also has a lxml dependency which creates mismatches.
Removing the separate lxml dependency in favor of the one within BAE

updating bae version and removing separate lxml dependency

---

seed/models/analysis_property_views.py
seed/static/seed/js/services/analyses_service.js
seed/views/v3/analyses.py

The first commit speeds up the db queries and serialization of the "views" returned by `/api/v3/analyses/` by about 50%
The second makes returning the views optional, as they aren't used. That speed things up _a lot_
1. Create analysis ([as described here](https://github.com/SEED-platform/seed/issues/3343#issue-1296292747)) 
2. Go to property detail page. 
3. Say "wow, so fast."
https://github.com/SEED-platform/seed/issues/3343

Speed up list analysis

---

seed/static/seed/js/controllers/data_quality_labels_modal_controller.js
seed/static/seed/js/controllers/update_item_labels_modal_controller.js
seed/static/seed/partials/data_quality_labels_modal.html
seed/static/seed/partials/label_admin.html
seed/static/seed/partials/update_item_labels_modal.html

It would be convenient if a user could select if a label was to be shown in list while creating a new label
adds a "Show in List" checkbox to all create label forms 
- Label Admin 
- Data Quality Label "+" Modal
- Inventory/Beta/Detail Action Modal
Select a number of properties and add labels through the actions tab with "Show in List". Labels should be shown. 
https://user-images.githubusercontent.com/58446472/178305514-6ac40752-5a0d-4fe1-b6f1-18d46d20f113.mov
#3291
Label Admin
Data Quality Label "+" Modal
Inventory/Beta/Detail Action modal

3291 add show in list to label creation

---

seed/analysis_pipelines/co2.py

CO2 Analysis report was missing "Total GHG Emissions Intensity"
Adds "Total GHG Emissions Intensity" to CO2 Analysis report
Upload a building file and its meters (ex: ESPM_JCC_Custom_Download_BETTERTest.xlsx). Then go to any property detail and change eGRID Subregion Code to "AZNM" and run a CO2 analysis
- "Total GHG Emissions Intensity" should be displayed in the analysis report
#3300

add total ghg emission intensity to report view

---

config/settings/common.py
seed/tasks.py

- We (OPEN) have been using SEED in Docker on our dev machines, where we don't have an HTTPS proxy set up.
- In these environments, we want generated links back to the SEED application to show with HTTP, not HTTPS.
- Makes the protocol configurable via an optional environment variable called `PROTOCOL`. When this isn't provided, the default value of `'https'` is used.
- Alters how URLs back to the SEED application are generated for use in emails, particularly the "new user" emails and "added to new organization" emails. These now use the configured protocol (either HTTP or HTTPS).
1. Build a new Docker image using this branch.
2. Copy and paste one of the Docker Compose configuration files from this repository, and set the PROTOCOL environment variable to `'http'`.
3. Make sure to set the …

Allow using "http" in links to SEED within outbound emails

---

seed/static/seed/js/services/inventory_service.js

The new inventory list had a bug where batch deleting did not work for taxlots.
Allows batch deletes for taxlots.
Load taxlots, select all, delete.
https://github.com/SEED-platform/seed/issues/3394

fix: taxlots->selectall->delete now works

---

seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/inventory_list_legacy_controller.js

Evaluated derived columns could have up to 16 decimal points.
Applies the `organization.display_decimal_places` setting to derived columns on 
- inventory list 
- inventory list (legacy)
- inventory detail
_NOTE: it is possible to apply a unique decimal count to each derived column as an individual setting, but it will require further development_
- generate derived column that when evaluated will have more than 2 (organization setting) decimal places
- confirm there are only 2 decimals displayed on the inventory list/legacy/detail 
#3393
dc1 = extra column / 7 
dc2 = PM Property ID / 7
dc3 = dc2 / 7

apply org settings to derived col decimals

---

seed/static/seed/js/controllers/inventory_list_controller.js

See ticket
re-enables reelated data on the new inventory page
see ticket
https://github.com/SEED-platform/seed/issues/3390
https://github.com/SEED-platform/seed/issues/3395

fix: re-enabled related data on inventory list

---

config/settings/docker.py

- We (OPEN) would like to use our own email address for emails from SEED.
- The "From" address for "forgot password" emails wasn't configurable in the Docker image for SEED. (It was always set to "info@seed-platform.org".)
- In order to set this From address, we've made the `PASSWORD_RESET_EMAIL` take its value from the main `SERVER_EMAIL` environment variable, when running SEED in a Docker image.
1. Build a new Docker image using this branch.
2. Copy and paste one of the Docker Compose configuration files from this repository, and set the `SERVER_EMAIL` environment variable.
3. Make sure to set the `DJANGO_EMAIL_BACKEND` variable and other email-related environment variables so that you can send outbound email.
4. Run the Docker image with the configuration file.
5. Log in to SEED and …

Make "From" address in password-reset emails configurable when using Docker

---

seed/api/v3/urls.py
seed/views/main.py

Creates an API endpoint for superusers to see the number of active, reserved, and scheduled tasks.  This is helpful for understanding if the celery queue is at max concurrency, or just in use.  I opted for an API endpoint rather than a managed task.
Note: you may see a `AssertionError at /api/v3/celery_queue/` if celery isn't running, and sometimes nondeterministically (no idea why)
```json
{
"active": {
"total": 4,
"tasks": [
"seed.data_importer.tasks._save_raw_data_create_tasks",
"seed.data_importer.tasks._save_raw_data_chunk"
]
},
"reserved": {
"total": 0
},
"scheduled": {
"total": 0
},
"maxConcurrency": 4
}
```
As a superuser, fetch the `/api/v3/celery-queue` endpoint while celery task are running (or aren't)
#3315

Celery-queue API endpoint

---

seed/tests/test_media.py
seed/views/v3/media.py

- Adds directory handling for InventoryDocument media files, so that files that have been uploaded can be downloaded on a server running nginx
- Adds testing for retrieving an InventoryDocument file as an org member to test_media.py
When running SEED with nginx (like on a server), navigate to a property details page, upload a .pdf document, and then try downloading that document.
#3437

Added inventory documents to media view & tests

---

seed/models/properties.py

Simply cuts off the number of returned histories to 10.
Maybe we wanted this number to be a arg to the endpoint, or a envvar, or something the user can set in the UI. We can duke it out in the comments, I just wanted to get a fix fix out there.
Ultimately, this is a cheap fix for an expensive problem that we should confront in a real way at a later date.

Only return 10 history at max

---

seed/views/v3/column_list_profiles.py

see ticket
ensures the reesponse is a list beforee appending
attempt to load inventory when comstock is enabled
https://github.com/SEED-platform/seed/issues/3510

fix/make sure it's a list

---

seed/static/seed/js/controllers/column_mappings_controller.js
seed/static/seed/js/controllers/column_settings_controller.js
seed/static/seed/partials/column_mappings.html
seed/static/seed/partials/mapping.html

See ticket.
Adds GHG and GHG Intensity to column settings data types.
Try to set units on a GHG field and notice them appearing when mapping.
https://github.com/SEED-platform/seed/issues/2605
Set data type on settings:
See units on mapping:
GHG Units:
GHG Intensity Units:

feat: added GHG and GHG Intensity

---

seed/static/seed/js/controllers/program_setup_controller.js

Adds an error when trying to save a program metric when either the energy or emission metrics have a target column selected without an actual column.
Fixes #3571

Add error check for blank Actual Column in Program Setup

---

seed/static/seed/js/controllers/inventory_list_controller.js

lets say a have filter groups Office and Retail.
I select Retail and delete it.
As excepted, it deletes, now no filter group is selected.
I select Office. Nothing happens :open_mouth:
This fixes that

On FilterGroup delete, filter groups don't filter≈y

---

seed/static/seed/partials/inventory_list.html

When a user add a label it doesn't automatically filter the inventory list
Update the ng- model to be `on-tag-added` and `on-tag-removed`
See ticket
#3616

Fix update labels and label selected

---

seed/static/seed/js/controllers/column_mappings_controller.js
seed/static/seed/js/services/column_mappings_service.js
seed/static/seed/partials/column_mappings.html
seed/static/seed/scss/style.scss
seed/tests/data/bps/README.md
seed/views/v3/column_mapping_profiles.py

The py-seed has a format that is used to create a column mapping profile via a CSV. See #3610 for the links.
* Add API method for exporting column mapping profile to CSV
* Add button to column mapping profile page to export the data
* go to the column mapping page
* select one of the profiles
* click on the new lightgreen export button
* change some mappings, save the mappings
* export again
* verify that the files changed
#3610

Add export column mappings

---

seed/views/v3/portfolio_manager.py

non-empty arrays where parsed with `replace('"[{', '[{').replace('}]"', '}]')`, but not the empty ones. Thus, if `childrenRows` was empty, we'd try to iter through an empty array like it was a string, "[]".
Note, replacing `replace('"[{', '[{').replace('}]"', '}]')` with `replace('"[', '[').replace(']"', ']')` doesn't work, as `[` and `]` are uses in the data and it all gets messed up. 
#3593 [#3322](https://github.com/SEED-platform/seed/issues/3322)

Fix get template with no children

---

seed/serializers/notes.py
seed/tests/test_note_views.py
seed/views/notes.py

The Note's API returns both the `property_view_id` and `taxlot_view_id` even though only one of the two will be populated. 
Removed the `null` view id from the return by overloading the `to_representation` method
* create notes on a property and a taxlot
* monkey test the CRUD operations in the UI
* Also updated the API documentation
#3634 
Before:
After:

Fix note's API result to not include related model's view ID

---

seed/views/v3/meters.py

Swagger expects a quertyset to be returned 
* add `Meter.objects.none()` to the Meter `get_quertyset` method.
Does swagger load?
#3661

Fix swagger loading the Meter endpoints

---

seed/models/columns.py
seed/static/seed/js/controllers/inventory_list_controller.js
seed/utils/inventory_filter.py

- UI disables sorting and filtering on derived columns
- API ignores detrived columns in sorting and filtering. You could convince me it should 400 instead. 🤷  This felt right the the API ignore all other invalid column filters.
https://github.com/SEED-platform/seed/issues/3667

Disable sorting by derived column

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/stale.yml
requirements/base.txt

`develop` publish builds are failing.
The shapely dependency comes from pnnl-buildingid library which does not have any version constraints on shapely, thus it grabbed the latest shapely which was released on 12/12/2022.
```
pnnl-buildingid==2.0.0
- click [required: Any, installed: 8.1.3]
- click-log [required: Any, installed: 0.4.0]
- click [required: Any, installed: 8.1.3]
- shapely [required: Any, installed: 1.8.5.post1]
```
* force the use of 20.04 for most of the builds. This is not likely the issue, but now we will be explicit on what version of Ubuntu we are using.
* Force Shapely 1.8.5.post1 as 2.x version does not build the geos library correctly.
n/a
n/a

Fix build and publish scripts by pinning version of Shapely

---

seed/models/compliance_metrics.py

There was an issue with how the column_ids were created for the property_response in the compliance_metrics model.
It adds checks for whether actual energy, target energy, actual emission, and target emission values are present before adding them to column_ids.
Create a Program with only energy metric, only emission metric, and both metrics. Then make sure each of the three Programs will load on Program Overview and Property Insights pages.
Fixes #3697

Fix issue with evaluating compliance metric

---

seed/static/seed/js/controllers/insights_property_controller.js
seed/static/seed/js/controllers/program_setup_controller.js
seed/static/seed/js/seed.js
seed/static/seed/partials/accounts.html
seed/static/seed/partials/accounts_nav.html
seed/static/seed/partials/program_setup.html
seed/templates/seed/_header.html
seed/views/v3/compliance_metrics.py

Users with viewer role could make changes to programs even though this wasn't the intended behavior.
It changes the api back end and front end to only allow members and owners to create, edit, and delete programs. Viewers can view the Program Setup page but the forms are disabled (i.e. no changes are allowed). Additionally, the Program Overview and Property Insights pages still work for viewers.
Create an user with the viewer role and make sure that you can view but not edit programs on program setup page. Additionally, make sure that program overview and property insights pages still are visible.
Fixes #3691

Add the @has_perm_class permission to program metric api endpoints

---

seed/views/v3/column_mapping_profiles.py

The column mapping export data was being exported in order of IDs, which was reasonable; however, in orgs with lots of column mappings (~1,000) it appeared that all the data was not being exported. One of the reasons was that the view on the website did not match the view in the exported file.
* Sort (case insensitive) the column mappings before export
* In SF org (or any other org), go to column mappings
* Export and verify that the to_field is sorted alphabetically and consistent with the results in the SEED UI.
Further addresses #3610 
Here are the results of SF after sorting ... [2020-11-14 org-wide mapping snapshot_mapping_profile.csv](https://github.com/SEED-platform/seed/files/10415371/2020-11-14.org-wide.mapping.snapshot_mapping_profile.csv)

Sort column mappings in profile before export

---

.github/workflows/pr-labels.yml
.github/workflows/stale-ice-box.yml
.github/workflows/stale.yml

Developers only -- issues that are labeled icebox will be marked stale after 180 days.

Mark icebox-labeled issues as stale after 180 days

---

seed/data_importer/utils.py
seed/lib/superperms/orgs/models.py
seed/lib/superperms/orgs/permissions.py
seed/serializers/meter_readings.py
seed/tests/test_meter_views.py
seed/utils/meters.py
seed/views/v3/meter_readings.py

Meter readers only supported one-at-a-time style import.
* Add in a Bulk Meter Reading Create
* Should be tested in part of the Meter Viewset PR
* API only updates
N/A

Add bulk meter reading API for faster creation

---

seed/static/seed/js/controllers/create_column_modal_controller.js

@axelstudios this'll give us a actual error message, but is there a way to figure out what the error underneath is before this hits dev1? locally, I get no errors. 
[Column Settings: getting 520 error when making a new column but column is created#3780](https://github.com/SEED-platform/seed/issues/3780)

Catch create column error correctly

---

seed/static/seed/js/seed.js

the nav of the org pages needs `auth.owner_requried`, which not every controller had. Now it does.
go to the org page and click around. 
Organization: Not all links appear at the top on all screens #3808 
before:
after:

Show all navs in org

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/publish.yml
config/urls.py
seed/data_importer/match.py

SEED requires that a property state includes at least one audit log when completing a merge. SEED had code in the merging logic which simply called `assert` and for the first time that we know of, this assertion was called.
* add more information to the exception so that we can track down the state id's of the records that do not have audit logs
* move sentry-debug out of debug urls to allow for sentry testing.
n/a
n/a

Add more logging to the exception when a property state is missing an audit log

---

seed/views/v3/organizations.py

In a user's settings page, the list of meter units can be pretty long and as new meters are added, the order of the list needs to be sorted.
* sort the backend/django return of the org data's meter unit display 
* go to an org
* select setting -> units
* Look at the meter energy units drop down and make sure the values are sorted.
n/a
Before:
After:

Sort the dropdown of meter units

---

seed/static/seed/js/controllers/program_setup_controller.js
seed/static/seed/partials/program_setup.html

The Program Setup page in the organization settings used a heading of "Program Configuration" at the top of the page. Where as all of the other organization settings pages had the header consistent with the name of the page.
Revise Program Configuration to be Program Setup.
Load the Program Setup page and make sure that the header has been revised as indicated.
#3831

Change "Program Configuration" to "Program Setup"

---

seed/building_sync/building_sync.py
seed/building_sync/mappings.py
seed/building_sync/tests/test_buildingsync.py

upload a buildingsync file and see the new columns.
https://github.com/SEED-platform/seed/issues/3774

Get audit date and audit date type from buildingsync files

---

docker/nginx-seed.conf

In our Nginx config we have `add_header` directives at multiple levels, which is BAD - the directives are inherited from the previous level only if there are no `add_header` directives defined on the current level, so our higher level headers were being ignored
Moves all `add_header`s to the same level
Serve via Nginx, look for all headers

Fix Nginx Security

---

seed/static/seed/scss/style.scss

Fixes the top header so that the whitespace isn't clickable, inadvertently redirecting the user to the home page
Click the header area that doesn't include the logo

Fix clickable header

---

seed/static/seed/js/controllers/inventory_detail_meters_controller.js
seed/static/seed/partials/home.html
seed/static/seed/partials/inventory_detail_meters.html
seed/static/seed/scss/style.scss

Needed an easy way to export meter data. 
Simply adds the un grid export to the meter and meter readings tables. This supports the basic use case. It also allows us to export the monthly or yearly data without having to make an additional API call.
* import meter data (via building sync or espm)
* Go to a meter 
* Click on the hamburger on the top right of the meter and then on the meter_reading page
* Verify data exported correctly
#2946

Add export to meters and meter readings

---

seed/static/seed/js/controllers/organization_settings_controller.js
seed/static/seed/js/services/analyses_service.js
seed/static/seed/js/services/salesforce_config_service.js
seed/static/seed/js/services/salesforce_mapping_service.js

This PR fixes the ability to save BETTER tokens, Salesforce configs, and Salesforce mappings for a different organization than the currently active one.
Additionally, it fixes a bug with `sync_salesforce` where the `organization_id` was being passed in the POST body rather than the path params.
1. Go to the settings of an organization other than the active one in the top right corner
2. Attempt to verify a BETTER token
3. Attempt to save a Salesforce config and mappings
4. Check the database and confirm that the org ids match the correct org, and not the one in the top right corner
#3919
Related to #3916

Fix saving BETTER/Salesforce data for non-active orgs

---

seed/static/seed/partials/program_setup.html

I also double checked that all translations in this file have been added to Lokalise.

adding >= and <= to display

---

seed/static/seed/js/controllers/derived_columns_admin_controller.js
seed/static/seed/js/controllers/derived_columns_editor_controller.js
seed/static/seed/js/seed.js
seed/static/seed/partials/accounts_nav.html
seed/static/seed/partials/derived_columns_admin.html

Attempting to edit an already-saved column, without changing the name, always resulted in an error because _the name was already taken by itself_.
- Fixes updating an existing derived column when the name is unchanged
- Fixes `Derived Columns` active nav for all subpages
- Improves the `Create Derived Column` button to set the default type on the editor page based on whether it was clicked when viewing the Property or Tax Lot derived columns
- Improves the `Create`/`Save` button such that it takes you to the correct Property/Tax Lot derived column page on success
- Create a derived column, click Edit, then click Save.  It should now succeed
- Check that the `Derived Columns` nav shows as active while on any of the derived column pages
- Check that the `Create Derived Column` button …

Fix editing a derived column without changing the name

---

seed/utils/salesforce.py

Minor enhancement to include the property view ID in a salesforce error message for better troubleshooting.
@axelstudios, if you could get this fix onto dev1 when you have a chance that would be great and would help out users testing out the functionality. thanks!

add better error messaging that includes the property view ID

---

seed/static/seed/js/services/inventory_service.js

- Adds `organization_id` to the `update_salesforce` requests so that non-superusers can use the endpoint
- Fixes the POST body so to match the expected backend data structure
Use the `Update Salesforce` action from the inventory list and detail views

Fix Update-Salesforce requests

---

seed/static/seed/partials/home.html

Replaced getting started guide on front page for v2.18

replacing seed getting started guide for v2.18

---

seed/static/seed/js/services/filter_groups_service.js
seed/static/seed/js/services/inventory_service.js

Fixes a syntax bug preventing inventory_service.get_column_list_profile from working correctly.
It's used on the inventory list page when first loaded; without the fix, one of the GET requests will fail with a 301 error.

Fix column list profile GET request syntax

---

requirements/test.txt

Dependabot updated `requests`, and requests v2.30.0 added support for urllib3 v2.0.
> https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#attributeerror-module-urllib3-connectionpool-has-no-attribute-verifiedhttpsconnection
> https://github.com/kevin1024/vcrpy/issues/688
Pins urllib3 to v1 to fix the one CI test failure until vcrpy fixes their broken imports
CI success

Pin urllib3

---

docker/nginx/nginx.conf

1. Prevents automatically serving `/static/**/index.html` files
2. Treats every `/static/**` file, except for js/css/svg, as binary files
1. Browse to `/static/node_modules/angular-dragula/` and make sure the dragula readme page doesn't appear (403 error)
2. Browse to `/static/node_modules/angular-dragula/index.html` and make sure the file downloads rather than rendering and loading js files that we don't want executing
3. Monkey test, make sure the app itself still works as expected and that images load and such
#4039

Prevent Automatically Serving Static `index.html` Files

---

seed/lib/superperms/orgs/decorators.py
seed/management/commands/create_default_user.py
seed/static/seed/js/controllers/admin_controller.js
seed/views/v3/users.py

Fixes multiple bugs:
1. It was not possible to use the Admin `Create a user` form when also specifying a new organization to create
2. The same `Create a user` form failed to update the organization list after creating a new organization
3. The `create_default_user` script failed to add new users to the specified organization if it already existed, leaving the new user orphaned
1. Check that the `Create a user` form works as expected when specifying a new organization name, and then check the organization dropdown at the top right for the newly created org
2. Check that an organization owner (non-superuser) can still invite new members to their organization
3. Run `manage.py create_default_user`, specifying and existing organization name, and check that the new user was added to the …

Fix User Creation Bugs

---

seed/static/seed/js/controllers/inventory_reports_controller.js

Fix categorical data on reports scatter plot

---

seed/migrations/0200_rehash.py

The `0200_rehash` migration was failing due to memory pressure when migrating the production database with over 14E6 states. 
Convert the `.all()` call to `.all().iterator()` to prevent all records from returing at one time, rather force a database iterator.
This migration still takes *a long* time to run--around 10 hours. We might need to parallalize this in the future.
If CI passes, then there are no syntax errors. The PR does not change the core functionality.
n/a

Use iterator() when rehashing to save memory

---

.github/workflows/ci.yml

See #4151
Replaces `chrome-unstable` v117 with v114 explicitly, so that `google-chrome` and the selenium webdriver versions both exist and match
Check for CI to pass
#4153

Lock `google-chrome` to v114

---

docker/nginx/seed-csp.conf

Adds `https://*.tile.openstreetmap.org` and `https://better-lbnl-staging.herokuapp.com` to the allowed domains for loading images (to fix the map view)
Run the web container in production with nginx, then load a map view
#4168

Add Open Street Map to CSP rules

---

.cspell/custom-dictionary-workspace.txt
seed/tests/test_media.py

The `test_media.py` file mucks with the location of the MEDIA_ROOT. If there is a test that runs after this that write data to the MEDIA_ROOT, then it will still be pointing to the updated location (which is the `/tmp` dir). If the subsequent test needs to read out of MEDIA_ROOT it will fail due to the "file not in django working path" error.
After running the test, in the tearDown, set the MEDIA_ROOT back to the previous value.
CI only
N/A

Set the MEDIA_ROOT path back to original value during test

---

seed/serializers/analysis_property_views.py
seed/static/seed/js/controllers/analyses_controller.js
seed/static/seed/partials/analyses.html
seed/views/v3/analyses.py

Previously, `GET /api/v3/analyses/` returned a whole propertystate per `AnalysisPropertyViews` of which there are many. We did this the compute view display_name client side. now we compute that in the backend, greatly decreasing the amount of fetched and sent data. 
We were also querying for each `AnalysisPropertyViews`'s outputfiles one at a time. We are now prefetching them with the `AnalysisPropertyViews`
on a test db with 400 `AnalysisPropertyViews`, `GET /api/v3/analyses/` used to take ~4.5 secs and returns ~75 KB. It now returns < .4 secs and returns ~10KB.  I believe both of these performance gain will scale linearly with the number of `AnalysisPropertyViews`.

Optimize list analyses endpoint

---

seed/data_importer/tasks.py
seed/lib/xml_mapping/mapper.py
seed/views/v3/properties.py

The import process relies heavily on cascading delay/background tasks. To allow a full path through the existing background tasks in the foreground on a system that has celery enabled is complicated. 
* creates two new methods for saving raw data and mapping in the foreground. 
There is definitely some areas of improvement with the entire Celery workflow, but this will not be done until the AH work is complete.
* locally start SEED with the always eager flag set to false. 
* test the `Update from ESPM` method. It should now return successfully and update the SEED property
n/a

Fix 179d ESPM update endpoint to run in foreground with Celery enabled

---

seed/static/seed/js/controllers/inventory_detail_meters_controller.js

Fixes showing meter readings for meters that don't have a `source_id` value
#4228

Fix Meters Without `source_id`

---

seed/models/property_measures.py
seed/models/scenarios.py
seed/tests/test_property_measures.py
seed/utils/api_schema.py
seed/views/v3/meters.py
seed/views/v3/property_measures.py
seed/views/v3/property_scenarios.py

These changes are cherry picked from a64092639fcb4647d0d5d4c257a56858561f2f46 on the `bps-feature-develop` branch that was never merged to develop (but all of the BPS changes were merged in with https://github.com/SEED-platform/seed/pull/3899/)
- Fixed 500 errors when the input datatypes did not match the expected model types
- Fixed 500 error when using PUT with a nonexistent scenario
- Removed 3 fields from the scenario input model that always resulted in 500 errors: `measures`, `property_state`, and `reference_case`
- Removed unused pagination inputs on measures endpoints
- Fixed listing measures for a scenario, if the scenario exists with zero measures it now returns an empty array rather than a 404
- Fixed measure input model, `recommended` is a boolean rather than a string
- Updated …

Fixed Issues with Scenario/Measure CRUD Operations

---

docker/nginx/seed-csp.conf

Allows modern network requests (via fetch) to be made to ArcGIS for displaying census tracts
1. Run seed through nginx
2. Zoom in on the map page and check that census tracts are visible

ArcGIS CSP rule

---

seed/static/seed/js/controllers/inventory_map_controller.js

Filtering properties or taxlots by label on the map page works as expected for small databases, but once property/taxlot ids are no longer identical to view ids the map view filters against the wrong ids.
Filters properties and taxlots using the view id instead of the property/taxlot id

Fix edge case for map label filtering

---

CHANGELOG.md
docker/nginx/seed-csp.conf
docs/source/migrations.rst
seed/static/seed/js/controllers/inventory_map_controller.js

* Remove Deprecated APIs (#4049)
* Remove deprecated endpoints
* Update tests
* Remove additional code related to API v2
* Add ubid_threshold to expected org response
* Lock `google-chrome` to v114 (#4165)
Lock chrome version to webdriver version
* Bump word-wrap from 1.2.3 to 1.2.4 (#4154)
Bumps [word-wrap](https://github.com/jonschlinkert/word-wrap) from 1.2.3 to 1.2.4.
- [Release notes](https://github.com/jonschlinkert/word-wrap/releases)
- [Commits](https://github.com/jonschlinkert/word-wrap/compare/1.2.3...1.2.4)
---
updated-dependencies:
- dependency-name: word-wrap dependency-type: indirect ...
* Fix a few code-formatting issues (#4172)
* run autopep to cleanup a few straggling issues
* Run precommit against migrations
* Cleanup unnecessary logging
---------
* Add Open Street Map …

Release 2.20.0 (again) (#4273)

---

seed/static/seed/js/controllers/admin_controller.js
seed/static/seed/js/controllers/new_member_modal_controller.js
seed/static/seed/js/seed.js
seed/static/seed/partials/admin.html
seed/static/seed/partials/new_member_modal.html
seed/static/seed/tests/new_member_modal_controller.spec.js
seed/tests/test_admin_views.py
seed/views/v3/users.py

There are 2 locations new users can be created
1. /app/#/accounts/{org_id}/members > invite new member
2. /app/#/profile/admin (only if current user is a superuser)
Adds ALI info to the superuser 'create a user' form. If a new organization is selected the ALI fields are set to undefined and disabled. The result user will be assigned to the root of the new org.
As a superuser create a new user from both members and admin pages.

Fix user creation bug

---

seed/analysis_pipelines/better/pipeline.py

There appears to have been an update with BETTER's API where measure recommendations are either `''` or `True`. 
Hande the case where the measure recommendation is an empty string
Run a property with better (I used `better.lbl.gov`)
n/a

Fix mapping of BETTER's measures with empty strings to false

---

seed/analysis_pipelines/better/client.py

BETTER's API can begin limiting API requests for long periods of time once a certain threshold of requests have been sent for a specific API key.
Reduces the polling rate for BETTER results from every second to every 5 seconds, and increases the timeout from 1 minute to 5 minutes.
Monitor backend network requests when performing a BETTER analysis.

Decrease BETTER polling rate 5x, increase timeout 5x

---

seed/views/v3/properties.py

Okay, so I miss did this endpoints permissions, this fixes it.  it sheds light on a problem tho:
the `/properties` endpoint _all_ are about PropertyViews, _except_ for this one, which uses Properties. Which is weird. Should I move it? to where?

Ah fix analysis list

---

seed/views/v3/portfolio_manager.py

While importing data from ESPM for Better Buildings I ran into the issue where some of the ESPM reports were failing to download.
Increases the max timeout from roughly 20 seconds to 3 minutes for when SEED is waiting for the ESPM report template to be generated.
Attempt to download Boston report from Better Buildings and see if it fails on the first attempt or not.
#4295

Increase ESPM max timeout

---

seed/static/seed/js/controllers/cycle_admin_controller.js

We recently added the `ng-strict-di` directive for strict dependency injection checking
Fixes the cycle deletion modal that was missing the `organization_service` injection
Click the `Delete` button for any cycle, ensure that the modal appears

Fix cycle deletion modal

---

config/settings/docker.py

Fixes bug with CELERY BROKER connection string to Elasticache Redis
In Django shell, print CELERY_BROKER_URL to make sure it is correct when using Docker.py settings.
No

Feature to enable Redis for ElastiCache

---

seed/static/seed/js/controllers/inventory_list_controller.js

Fixes showing derived column values.  The issue was a strict type comparison between a string and a number, that should've both been numbers
Check that derived column values appear on the inventory list page

Fix showing derived column values on the inventory list page

---

config/urls.py
seed/views/main.py

Tools like Docker can better integrate with containers if they offer a method for checking the health status of the container and its dependencies.
Adds a new, undocumented API endpoint that does not require authentication to check the status of the various systems necessary for SEED to function properly
- Endpoint: `/api/health_check/`
- 200 response code if everything is healthy, 418 otherwise
Example response:
**_HTTP 200_**
```json
{
"status": "healthy",
"postgres": "success",
"celery": "success",
"redis": "success"
}
```
1. Run SEED, check that the status is healthy
2. Stop celery, check that status has updated
3. Restart celery, stop redis. Check that both celery and redis are unhealthy
4. Restart redis, stop postgres. Check that only postgres is unhealthy
5. Restart postgres, check …

Health check endpoint

---

seed/static/seed/js/controllers/organization_access_level_tree_controller.js

Correct the data import modal id that points to the access level import file (corrupted during a merge).
To verify: ensure that when going to this page, and clicking on "upload access level instances" button and ensure the correct modal pops up.

update modal step ID

---

docker/start_celery_docker.sh
docker/start_uwsgi_docker.sh

This fix disables wait-for-it scripts that are not needed as managed services such as Postgres, Redis are not in docker and are already running.  So wait-for-it scrips are not needed in Stratus environment.
Build Docker image of seed and deploy to Stratus.

Provide environment variable to disable wait-for-it condition in deployments

---

docker-compose.local.yml
docker-compose.yml

Adds `healthcheck` to the `seed_web` container so that Docker understands the health status of the dependencies.
1. Run SEED using `docker compose`
2. Wait for the health status of the `seed_web` container to transition from `Starting` to `Healthy`
3. Stop the `seed_celery` container
4. Wait at most 60 seconds, and check that the container status is now `Unhealthy`
5. Start the `seed_celery` container
6. Wait at most 60 seconds, and check that the container status is now back to `Healthy`

Add healthcheck to docker web container

---

docs/source/developer_resources.rst
seed/utils/salesforce.py

Restoring a production database results in any scheduled tasks to inadvertently start running on the instance where the restore takes place
Updates the production database `pg_restore` documentation with steps to disable Salesforce syncing once the restore is completed
After restoring a production database follow the updated steps in the documentation and ensure that the celerybeat periodic tasks related to Salesforce are disabled

Updated salesforce pg_restore docs

---

seed/analysis_pipelines/co2.py

Very tiny bug fix - when creating a column during the CO2 analysis, it was naming the column with a tuple instead of a string.

Fix co2 analysis column naming

---

seed/static/seed/js/controllers/inventory_reports_controller.js
seed/views/v3/organizations.py

Truly the dumbest, least efficient way to do this, but it's the least invasive and if/esle-y

Add count to default reports

---

seed/models/analysis_property_views.py
seed/views/v3/analysis_views.py

Improves a very long, slow query, by ~17x
Previously, `GET /api/v3/analyses/` took `~13.52s`, now it takes `910ms` - `4.19s` for the same large dataset
Request the above URL and check the response timing
#4433

Additional analyses performance improvement

---

seed/static/seed/js/controllers/insights_property_controller.js

X-axis label was missing for "Ranked distance to compliance" on property insights page. 
It is there now:

display x axis label for ranked distance to compliance

---

seed/models/building_file.py
seed/tests/test_building_file.py
seed/views/v3/building_files.py

Add permissions to BuildingFile

---

seed/static/seed/partials/home.html
seed/static/seed/scss/style.scss
seed/templates/seed/_sidebar.html
vendors/package-lock.json
vendors/package.json

FontAwesome automatically updated from `v6.4.2` to `v6.5.0`, which caused alignment issues and visible scrollbars:
Fixes the alignment for the latest version of FontAwesome
1. Run `npm install`
2. Check that tiny scrollbars no longer appear on the homepage

Fixed FontAwesome v6.5 alignment

---

seed/static/seed/js/controllers/inventory_list_controller.js
vendors/package-lock.json
vendors/package.json

UI Grid has a known bug where unpinning a pinned column causes the filter box to disappear (until you either scroll away from the column and back, or refresh the page).
- Adds a workaround to handle a preexisting bug in UI grid by unpinning, hiding the column, and restoring the column. This is necessary because the underlying issue is a race condition with the filter destructor, and the column has to be recreated.
- This PR also hides the `Pin Right` menu option, since we don't respect that option
1. On the Inventory List page, pin a column
2. Unpin the same column, check that the filter box is still present
If there are other grids in SEED that allow pinning _and_ filtering they should be updated as well.
#3760

Restore column filters when unpinning

---

seed/static/seed/scss/style.scss

FontAwesome recently released a minor update that included several positioning changes
Fixes the note-count text alignment
Browse to the Inventory List view, look at the the notes-count column for rows with >0 notes
<table>
<tr><td>Before:</td><td>After:</td></tr>
<tr>
<td><img src="https://github.com/SEED-platform/seed/assets/411466/51e37db5-7085-420f-95d0-5340633d8fab"></td>
<td><img src="https://github.com/SEED-platform/seed/assets/411466/d138867e-1392-4929-bc46-f9387f1c6e3a"></td>
</tr>
</table>

Fixes text alignment following FontAwesome changes

---

seed/utils/sensors.py

Removes a long, unnecessary `COUNT` query, which cuts query time by 40%
Browse to the sensors page for an org with, ideally, millions of readings
#3328

Sensor reading performance improvement

---

seed/data_importer/meters_parser.py

See comments in the issue for added context
Prevents ESPM meters from being imported twice (and failing) due to multiple energy types matching a single meter column
Import ESPM meter data using a meter column name that starts with `Diesel #2 Use`
#4474 
Importing a diesel energy type after the fix:

Fix importing diesel meter readings

---

seed/static/seed/js/controllers/inventory_map_controller.js

maps use to get data pages  like this
now it does it like this
yay!
Best speed up for https://github.com/SEED-platform/seed/issues/4430 will be view-location based filtering, but this is nice to.

Retrieve all map data at once

---

seed/static/seed/js/controllers/inventory_list_controller.js

PR #4480 introduced a bug that prevents inventory from loading if the user has never sorted a column for the current org (localStorage has no sort key)
Fixes showing the Inventory List data if there is no pre-existing sort rule
1. Create a new org
2. Import data
3. Go to the Inventory List page, ensure that data appears

Fix inventory loading if no previous sort settings exist in localStorage

---

seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
seed/static/seed/partials/accounts.html
seed/static/seed/partials/accounts_nav.html
seed/static/seed/partials/data_upload_modal.html
seed/static/seed/partials/data_upload_modal_progress.html
seed/static/seed/partials/organization_add_access_level_instance_modal.html
seed/templates/seed/_header.html

1. Moved Access Level Tree option so the menu is correctly alphabetized:
2. Fixed the upload dialog so it no longer shows 2 lines saying "uploading xxxx to cycle yyyy":
3. Fixed the level numbering on the "Add access level instance" modal.  Levels used to be listed as 0-based. Now only listing levels where you can actually add an instance (level 2 and up):

AH UI Fixes for access level modals

---

seed/static/seed/js/services/simple_modal_service.js

The simple modal service broken somewhere along the way...this PR fixes it. 
To test: ensure that you can delete a label or a derived column.
thanks @perryr16!

fix simple modal service

---

seed/static/seed/js/controllers/update_item_labels_modal_controller.js
seed/static/seed/js/services/simple_modal_service.js
seed/static/seed/partials/update_item_labels_modal.html

This PR resolves the bug described in #4502
As an org owner: user can create a new label and assign it to properties:
As an org owner: user can assign labels to the properties they have access to, but not create new labels:

AH - Fix label creation UI

---

seed/docs/views.py
seed/lib/superperms/orgs/decorators.py
seed/static/seed/js/controllers/goal_editor_modal_controller.js
seed/static/seed/js/controllers/menu_controller.js
seed/static/seed/js/controllers/portfolio_summary_controller.js
seed/static/seed/js/services/user_service.js
seed/static/seed/partials/goal_editor_modal.html
seed/static/seed/partials/portfolio_summary.html
seed/templates/seed/base.html
seed/tests/test_account_views.py
seed/tests/test_goals.py
seed/views/main.py
seed/views/v3/goals.py

Per Sydney, partners should only have read access to goals.
- Adds frontend logic to prevent leaf users from accessing goal configs 
- Adds a backend decorator to prevent leaf users from performing write actions on goal views (create, update, delete)
- As root user create/update/delete goals 
- As a middle tree user (not root or leaf) create/update/delete goals
- As a leaf (partner) user attept to create/update/delete goals. Your permission should be denied.
- In a new org with a single user with an access level tree depth of 1, create/update/delete goals
Leaf
Root
Middle
Root & Leaf

Restrict leaf user permissions for goals

---

seed/static/seed/js/controllers/portfolio_summary_controller.js

- adds "Year Built" to table
- adds a logic to find non null columns given 2 property views from different cycles.
- Year Built column should appear in the table. 
- Columns that are constant between cycles (property name, pm property id, year built) should appear if values exist in either baseline or current, with a default to current.

Add year built to goal table

---

seed/static/seed/js/controllers/portfolio_summary_controller.js

Empty properties in a cycle would prevent portfolio summary from loading
Sets default properties as `{}` if they are missing
Create goals with empty cycles or missing properties in one of the cycles

Set default property if goal property is undefined

---

seed/data_importer/tasks.py
seed/lib/progress_data/progress_data.py
seed/lib/superperms/orgs/models.py

The `Upload Access Level Instances` functionality was correctly set up as a background task, but wasn't running in the background
Updates that task to run in Celery, and adds progress status
Upload a hierarchy on the Access Level Tree page, and observe the progress bar status

Enable background progress for uploading AH levels

---

seed/views/v3/label_inventories.py

ignore "duplicate errors" when adding labels to properties.
related issue: #4144

ignore duplicates when adding labels

---

seed/views/v3/organizations.py

- Adjust permissions for default reports page.  Allow viewers to load the default reports page (was set to require_members).
- Also fixed retrieving extra_data x and y columns.
#4123

fix 403 error for viewer role

---

seed/static/seed/js/controllers/inventory_list_controller.js

Do not display an error to user when a filter only contains an operator (>, <, =, etc.). Assume that the user is still typing.
Type an operator in a filter field on the inventory list page and ensure there is no red notification that pops up.
#3970, #4106

Inventor List - Ignore incomplete filters containing just an operator

---

.cspell.json
config/settings/docker.py
config/settings/docker_dev.py
config/settings/local_untracked.py.dist
config/settings/test_local_untracked.py
docs/source/aws.rst
docs/source/linux.rst
docs/source/migrations.rst
docs/source/setup_osx.rst
requirements/base.txt

The dependency we were using to leverage Redis as the Django/Celery cache (`django-redis-cache`) effectively hasn't been updated since 2020, and requires `redis-py < v4.0`. Redis-py introduced cluster-mode in v4.1.0.
Drops the `django-redis-cache` dependency in favor of `django-redis`, which is compatible with current versions of `redis-py`. This PR also adds `hiredis` for performance.
Once we migrate to Django v4 we can use Django's built-in Redis support going forward.
1. `pip install -r requirements/base.txt`
2. Update your local config (usually `local_untracked.py`), **see the migration steps below** to understand what to change
3. Test that SEED and Celery work as expected
#4375
This updated dependency requires users and deployments to modify their `CACHES` config. [Django v4 uses …

Redis backend update

---

seed/data_importer/tasks.py
seed/tests/test_greenbutton_import.py
seed/tests/test_meter_usage_import.py

Updates the error message to be more descriptive if incoming readings (meter, sensor, greenbutton) have duplicate date-pairs.
Old message: "Overlapping Readings."
~New message: "Import failed. Unable to import data with overlapping readings."~
New message: "Import failed. Unable to import data with duplicate start and end date pairs."
#4253

Update error message on overlapping reading import

---

requirements/aws.txt
requirements/base.txt

Downgrades `django-redis` for compatibility with boto3 to resolve this error:
```
Requirement already satisfied: boto3==1.34.42 in c:\nrel\seed.clean2\.venv\lib\site-packages (from -r requirements/aws.txt (line 2)) (1.34.42)
ERROR: Cannot install django-redis==5.2.0 and django-redis==5.4.0 because these package versions have conflicting dependencies.
```
`pip install -r requirements/aws.txt` should succeed

Fix Redis compatibility with boto3

---

seed/data_importer/tasks.py

Curly braces `{ }` are an angular reserved operator used to pass variables from js to html, if braces are included in incoming file headers angular becomes confused and misrepresents data.
Rejects import files if the headers contain curly braces `{ }`. 
Invalid files will be rejected before the mapping screen.
example invalid header file (any file with braces in a header will do)
[12props_special_characters.xlsx](https://github.com/SEED-platform/seed/files/14312847/12props_special_characters.xlsx)
#4511

Reject import file if it contains braces

---

seed/static/seed/js/controllers/inventory_detail_controller.js

Tiniest bug to display access levels table on inventory details page: fix for level 1 instance not showing up in the table.

AH - Fix level 1 Access Level display in Inventory Details Page table

---

seed/analysis_pipelines/better/pipeline.py
seed/analysis_pipelines/co2.py
seed/analysis_pipelines/eeej.py
seed/analysis_pipelines/eui.py
seed/lib/superperms/orgs/models.py
seed/models/analyses.py
seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/partials/inventory_detail_analyses_modal.html
seed/tests/test_analysis_pipelines.py

Restrict creation of new extra data columns during an analysis run to root owner and members.
If the analysis is run by a leaf member, and the columns do not exist, they will not be created. If they exist, they will be populated with the analysis results.
Import data in a hierarchy-enabled org. 
Create a leaf node user
As leaf node user, create an analysis. Verify that no columns were created on the org.
As a root node user (owner or member role), create an analysis. Verify that columns were created and populated.
eligible analyses:  eui, co2, eeej, BETTER.
#4220

AH - Revise analysis permissions for creating columns

---

seed/static/seed/js/controllers/portfolio_summary_controller.js
seed/static/seed/partials/portfolio_summary.html
seed/static/seed/scss/style.scss

The Portfolio Summary page had a number of layout issues, especially on Windows with 3x nested scrollbars:
- Fixes several layout issues with the Portfolio Summary page, and removes all unnecessary scrollbars
- Adds responsive layout handling
- Adds minimum column width to the summary grid
1. Go to the Portfolio Summary page, and create a goal if necessary
2. Test that the page appears as expected, on reload, and as the browser window is resized

Fix portfolio summary layout

---

seed/lib/superperms/orgs/decorators.py
seed/static/seed/js/controllers/delete_data_logger_modal_controller.js
seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/sensor_service.js
seed/static/seed/partials/delete_data_logger_modal.html
seed/templates/seed/_scripts.html
seed/tests/test_property_views.py
seed/views/v3/data_logger.py

https://github.com/SEED-platform/seed/issues/3375

Allow data logger deleteion

---

seed/static/seed/js/controllers/menu_controller.js

When changing the organization from the menu, the page did not redirect to that org's data if the url contained an `organization_id` argument.
checks for the presence of the `organization_id` arg and updates it if necessary
With multiple orgs navigate to any of the organization settings pages. Change the org from the dropdown. The page data should reflect the newly selected org.
#4575

Redirect on org change if necessary

---

seed/views/v3/properties.py

The search endpoint in swagger was missing the org_id as a parameter, causing it not to return results.
* Add the schema helper to the endpoint
* in a property with data, go to swagger
* in search, enter data into one of the fields and the org_id
* results should return now
n/a

Fix property search endpoint in Swagger

---

seed/static/seed/partials/members.html
seed/tests/test_organization_users.py
seed/views/v3/organization_users.py

ICF requested that the members page should only show users that are at their own level or below.
i.e. starbucks partners should only be able to see starbucks partners, not admin users, and not other partner users
Uses ALIs to filter out users with higher permissions
create a few members at different access levels. 
Log in and navigate to 'members' page. Only users in your ali or below are visible.
#4569
Admin
Sector Level
Partner Level

Limit member visibility to users within access level instance

---

seed/data_importer/tasks.py
seed/models/column_mappings.py

https://github.com/SEED-platform/seed/issues/4164
I have a version that factors out the section that is asking to be factored out, but `delimited_fields` is called again outside that, when "expanding the row"

Allow jurisdiction_tax_lot_id display name change

---

config/settings/common.py
seed/templates/drf-yasg/swagger-ui.html

Swagger, by default, allows loading external schemas via the URL input at the top, which presents a security risk. Fortunately, this risk is mitigated by our strict CSP, but it's a good practice to remove the field regardless.
Removes the header containing the Swagger URL field
Go to the Swagger page and confirm that the header is no longer present
#4346

Updated Swagger config to prevent requesting external schemas

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/partials/inventory_list.html

The label filters (and, or, exclude) are based attached to the model via a `<tags-input>` and `<auto-complete>` elements. If a valid label is selected, its value is attached to the `<tags-input>`'s ng-model. If invalid text is entered, it is not attached to the ng-model and not available to reset in $scope. This makes clearing the text difficult.
After resetting the ng-model's labels, the trashcan icon will also re-render the `<tags-input>` element, clearing any remaining text. 
It's a little hacky, but it's cleaner than trying to locate the correct HTML element within <tags-input>, clear its contents, and convince the element that it is now in a 'valid' state.
Add a few labels. Filter on those labels. Add some random text to the filter fields. Hit the trash icon.
#4305 …

Clear invalid label tags

---

seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/controllers/inventory_map_controller.js
seed/static/seed/js/services/inventory_service.js

When requesting filtered properties with the `/api/v3/properties/filter/` endpoint, if you leave out the `cycle` param the backend defaults to the first alphabetical cycle
- Makes the cycle id explicit, so that when you're on the Inventory List page, select records, and open the merge modal, it will now work for all cycles and not just the first alphabetical cycle
- Fixes the cycle toggle on the map page, it was also affected by this issue
- Adds a fallback on the front-end, such that if a cycle isn't passed when filtering properties it will use the most-recently selected cycle
1. In an org with multiple cycles, go to the Inventory List page and select any cycle that is not alphabetically sorted first
2. Select a few records, and then open the Merge modal
3. Ensure that the data appears …

Fix merge modal for all cycles

---

seed/tests/test_utils_ubid.py
seed/utils/ubid.py

Prior to this change, when importing a file with a UBID we were setting the PropertyState's latitude and longitude to the center of the UBID _**bounding box**_, which isn't necessarily representative of the footprint.
- Sets the PropertyState's latitude and longitude to the center of the UBID _**centroid**_.
- This PR also fixes floating-point rounding errors for lat/long values when geocoding from a UBID by rounding to 12 decimal places. There's no risk of loss of precision, because at its highest precision the area encompassed by the coordinate would be _12,392 square nanometers_ at the equator.
1. Upload a file with a UBID like `85FPPRRC+XH9-7-8-3-6`
2. Confirm that the lat/long is `39.7424125, -105.178515625`, NOT `39.7424625, -105.178484375`
The red dot represents the lat/long SEED …

Geocode UBIDs using centroid

---

seed/data_importer/match.py
seed/utils/merge.py
seed/utils/ubid.py

This is in response to some bugs Robin encountered while testing the UBID work
- Fixes a bug that caused the import process to hang if ubid was the only matching criteria 
- Fixes a bug that did not preserve access level instances on merges
The following test files include the NREL FTLB, the NREL Cafe, and an invalid property without a ubid. Each file increases the ubid footprint.
1. set matching criteria to only ubid
2. upload a file with ubids [3props_ubids_0.xlsx](https://github.com/SEED-platform/seed/files/14910546/3props_ubids_0.xlsx)
3. in org settings change the ubid threshold to 0.1 to allow matching 
4. upload a file with slightly different ubids [3props_ubids_1.xlsx](https://github.com/SEED-platform/seed/files/14910547/3props_ubids_1.xlsx)
5. properties should have been merged …

Fix ubid bugs

---

seed/static/seed/js/controllers/inventory_detail_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/filters/floatingPoint.js
seed/static/seed/js/seed.js
seed/static/seed/partials/inventory_detail.html
seed/templates/seed/_scripts.html

UBIDs like `86HJX66V+M5R-4-1-3-2` decode to latitude/longitude centroids with floating-point rounding errors:
> 41.96174999999997, -87.75712499999999
- Adds a new `floatingPoint` AngularJS filter that can automatically fix floating point rounding errors
- Applies the floatingPoint filter to latitude and longitude on the Inventory List/Detail pages
- Fixes latitude/longitude truncation on the Inventory Detail page
1. Upload the covered building list file, ensure that the geocoded lat/long values don't display floating point rounding errors
Before and after:

Fix floating point rounding

---

seed/static/seed/js/controllers/inventory_list_controller.js

Related values could be null, when we were expecting strings. This change fixes that issue
1. Create a new database
2. Import `covered-buildings-sample.csv` with taxlot and property mappings
3. Check that the inventory list loads
#4624

Handle null values in related columns

---

seed/static/seed/js/controllers/inventory_list_controller.js

Sometimes some of the items are not shown in the Actions dropdown on the inventory list (the one I notice is "Only Show Populated Columns").  Refreshing the page fixes the issue, but this is annoying.
I tracked the issue down to menu.user.is_ali_root not always being populated on some redirect issues.
To test:
- go to inventory list page
-  ensure you see 'only show populated columns' from actions dropdown
- switch the org to a different org in the top right of the page. the page will refresh
- open up the actions dropdown and ensure AGAIN that 'only show populated columns' is still there

ensure is_ali_root is populated on redirects

---

docker-compose.build.yml
docker-compose.dev.yml
docker-compose.local.yml
docker-compose.pgupgrade.yml
docker-compose.yml
docker/dump_database.sh
docker/postgres_upgrade.sh
docker/restore_database.sh

The script `./docker/postgres_upgrade.sh` will properly upgrade a database from pg12.7-(2.3.0) to pg14.11-(2.14.2).  It works in conjunction with the "docker-compose.pgupgrade.yml" docker-compose file to temporarily run Timescale Postgres 13 and 14 images.
./docker/postgres_upgrade.sh  --source-pg-conv-version 13 --source-ts-conv-version 2.11.2 --target-pg-test-version 14 --target-ts-test-version 2.11.0

Docker upgrade database

---

docs/source/postgres_upgrade.rst

When using pg_restore with TimescaleDB, it is very important that the version of the TimescaleDB extension is the same in the source and target databases.
- Adds documentation for upgrading Postgres and TimescaleDB to the latest version. This process can be used to upgrade to any Postgres version higher than 12
- Transitions us away from the deprecated `timescale/timescaledb-postgis` images to the modern `timescale/timescaledb-ha` images
1. Follow the steps
2. Ensure that there are no errors during pg_restore
Related to #2655

Postgres 16 upgrade documentation

---

seed/tests/test_portfoliomanager.py
seed/views/v3/portfolio_manager.py

The CI was relying on ESPM report `2807325`, which appears to no longer exist
Creates a replacement
Tests should pass

Replaced missing ESPM report

---

seed/static/seed/js/controllers/portfolio_summary_controller.js

All cells appeared editable. It's only a UI issue as there was no backend logic to make changes permanent
Sets the default cell style to non-editable
- go to portfolio summary
- double-click a non-goal_note cell in the bottom table
- cell should not appear editable
- goal notes should still be editable

Set default portfolio summary cell type

---

requirements/base.txt

Numpy v2 was released yesterday, and pnnl-buildingid doesn't specify which version, so the CI (and updated local instances) are failing to work with the new major version
Locks [numpy to `v1.26.4`](https://github.com/SEED-platform/buildingid/commit/892958be07c55eebdbf582f5a81d4b1ce6d61412)
The CI should pass

Lock Numpy

---

package-lock.json
package.json
vendors/package-lock.json

There have been a small handful of dependabot PRs lately related to package-lock npm versions. This PR recreated the package-lock.json files using the latest semantic versions.
The CI should pass, and local monkey testing should look the same

Node dependency upgrade

---

seed/tests/test_meter_views.py
seed/utils/api_schema.py
seed/utils/viewsets.py
seed/views/v3/building_files.py
seed/views/v3/gbr_properties.py
seed/views/v3/meter_readings.py
seed/views/v3/meters.py
seed/views/v3/property_views.py

- Adds missing AH restrictions to all meter reading endpoints
- Adds AH tests for all meter reading endpoints
- Removes meter reading `PATCH` endpoint for consistency
- Fixes all writable PropertyView endpoints to restrict actions to members or higher, and include `organization_id`
- Fixes all meters Swagger endpoints to include `organization_id`
- Query reduction in `MeterReadingViewSet`
- Adds a `datetime` Swagger schema helper
Tests should pass

Fix several AH meter issues

---

package-lock.json
package.json
seed/data_importer/match.py
seed/data_importer/models.py
seed/data_importer/tasks.py
seed/data_importer/tests/test_ah_import.py
seed/utils/match.py
seed/utils/ubid.py

When `UBID` is part of the matching criteria along with other columns, importing records with empty UBIDs would incorrectly match against existing records with populated UBIDs.
- Treats UBID as a matching column as strictly as other matching columns
- Small cleanup
See the example in the related ticket
#4713

Fix UBID matching behavior

---

seed/static/seed/partials/inventory_detail.html

Fixes missing inventory detail sections when properties don't have elements
Go to the inventory detail page for a property without elements, ensure that documents/files/scenarios/measures all show up

Fix missing inventory detail sections

---

seed/static/seed/js/controllers/column_mappings_controller.js
seed/static/seed/partials/column_mappings.html

Adds messaging to the save button tooltip to help explain why the button may be disabled for column mapping profile changes.
View the column mappings page and make changes to extant profiles
#4701

Add messages for reasons the save button on column mappings is disabled

---

config/settings/common.py
config/settings/local_untracked.py.dist
config/urls.py
requirements/base.txt
seed/landing/models.py
seed/migrations/0227_remove_oauth.py
seed/utils/viewsets.py

- We've been frequently seeing warnings related to our jwt oauth dependencies related to Django v4:
`/usr/lib/python3.9/site-packages/oauth2_provider/signals.py:4: RemovedInDjango40Warning:The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.`
- The [jwt-oauth2](https://github.com/GreenBuildingRegistry/jwt-oauth2) library hasn't been updated in 6.5 years, and is incompatible with newer versions of the sub-dependencies that resolve this error.
- We've never used this dependency, but there's a chance that it's being used downstream by Earth Advantage. Once they upgrade to the latest version of SEED, if this is an issue for them we can discuss …

Remove jwt oauth

---

seed/utils/api_schema.py
seed/views/v3/elements.py

We had endpoints to list all elements for an org (or a single element by id), but no method for filtering them
Adds a new `GET /v3/elements/filter/` endpoint that filters for all organization elements under a specific Uniformat code. This is useful for finding which properties have specific types of elements
Given a database with elements, test URL like:
`GET /api/v3/elements/filter/?page=1&per_page=10&organization_id=2&code=D2010`

Filter elements endpoint

---

seed/data_importer/tasks.py
seed/utils/migrations.py

If you had a database that was on a migration earlier than [migration 0223](https://github.com/SEED-platform/seed/blob/develop/seed/migrations/0223_water_use_columns.py) and attempted to migrate using the latest codebase, then 0223 would fail because #4769 changed the rehash function to expect a new column to exist.
- Changes the rehash function to check if [migration 0225](https://github.com/SEED-platform/seed/blob/develop/seed/migrations/0225_column_is_excluded_from_hash.py) has run yet, and if not it uses the older rehash logic
- Adds a performance improvement so that an organization's columns are fetched only once instead of for every Property/TaxLot State (19% faster than the improvements added in #4754)
1. Checkout SEED v3.0 and create a new database
2. Import some data
3. Checkout …

Fix rehash migrations prior to `is_excluded_from_hash`

---

CHANGELOG.md
requirements/base.txt

Any new docker builds (or virtual environments) created within the last 5 hours have failed to start celery due to the error `name 'hiredis' is not defined`.
This is because `redis` v5.0.8 had the dependency `hiredis>=1.0.0`, but v5.1.0 included the breaking change `hiredis>=3.0.0`. `redis` is a sub-dependency of our dependency `django-redis`, which has a _very_ liberal requirement of `redis>=4.0.2`.
Updates `hiredis` to v3.0.0 to match the [requirement from the sub-dependency `redis`](https://github.com/redis/redis-py/blob/v5.1.0/setup.py#L59) to resolve celery launch errors
1. Create a new virtual environment
2. Run `pip install -r requirements/base.txt`
3. Ensure Django and celery both start successfully

Fix `hiredis` not found error

---

.github/workflows/ci.yml
package-lock.json
package.json

Updates the sass package to version 1.79.4 which will hopefully last only until Alex finishes the dependency upgrades.
Ideally this will fix the CI runs for testing.

Lock sass dependency and enforce Node v20

---

seed/models/tax_lot_properties.py
seed/static/seed/js/controllers/inventory_group_modal_controller.js
seed/static/seed/js/controllers/inventory_list_controller.js
seed/static/seed/js/seed.js
seed/static/seed/js/services/organization_service.js
seed/static/seed/scss/style.scss
seed/tasks.py
seed/tests/test_inventory_groups.py
seed/tests/test_organization_access_levels.py
seed/utils/merge.py
seed/views/v3/access_levels.py
seed/views/v3/properties.py
seed/views/v3/taxlots.py

- Adds a function to limit available ALI selections to the current node and its descendants.
EX: say an org's access levels are
Level1 
Level2
Level3
A user who belongs to Level2 should be able to create a group for Level2 & Level3 but not for Level1
- Adds groups indicator
- Refactors group merge
- Adds logic for pruning orphaned inventory mappings & groups
Log in with a child user. Create a group from the group list page.
In this example, the user is a member of the SubSector level.
Existing:
New:
Group Indicator (not clickable)

Add various inventory group features

---

seed/views/v3/organizations.py

Handles non-numeric x-axis selections properly - assuming properly means those axis should have all zero values in the rollup table.

Recheck for only numeric data in the rollup table

---

seed/models/filter_group.py
seed/tests/test_filter_groups.py

Fixes a bug where filter groups with ALI selections would not properly filter based on those ALIs.

include organization access_level_names in filter construction

---

seed/static/seed/js/controllers/inventory_reports_controller.js

Fixes the range for numeric x-axis values to be the actual range of data +/- a half percent cushion
Fixes year_built labels to be strings, so the system will not add commas after the thousands digit.
Run a chart where the x-axis is year built, note the range and labels.
#4858

Ensure year_built labels do not have commas, adjust width of scatterchart

---

seed/static/seed/partials/inventory_reports.html
seed/static/seed/scss/style.scss
seed/views/v3/organizations.py

make agg table like a pivot table

update aggregation table

---

CHANGELOG.md
seed/static/seed/partials/inventory_nav.html

The `Data` nav item was ambiguous, and unnecessary, since it wasn't related to Inventory and would navigate away to the Insights page
- Removes the Inventory List `Data` nav item
- Small changelog cleanup
Check that `Data` no longer appears. Old nav:

Remove inventory list `Data` nav item

---

seed/landing/forms.py
seed/landing/templates/two_factor/core/login.html
seed/landing/views.py

The `sessionid` cookie should have only the minimal session-specific data necessary, and not server settings that can become out-of-sync if stored in session tokens
Overrides the `two_factor.views.core.LoginView.render` method to make the backend setting `INCLUDE_ACCT_REG` available to the view template without storing it in each user's session cookie
1. In `local_untracked.py` toggle the `INCLUDE_ACCT_REG = True` variable and check that the login page correctly renders (or hides) the `Create my Account` button
2. Optionally inspect the session cookie data and ensure the `include_acct_reg` is no longer included. Copy your `sessionid` cookie value and run the following commands:
```bash
export DJANGO_SETTINGS_MODULE="config.settings.local_untracked"
```
```python
from django.conf import …
```

Remove server settings from the session cookie

---

config/settings/common.py
config/urls.py
requirements/base.txt
seed/landing/models.py
seed/landing/serializers.py
seed/landing/urls.py

Add simplejwt support to the authorization options, adds an additional block to handle bearer tokens
This PR enables you to get a set of authorization and refresh tokens by authenticating against SEED:
```bash
curl -X POST -H 'Content-Type: application/json' -d '{"username":"usernam@email.com", "password":"password"}' http://localhost/api/token/
```
That will return a refresh and access token:
```json
{
"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzA2MDk4MSwiaWF0IjoxNzM2OTc0NTgxLCJqdGkiOiIzNmRmZjhmMzYwNTc0NjBhYTk3MTJiNTYzZjgzNjg2MyIsInVzZXJfaWQiOjJ9.PampCBSI2djMnfmx8MZv4oocvEVfd_hrY4k238nX81Q",
"access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc0ODgxLCJpYXQiOjE3MzY5NzQ1ODEsImp0aSI6ImIwYTdkMjYwODc4M …
```

Add Simple JWT to authorization setup

---

seed/static/seed/js/controllers/update_inventory_groups_modal_controller.js
seed/static/seed/js/services/organization_service.js
seed/static/seed/partials/update_inventory_groups_modal.html
seed/tests/test_organization_access_levels.py
seed/views/v3/access_levels.py

There was an argument mismatch between the frontend and backend when fetching the ALIs associated with a selection for the groups modal. The frontend passed view_ids while the backend interpreted them as inventory_ids (property_ids or taxlot_ids). On small DBs this wasn't noticeable as the view_ids and property_ids aligned. However, in larger dbs, the views and the properties did not align and the backend would return zero ALI matches. This led to the frontend form being disabled as it expects the ALI count to equal 1, not 0.
- This PR corrects the django db logic by converting the view_ids to inventory_ids before filtering for access level instances. 
- Fixes smaller syntax and swagger bugs
From the inventory list, select a few properties with the same access level and add them to a …

Fixes inventory groups add inventory bug

---

seed/models/properties.py
seed/serializers/analysis_property_views.py
seed/static/seed/js/controllers/analysis_controller.js
seed/static/seed/js/controllers/analysis_run_controller.js
seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
seed/static/seed/partials/analysis_runs.html

Shows property default display field in the analyses table
- create an analysis
- property's default display field should be in the analyses table. If the property is missing the default display field, it will display "Property: Unknown"
#4822

Show default display name on analyses

---

config/urls.py
seed/landing/models.py
seed/views/main.py

Adds an API endpoint to retrieve Django settings needed to render unauthenticated pages
Endpoint: `GET /api/config/`
Currently only returns the setting `allow_signup` but we can expand as needed.

Django settings endpoint

---

seed/landing/serializers.py
seed/views/v3/users.py

The new angular client needs an endpoint to retrieve user information, as token claims will not be reliably refreshed from the db when the underlying user data changes - see this bug: https://github.com/jazzband/djangorestframework-simplejwt/issues/705

Move JWT token claims to v3_users_current

---

seed/landing/models.py
seed/serializers/users.py
seed/tests/test_account_views.py
seed/tests/test_api.py
seed/views/v3/users.py

Adds user serializer, enable it for v3/users/current, v3/users/retrieve and v3/users/update
Principally this is for use in the new Angular UI, but it does not break anything in the extant UI.

Add user serializer

---

seed/views/v3/portfolio_manager.py

ESPM changed their api! This broke our [tests](https://github.com/SEED-platform/seed/actions/runs/13996604162/job/39200257219?pr=4956):
specifically, this line [broke](url):
I tried calling the same endpoint on [portfoliomanager.energystar.gov](portfoliomanager.energystar.gov), and it appears to be a get
I changed it to a get and it worked!

Fix ESPM download, change generateData from POST to GET

---

seed/analysis_pipelines/bsyncr.py

- Ensures that timeseries data in the bsyncr XML generation is sorted by date
- Also adds 'EndTimestamp' to the Timeseries element in the XML

Fix bsyncr xml timeseries ordering

---

seed/views/v3/analyses.py

The `/api/v3/analyses/used_columns/` endpoint was calling `get_num_of_nonnulls_by_column_name` with the wrong arguments for taxlots, and would fail for any organization containing taxlots.
- Fixes the `used_columns` endpoint
1. Create an org with taxlot data
2. Browse to `/api/v3/analyses/used_columns/?organization_id=X`
#4979

Fix `used_columns` error for taxlots

---

seed/views/v3/tax_lot_properties.py

Fixes part 2 of #5013
SEED recognizes the polygon fields `"bounding_box", "centroid", "property_footprint", "taxlot_footprint", "long_lat"`, and during GeoJSON export any field that **even contains** that text (including the extra_data column `property_footprint (Invalid Footprint)` is run through `_serialized_coordinates` expecting valid WKT content without error handling.
1. Import a GeoJSON file with a MultiPolygon:
```json
{
"type": "FeatureCollection",
"features": [{
"type": "Feature",
"properties": {
"Custom ID 1": 1
},
"geometry": {
"type": "MultiPolygon",
"coordinates": [
[
[
[102, 2],
[103, 2],
[103, 3],
[102, 3],
[102, 2]
]
],
[
[
[100, 0],
[101, 0],
[101, 1],
[100, 1],
[100, 0]
],
[
[100.2, 0.2],
[100.2, 0.8],
[100.8, 0.8],
[100.8, 0.2],
[100.2, 0.2]
]
]
]
}
}, {
"type": …
```

Fix exporting GeoJSON records with invalid footprints

---

seed/static/seed/partials/dataset_list.html

For whatever reason, after updating from Chrome v137 to v138, the dataset-list links became unclickable
Moves the link outside of the `span` element, which fixes the problem
1. Update Chrome to the latest version
2. Check that dataset-list links are clickable
#5037

Fix dataset links for Chrome v138

---

seed/audit_template/audit_template.py
seed/views/v3/media.py

Fixes Dataset file download when imported both properties and meters from the same file (duplicate filename issue).
#5043 
How to test: from datasets page, import a file that has meters, then click on the "import meters from the same file" button. Then go back to datasets and try to download the original file.

Dataset links
