SEED-platform/seed

- BE/settings/docker.py
- Dockerfile
- README.md
- bin/docker_environment.sh
- bin/setup_database.sh
- bin/start_celery.sh
- bin/start_celery_docker.sh
- bin/start_uwsgi.sh
- bin/start_uwsgi_docker.sh
- requirements.txt
This import dockerizes the seed platform.  And updated README.md is included.
> Dockerized Seed Platform

- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/partials/mapping.html
Issue #10 - Creating a brand new pull request
> [Issue 10] Creating new pull request for typehead list

- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
- seed/static/seed/less/style.less
- seed/static/seed/partials/data_upload_modal.html
Robin,
These are the new GUI changes for the data upload modal.
> [Issue #89] Prevent modal dismissing altogether and add a cancel button

- seed/static/seed/partials/data_upload_modal.html
Robin,
This is the pull request for the updated buttons to contain the text, and the updated color for cancel button.
Miles,
Could you merge this to seed test ? Thanks
> [Issue #89] Updated buttons

- seed/static/seed/partials/mapping.html
> [Issue #131] Concatenation button hidden

- requirements.txt
- seed/tasks.py
I dont know if this will work but please test it.
> Issue 25 matching

- seed/tasks.py
- seed/tests/test_matching.py
Reworked the _normalize_street_addr() function, fixed some problems and added unit tests.
> Streetaddress fix

- seed/common/tests/test_map.py
- seed/data/pm-mapping.json
Modified JSON mapping and added test
> changed mapping for hardcoded values, Issue #171

- seed/static/seed/partials/mapping.html
On my last pull request merge comments were introduced on one of the two files I updated. So I've pulled from the latest develop and removed the merge comments.
> Updates mapping.html to remove extraneous merge text

- seed/static/seed/js/controllers/menu_controller.js
- seed/templates/seed/index.html
- seed/views/main.py
Show a loading message while the mapping page is loading. Also sped up the load time by optimizing the heavy query that causes the delay.
Fixes #9
> Issue #9 - Mapping page loading indicator 

- seed/static/seed/js/controllers/menu_controller.js
- seed/templates/seed/index.html
- seed/views/main.py
Reverts SEED-platform/seed#219  PR was mistakenly made against master.
> Revert "Issue #9 - Mapping page loading indicator "

- seed/static/seed/js/controllers/menu_controller.js
- seed/templates/seed/index.html
- seed/views/main.py
Reopened again develop:
Show a loading message while the mapping page is loading. Also sped up the load time by optimizing the heavy query that causes the delay.
> Reopen: Issue #9 - Mapping page loading indicator

- BE/settings/dev.py
- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
- seed/static/seed/js/controllers/dataset_detail_controller.js
- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/directives/beUploader.js
- seed/static/seed/js/filters/stripImportPrefix.js
- seed/static/seed/js/services/uploader_service.js
- seed/static/seed/partials/data_upload_modal.html
- seed/static/seed/partials/dataset_detail.html
- seed/tasks.py
Reverts SEED-platform/seed#224.  This PR introduced an issue in file uploading.
> Revert "Upload error handling"

- seed/search.py
- seed/tests/test_views.py
Enable exact and "null" searches on the Building extra_data json blob.
This fix needed a less than ideal hack for the "null" filtering. When fields are mapped and added to the building json blob, they are only added if they contain data. So i'm doing a `contains` query on the JSONField to see if it contains what looks like a key for that field. 
When we bump to Django 1.7, we can update the postgres JsonField package, and make use of postgres's "has" filter. This note was added as a comment in the code.
Refs #20
> Issue 20 - JSON field exact and null searches

- seed/static/seed/js/seed.js
- seed/static/seed/js/services/search_service.js
Reverts SEED-platform/seed#235
> Revert "Issue #12 - Save building filter params in sessionStorage"

- seed/views/main.py
Handle case in which the child node is not a source_type COMPOSITE_BS, and must be included in the buildings list.
> 8 show green button file

- seed/static/seed/js/controllers/menu_controller.js
- seed/templates/seed/index.html
- seed/views/main.py
Bringing the changes from PR 221 back into the develop branch.
> Manual merge of loading indicator patches

- requirements.txt
- superperms/orgs/decorators.py
- superperms/orgs/exceptions.py
- superperms/orgs/models.py
- superperms/tests/test_decorators.py
- superperms/tests/test_organizations.py
This PR moves the `seed-superperms` repo into the root of the `seed` repo and removes the external requirements.  It also updates the superperms tests.
**Be sure to update your dependencies after merging this PR**
```bash
sudo pip install -r requirements.txt
```
> Include superperms

- seed/lib/exporter.py
This fixes #281. I tested using S3 from my local dev environment.
> set contents from file object, not filename

- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
- seed/static/seed/js/controllers/delete_modal_controller.js
- seed/static/seed/js/controllers/matching_controller.js
- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/services/building_service.js
- seed/static/seed/js/services/dataset_service.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/js/services/project_service.js
- seed/static/seed/less/style.less
- seed/static/seed/partials/matching_list_table.html
- seed/templates/seed/_sidebar.html
This fix uses watch statements to update properties bound to count displays via $scope. The fix isn't ideal but is the most expedient  -- see my comments here: https://github.com/SEED-platform/seed/issues/44
> Issue 44 update count labels in nav automatically

- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
- seed/static/seed/js/controllers/delete_modal_controller.js
- seed/static/seed/js/controllers/matching_controller.js
- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/services/building_service.js
- seed/static/seed/js/services/dataset_service.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/js/services/project_service.js
- seed/static/seed/less/style.less
- seed/static/seed/partials/matching_list_table.html
- seed/templates/seed/_sidebar.html
Reverts SEED-platform/seed#295
> Revert "Issue 44 update count labels in nav automatically"

- seed/static/seed/js/controllers/matching_controller.js
- seed/static/seed/less/style.less
- seed/static/seed/partials/matching_list_table.html
Shows # of buildings (given the current filter setting) next to the pulldown selector. Also updates style.less to include new style for a 'data_label' in the table header.
> Issue 51 - Updates table header to include a label showing the # of buildings.

- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
- seed/static/seed/js/controllers/delete_modal_controller.js
- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/services/building_service.js
- seed/static/seed/js/services/dataset_service.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/js/services/project_service.js
- seed/templates/seed/_sidebar.html
This fix uses watch statements to update properties bound to count displays via $scope. The fix isn't ideal but is the most expedient -- see my comments here: #44
> Updates menu to show correct item count in nav items.

- .travis.yml
- requirements/local.txt
- seed/tests/test_views.py
upgrade version of nose and django-nose
fix 1 test failure and skip the last test in the other
> Test failures

- seed/search.py
- seed/tests/test_views.py
Not null filtering via `!""`.
Fixes #250
> Issue #250 - Not null filtering via !""

- seed/static/seed/js/seed.js
- seed/static/seed/js/services/search_service.js
Save building number per page in session storage. 
Fixes #318
> Issue #318 - Save number per page in sessionStorage

- seed/static/seed/js/controllers/building_detail_controller.js
Show all fields on building detail page, even if they're blank.
Refs #67
> Issue #67 - Building detail show all fields

- seed/static/seed/partials/matching_list_table.html
Handle extra_data JSON fields on right side of matching view table.
Refs #325
> Issue #325 - Handle right side matching extra_data fields.

- seed/static/seed/partials/mapping.html
Should also save on a few calls to the server since is_suggestion_BEDES was getting called for each row in the table.
> Removed BEDES column from the table in the mapping screen.

- seed/static/seed/partials/mapping.html
andd DATA FILE HEADER.  Also changed the import filename to span all columns from the import file (all columns except the first).
> Changed table header text for the two header fields to SEED HEADER 

- seed/static/seed/js/controllers/building_detail_controller.js
- seed/tasks.py
- seed/utils.py
Fix for issue Claudine's test suite detected in the original code.  Changed which records to check for duplicates.
> Issue 83 duplicate data fix for which records to check for duplicates

- README.md
- bin/start-seed.sh
- config/settings/common.py
- config/settings/compress.py
- config/settings/dev.py
- config/settings/docker.py
- config/settings/local_untracked.py.dist
- config/settings/main.py
- config/settings/test.py
- config/settings/travis.py
- config/wsgi.py
- docs/source/LINUX.setup.rst
- manage.py
- requirements/base.txt
- seed/__init__.py
- seed/celery.py
- seed/cleansing/tasks.py
- seed/cleansing/tests.py
- seed/tasks.py
Merge down upgrading of celery into data cleansing. After data cleansing is working right, then I will add a PR for DataCleansing to develop.
> update celery to 3.1. enable celery results

- seed/static/seed/partials/matching_detail_table.html
Show extra_data JSON content on matching detail screen.
Before:
After:
Refs #345
> Issue #345 - Matching detail screen show extra_data column content

- seed/static/seed/js/services/search_service.js
Fixes the initial "showing" count on the building list view for the per page dropdown.
Refs #354
> Issue #354 - Update display counts for per page number

- seed/static/seed/less/style.less
- seed/static/seed/partials/admin.html
Change the width on the remove buildings table in the admin. Refs #372 
Before:
After:
> Issue #372 - Change width for admin remove buildings table

- seed/static/seed/partials/data_upload_modal.html
Fix for Issue(https://github.com/SEED-platform/seed/issues/340)
> Modified matching dialog message.

- seed/static/seed/js/directives/dropdown.js
Replaces static URL. Instead, now injecting urls object and using urls.static_url property to build URL.
> Fixes template url issue. 

- seed/views/main.py
Added check to force any buildings with a gross_floor_area > 1 million to be put in the 'over 1,000k' bin.
> Fix for issue 410 aggregate gross floor area bug

- seed/views/main.py
Previously only got data from unmerged building snapshot records.  Per Robin changing that to use only data from merged records (the current canonical building and previous canonical buildings).  One consequence of this is that since there is no current way to null out a field once a building gets a value in a field it will always have that value.  So if there are files with later years uploaded and they do not have the value in them but an earlier file did the later years will report the value from the earlier year since it is perpetuated through the matching.
> Changing the way data is acquired for reports.  

- seed/cleansing/models.py
the cleansing app doesn't persist anything to the DB, so make it a simple class for now.
> remove cleansing django model

- seed/static/seed/js/controllers/buildings_reports_controller.js
Updates the default palette for charts. (New order and adds a couple extra colors.)
> Updates palette for building reporting charts

- requirements/base.txt
- samples/demo_app/requirements.txt
- samples/demo_app/setup.py
- samples/demo_app/stats/views.py
- seed/audit_logs/views.py
- seed/cleansing/views.py
- seed/data_importer/views.py
- seed/decorators.py
- seed/landing/views.py
- seed/static/seed/js/services/auth_service.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/js/services/project_service.js
- seed/static/seed/js/services/uploader_service.js
- seed/static/seed/js/services/user_service.js
- seed/views/accounts.py
- seed/views/api.py
- seed/views/main.py
- seed/views/meters.py
- seed/views/projects.py
Reverts SEED-platform/seed#444
> Revert "Issue #437 - API endpoint status codes"

- requirements/base.txt
- samples/demo_app/requirements.txt
- samples/demo_app/setup.py
- samples/demo_app/stats/views.py
- seed/audit_logs/views.py
- seed/cleansing/views.py
- seed/data_importer/views.py
- seed/decorators.py
- seed/landing/views.py
- seed/static/seed/js/services/auth_service.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/js/services/project_service.js
- seed/static/seed/js/services/uploader_service.js
- seed/static/seed/js/services/user_service.js
- seed/views/accounts.py
- seed/views/api.py
- seed/views/main.py
- seed/views/meters.py
- seed/views/projects.py
Reverts SEED-platform/seed#446
> Revert "Revert "Issue #437 - API endpoint status codes""

- seed/decorators.py
This fixes cleansing. It broke after we tried to standardize the return codes. Please review and make sure my change is appropriate.
> fix response with list object

- seed/cleansing/tests.py
- seed/cleansing/views.py
- seed/decorators.py
- seed/static/seed/js/services/cleansing_service.js
- seed/tests/test_decorators.py
this is a continuation to the fixing the cleansing modal window. The result of the cleansing task is no a dictionary which fits into the ajax_request decorator.
> convert cleansing results to dict

- seed/static/seed/js/controllers/update_building_labels_modal_ctrl.js
It fixes the building label modal js code to work with the new format of the API endpoints.
> Make the label modal work

- seed/static/seed/js/controllers/cleansing_controller.js
This also includes the timezone offset:
> Formatted the time of upload in the Data Cleansing dialog

- seed/tasks.py
- seed/views/projects.py
Reverts SEED-platform/seed#525
> Revert "Piper/issue 434 weird add buildings to project bug"

- seed/static/seed/js/services/search_service.js
Reverts SEED-platform/seed#554. Wasn't finished with PR and code change wasn't correct.
> Revert "Issue with selected_buildings getting out of sync with user selections"

- seed/static/seed/js/services/label_service.js
Some of the comments in label_service.js were out of sync with the latest changes to the code.
Updated comments to match current method signatures.
> Updates label_service class and method comments for accuracy.

- seed/managers/json.py
- seed/mappings/seed_mappings.py
- seed/public/models.py
- seed/search.py
- seed/token_generators.py
- seed/urls/labels.py
- seed/utils/api_client.py
- seed/utils/visualization.py
- seed/views/main.py
- seed/views/projects.py
A new version of pylint was released that included some new linting rules.
Just cleaned up the various bits of code it was complaining about.
> Flake8 fixes for new pylint version

- seed/tasks.py
The JSON serializer for celery could not handle value_list.
Typecase value_list to a list
> typecast value_list to list when serializing to celery

- seed/static/seed/partials/mapping.html
https://github.com/SEED-platform/seed/issues/694
Reference to "Custom ID 1" field was incorrectly written as "Custom ID"
Updated the appropriate template.
> Fix text reference to Custom ID 1 field

- seed/views/main.py
https://github.com/SEED-platform/seed/issues/712
An error in the `django-pgjson` library occurs under the condition that the `extra_data` field is queried with something like `extra_data__gt=...` and then that query is used as a subquery for another queryset.
https://github.com/djangonauts/django-pgjson/issues/35
Force evaluation of the subquery.
> Fix error when deleting buildings when label filter active

- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/partials/mapping.html
View/Hide columns on mapping page doesn't work or make sense right now.
Remove view/hide columns settings on mapping page.
Refs #722
> Issue #722 - Remove view/hide columns from mapping screen.

- config/settings/local_untracked.py.dist
- requirements/base.txt
- seed/energy/__init__.py
- seed/energy/meter_data_processor/green_button_maps.py
- seed/energy/meter_data_processor/green_button_parser.py
- seed/tasks.py
- seed/views/main.py
@nllong I update several files following your feedbacks, the seed/energy/meter_data_processor/green_button_maps.py file is formated by autopep8. Thanks!
> Update as feedbak

- seed/static/seed/js/seed.js
- seed/templates/seed/base.html
Toggles Angular's debug setting based off the Django debug setting.
Refs #729
> Issue #729 - Angular debug setting

- seed/static/seed/partials/members.html
Show role text when you're the single owner on an organization.
Refs #726
> Issue #726 - Show role text for single owners.

- bower.json
- seed/static/seed/js/controllers/update_building_labels_modal_ctrl.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/building_service.js
- seed/static/seed/js/services/label_service.js
- seed/static/seed/js/services/search_service.js
- seed/static/seed/js/utilities/spinner.js
- seed/templates/seed/_scripts.html
- seed/templates/seed/base.html
Add spinner package and add a little utility around hiding and showing spinners in the app. Add spinners to label adding and building filtering stuff.
Refs #607
> Issue #607 - Loading spinners

- seed/audit_logs/models.py
- seed/authentication.py
- seed/cleansing/models.py
- seed/common/mapper.py
- seed/filters.py
- seed/managers/json.py
- seed/pagination.py
- seed/serializers/celery.py
- seed/token_generators.py
- seed/utils/buildings.py
- seed/utils/cache.py
- seed/utils/projects.py
- seed/utils/search.py
- seed/views/accounts.py
- seed/views/main.py
Basic clean up of code to conform to flake8 standards. 
I am planning on cleaning up the time series branch and wanted to make sure develop conforms first.
> cleanup code

- seed/tasks.py
- seed/views/main.py
https://github.com/SEED-platform/seed/issues/732
The data export had multiple places where it was broken.
* Incermenting of the progress key wasn't working correctly in most cases.
* The queries it was using weren't up to date with the latest search logic that was implemented.
* Converted the relevant pieces of code to use the new search functions that were recently developed with the label feature.
* Fixed the callback that updates the progress key to update the correct fields.
> Fixes for data export

- seed/tasks.py
- seed/tests/test_matching.py
Replaces some odd characters during the address normalization step. Adds error handling for cases we haven't found yet.
Refs #761
> Issue #761 - Replace odd characters in address normalization

- seed/static/seed/js/controllers/building_list_controller.js
Clear labels when clear filters button is pressed.
Refs #765
> Clear labels on clear filters

- seed/static/seed/js/controllers/data_upload_modal_ctrl.js
Add a loading spinner after clicking "View My Buildings" on the matching page.
Refs #776
> Issue #776 - View buildings spinner

- docs/source/data_model.rst
I changed the doc a bit and added a few sections trying to explain exactly what happened to the database and when when the user imports a record. I mostly left the existing text since it is basically correct at a high level. There were a few things that were incorrect due to changes we made so I fixed that.
So far this mainly looks at what happens to the database at each step when a user imports a record primarily focusing on the BuildingSnapshot table (since that is where most of the action is).  Also looks at what happens to the CanonicalBuilding table.
Also starts to explain some of the other relations like organizations and some of the logic in the Django model (data truncation when saving)
Ref #645
> 645 update data model docs

- seed/cleansing/models.py
- seed/cleansing/tests.py
This is a small cosmetic change to improve data cleansing output for Energy Score warnings/errors
Ref #583
> Rename `Energy Star Score` to `Energy Score` in data cleansing output

- seed/views/main.py
A regression introduced in #676  broke the unmatched filter on the matching page.
Fixed unmatched filter on matching page. Tests will be added when columns stuff is cleaned up in #800
Refs #799
> Issue #799 - Get unmatched view working on matching page.

- config/settings/common.py
Change the sessions to use signed cookies. Refs #751
> Issue #751 - Django cookie sessions

- seed/search.py
- seed/tests/test_views.py
- seed/utils/search.py
Adds ability to filter by excluding words.
Refs #492
> Issue #492 - Exclude filters

- config/settings/common.py
- seed/cleansing/models.py
- seed/data_importer/migrations/0002_auto_20160302_1142.py
- seed/data_importer/models.py
- seed/static/seed/js/controllers/building_list_controller.js
- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/js/services/cleansing_service.js
This pull request enables Django timezone support and also adds database timestamps to uploaded files.  This fixes #544.
This PR includes a database migration:
```bash
./manage.py migrate
```
> Issue #544 - Added Django timezone support

- .coveragerc
- seed/cleansing/tests.py
- seed/data_importer/models.py
- seed/tests/test_views.py
- seed/views/main.py
Add a bunch of python unit tests. Brings coverage from 72% to 78%. Removes some unused code.
Refs #790
> Issue #790 - Increase python unit test coverage

- seed/static/seed/js/controllers/mapping_controller.js
- seed/views/main.py
Fix a regression dealing with the mapping page column typeahead.
Refs #818
> Issue #818 - Better logic for mapping column typeahead & regression fix

- seed/static/seed/js/utilities/spinner.js
Fixes for the spinner utility to make it work more consistently. 
Refs #805
> Issue #805 - Spinner fixes

- seed/static/seed/js/controllers/building_detail_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/partials/building_energy_section.html
- seed/views/main.py
- Trim user input at front end
- Show energy type instead of cost in monthly energy data list
- Finer and monthly timeseries data, GreenButton request info are only requested when user goes to building's energy tab.
> Timeseries Updates

- seed/migrations/0014_auto_20160308_1106.py
- seed/models.py
- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/partials/mapping.html
- seed/static/seed/tests/mapping_controller.spec.js
- seed/utils/cache.py
- seed/views/main.py
Removes the unused schema model and some commented out code around it. Speeds up the first mapping step a bit too.
Refs #809
> Issue #809 - Remove Schema model

- seed/tests/test_account_views.py
- seed/tests/test_project_views.py
- seed/tests/test_views.py
- seed/views/projects.py
Gets python unit test coverage up to 81%
Refs #790
> Issue #790 - More python unit tests

- seed/static/seed/js/controllers/building_list_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/search_service.js
Save page number when navigating between building list and building detail views.
refs #836
> Issue #836 - Remember page number when navigating around building list.

- docs/source/developer_resources.rst
- docs/source/setup_osx.rst
- tox.ini
Adds documentation regarding which flake errors are ignored.
Refs #673
> add flake documentation

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Add template so that every pull request can provide similar information
Adds the template within the new .github folder
> add pull request template

- seed/landing/migrations/0004_auto_20160316_1102.py
- seed/landing/models.py
- seed/lib/superperms/orgs/models.py
- seed/static/seed/js/controllers/admin_controller.js
- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/services/organization_service.js
- seed/static/seed/partials/admin.html
- seed/tasks.py
- seed/templates/seed/_js_urls.html
- seed/tests/test_tasks.py
- seed/urls/main.py
- seed/views/main.py
Adds the ability to delete entire organizations via the admin panel.
refs #13
> Issue #13 - Delete organizations in admin panel

- seed/static/seed/partials/admin.html
Just change the text for the admin organization options headline.
Refs #859
> Issue #859 - Change admin orgs headline.

- seed/celery.py
There are several issues that are probably throwing errors in celery that we can't see.
Get Sentry working with celery.
> Celery logging for sentry

- seed/tasks.py
- seed/utils/cache.py
Progress bar for uploading and mapping wasn't displaying correct values, was causing false page changes when jobs weren't completely done.
Tweak the way progress cache is incremented and simplify the logic for chunking out progress. 
Refs #813
> Issue #813 - Progress bar fixes

- .travis.yml
We weren't caching pip correctly because we are using tox
caches the .tox folder for faster travis builds.
via travis.
None
> tox update

- seed/static/seed/js/seed.js
- seed/static/seed/js/services/building_service.js
- seed/tests/test_views.py
- seed/utils/buildings.py
- seed/views/accounts.py
- seed/views/main.py
"status" column on project buildings list was causing export to fail.
Remove status column on project buildings list since it is no longer used.
Export via project buildings list.
Refs #883
> Issue #883 - Project export fix

- .dockerignore
- Dockerfile
- bin/install_javascript_dependencies.sh
- bin/start_celery_docker.sh
- config/settings/local_untracked_docker.py
- requirements/base.txt
- requirements/test.txt
Docker broke somewhere along the way. You will need to rerun `pip install -r requirements/local.txt` as some of the dependencies were upgraded to support python 2.7.11.
Fixes the docker build
`docker-compose up`
> Docker update

- .github/CONTRIBUTING.md
- README.md
- docs/source/developer_resources.rst
- docs/source/setup_docker.rst
- docs/source/setup_osx.rst
readthedocs is changing domain from .org to .io.
Fixes links to readthedocs.
NA
#927 
NA
> 927 readthedocs

- seed/tests/test_views.py
- seed/views/main.py
Fix when newlines are in fields in mapping view.
Refs #925
> Issue #925 - Fix for newlines in mapping view.

- requirements/base.txt
- seed/managers/json.py
- seed/managers/tests/test_json_manager.py
- seed/search.py
#924 is hard to debug because of the custom json query stuff. 
This PR removes a lot of the custom json query stuff, as it was no longer necessary. The JsonField package we're using supports most of it.
Refs #924
> Issue #924 - Update json queries

- seed/static/seed/js/controllers/building_list_controller.js
Navigating from building list to detail and back was losing the chosen labels.
Fix keeping labels during navigation.
Refs #909
> Issue #909 - Keep filter by label during navigation

- config/settings/common.py
- config/template_context.py
- requirements/base.txt
Upgrade django compressor and remove an unused context processor method.
I ran the compress management command locally and it worked.
Refs #947
> Issue #947 - Upgrade django compressor

- seed/tasks.py
- seed/tests/test_views.py
Handle the condition where someone is trying to export zero buildings. This was just throwing an error before.
Refs #946
> Issue #946 - Handle exporting zero buildings

- .gitignore
- .travis.yml
- config/settings/test.py
- seed/fixtures/apitest.json
- seed/tests/api/seed_API_test.ini
- seed/tests/api/seed_API_test.ini.example
- seed/tests/api/seed_readingtools.py
- seed/tests/api/test_modules.py
- seed/tests/api/test_seed_host_api.py
- tox.ini
Fixes for the api test script. Reworked how the whole thing is set up. It now runs with the travis build. Now has option to runserver along with the test (for travis). Now has option for no input.
Refs #943
> Issue #943 - Fixes for api test

- config/settings/local_untracked.py.dist
Clean up local settings example. It had a ton of unnecessary stuff.
> Clean up local settings example

- seed/search.py
- seed/tests/test_views.py
- seed/utils/search.py
Handle date format from angular when filtering on date fields.
Refs #942
> Handle iso datetimes from angular on date filter.

- config/settings/travis.py
- tox.ini
> WIP test some tox changes

- seed/models.py
- seed/tests/test_models.py
Fix editing building detail fields.
Edit a building on the building detail page and go back to list view to see it has been saved.
Refs #966
> Issue #966 - Building detail edit

- seed/static/seed/js/services/simple_modal_service.js
I came across a javascript error that prevents deleting labels when looking into the code
Applies fix as per issue #976 
Navigate to the building label admin page and delete a label you have added.
ticket #976 #442 
No tests added.
Note there is an outstanding issue to add unit tests for simple-modal-service #442
> fixes #976

- seed/bluesky/management/commands/_localtools.py
- seed/bluesky/management/commands/create_m2m_relationships_organization.py
- seed/bluesky/management/commands/create_primarysecondary_taxlots.py
- seed/bluesky/management/commands/destroy_bluesky_data.py
- seed/bluesky/management/commands/manage_bluesky_data.py
- seed/bluesky/management/commands/migrate_organization.py
- seed/bluesky/views.py
This pull request fixes several migration issues from Philly and DC, adding primary/secondary tax lots in the migration, and combines all the bluesky migration commands into one manage_bluesky_data command.
Monkey testing 
Pivotal Tickets: #126361299, 126529883, 124001491
> Manually adding changes.

- seed/static/seed/js/controllers/property_detail_controller.js
- seed/static/seed/js/controllers/taxlot_detail_controller.js
Detail view should show changes to history after an update.
Adds code to refresh page after an update.
Once BE methods are in, test updating a real Property and TaxLot and see if table has new column to show new state in history.
Pivotal Tracker ID 128248441
n/a
> Dmcq fresh detail after update

- seed/functional/tests/test_browser.py
Fixes typos in functional tests
> fix typos in test

- seed/views/properties.py
History was not displaying correctly
bug fix for this
Make sure history shows up from properties and taxlots with multiple states, audit logs
> bug fix for buiding detail history views

- seed/static/seed/js/services/inventory_service.js
Came across a typo/wrong url when looking for something else
> fix incorect url

- api/urls.py
- api/views.py
- seed/data_importer/tests/test_data_import.py
- seed/models/properties.py
- seed/serializers/labels.py
- seed/views/datasets.py
- seed/views/main.py
- seed/views/organizations.py
- seed/views/projects.py
- seed/views/users.py
The auto-generated Swagger docs needed some cleanup.
Focused on docstring updates.  But in the case of complex body parameters and complex response types, I created small Serializers to allow Swagger to render nicely.  These serializers could be replaced later...possibly.
Just check the Swagger page endpoints and make sure the request/response types, and endpoint descriptions, all look nice.
None that I know of.
No.
> Clean up the Swagger docs

- seed/management/commands/migrate_labels.py
Updates label migration to reflect the change to labels, being moved from TaxLotView/PropertyView to TaxLot and Property objects.
Monkey testing
> Migrate label update

- api/urls.py
- api/views.py
- seed/data_importer/tasks.py
- seed/data_importer/tests/test_case_a.py
- seed/data_importer/tests/test_case_b.py
- seed/data_importer/tests/test_data_import.py
- seed/data_importer/tests/test_matching.py
- seed/models/__init__.py
- seed/models/joins.py
- seed/models/properties.py
- seed/models/tax_lots.py
- seed/pagination.py
- seed/views/datasets.py
- seed/views/main.py
- seed/views/organizations.py
- seed/views/projects.py
- seed/views/users.py
Add test case a and b in the unit tests. Tests c & d are still under development.
cleans up the testing for 2 of the 4 use cases for the new data model.
`./manage.py test`
N/A
N/A
> Add test cases

- seed/management/commands/manage_bluesky_data.py
- seed/management/commands/migrate_extradata_columns.py
Updates migration of columns to reflect new data model.
> Column migration bugfix

- seed/static/seed/js/services/search_service.js
Adds fix for #1035 backported from #1037 
test against steps in #1035 
#1035 
Neither of these are present in this branch, they are present in #1037. Adding them here would require backporting all the new Selenium Test work.
> Fix for 1035 backported from tallus-selenium-test-836

- seed/data_importer/tasks.py
- seed/data_importer/tests/test_case_a.py
- seed/data_importer/tests/test_equivalenceclass.py
- seed/data_importer/tests/test_mergeduplicaterows.py
- seed/data_importer/tests/test_robindemocase.py
- seed/mappings/mapper.py
- seed/models/properties.py
- seed/static/seed/js/controllers/inventory_detail_controller.js
- seed/static/seed/js/services/inventory_service.js
- seed/static/seed/partials/inventory_detail.html
- seed/views/properties.py
Allows you to press the `Edit` button on a property or tax lot detail page, modify the existing fields, and then save the changes
> Inventory Detail Save Changes

- seed/static/seed/js/services/project_service.js
@RDmitchell noted issue #1096 
Fixes the JS service to call the endpoint properly
Make sure the 404 doesn't show up anymore for that endpoint.  There are still a couple controller errors that pop up, not sure if they are unrelated or not yet.  @axelstudios ?  Maybe just my machine?
#132179901
The 404 from #1096 is gone, leaving only these controller issues ![image](https://cloud.githubusercontent.com/assets/849824/20080820/0e861e7a-a509-11e6-81a4-c63f9a43a297.png)
> Fixing 404 in Projects Count

- seed/lib/mappings/mapping_columns.py
- seed/lib/mappings/test_mapping_columns.py
If there list of mapping suggestions is 0, then an error was thrown when trying to assign a new mapping suggestions from a null list.
Checks if there are any more mapping suggestions.
Try to import KC file.
#1127
> No more mapping suggestions

- api/views.py
- docs/source/mapping.rst
- seed/static/seed/js/services/mapping_service.js
- seed/templates/seed/_js_urls.html
- seed/tests/test_views.py
- seed/urls/main.py
- seed/views/main.py
@nllong added a small worker function to get column mapping suggestions to allow it to work during the backend changes.  A new, viewset-based function was added and also called this worker function.  The original function was left in there and the front end was still hooked to it.
This PR moves the front end to call the new class-based "v2" function, also updating the docs mention of the function.
Verify that column mapping suggestions is still working as expected.
https://www.pivotaltracker.com/story/show/133876497
> Rewire column mapping suggestions

- seed/lib/mappings/data/pm-mapping.json
- seed/models/columns.py
PM mappings are wrong in some places
Fixes PM mappings.
Import PM file
#1151 
N/A
> fix pm mappings

- .travis.yml
- tox.ini
coveralls was broken
fix code coverage reports.
check coveralls
https://www.pivotaltracker.com/story/show/131468613
N/A
> 131468613 coveralls

- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/views/properties.py
property list did not show the tax lot address correctly.
fixes the display of the tax lot address in the property list.
import two files with addresses that can be merged. Make sure that the addresses look right.
#1164
> 1164 address line 1

- seed/views/properties.py
#1173 
Fixes the names of a couple of the fixed columns.
Monkey testing.
#1173
> fix display names of fields

- seed/views/properties.py
Column naming was not consistent 
Updates column naming
Look at inventory by taxlot and property.
#1173
> update column names

- seed/data_importer/tasks.py
- seed/data_importer/tests/test_demo_v2.py
Fix various edge cases for importing files.
Import files using existing organizations.
#1128 #1217
> Potential matching fix

- seed/data_importer/tasks.py
- seed/data_importer/tests/test_demo_v2.py
Matching changes (currently on develop) to handle IntegrityErrors
> Release hotfix (matching integrity)

- seed/lib/mappings/data/pm-mapping.json
More default mapping for PM files
Adds Energy Score and PM Parent Property ID
Upload PM file.
#1230
> new mappings

- seed/data_importer/models.py
- seed/data_importer/tasks.py
- seed/lib/mcm/mapper.py
- seed/lib/mcm/reader.py
- seed/lib/mcm/tests/test_reader.py
Headers in the file with leading and trailing spaces caused issues in the mapping. 
If a csv/xlsx file is uploaded, the headers will be trimmed to keep everything consistent.
Upload test files that have leading and trailing spaces in the headers and verify that the data are mapped correctly.
#1213
> trim spacing in headers

- api/urls.py
- seed/models/columns.py
- seed/static/seed/js/controllers/admin_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/column_mappings_service.js
- seed/static/seed/partials/admin.html
- seed/templates/seed/_scripts.html
- seed/views/columns.py
There was no way to access the column and column mappings easily via the API.
Adds list and retrieve for Column and ColumnMapping objects. Adds delete_all method to delete all methods for ColumnMappings.
Use swagger API.
> add get for columns and mappings. add endpoint for delete_all

- seed/static/seed/js/controllers/pairing_controller.js
- seed/static/seed/partials/pairing.html
More fixes for pairing page with drag and drop
> fix for pairing page, didn't like scope() syntax

- .travis.yml
- seed/data_importer/views.py
- seed/models/columns.py
There can be duplicate columns which cause issues.
If MultipleObjects are returned then it will remove the duplicate.
Monkey testing
#1310
> fix duplicates when querying columns

- seed/data_importer/views.py
- seed/migrations/0054_remove_same_column_in_mappings.py
- seed/models/columns.py
- seed/models/tax_lots.py
- seed/static/seed/js/controllers/mapping_controller.js
- seed/tests/test_columns.py
- seed/tests/test_views.py
- seed/utils/constants.py
- seed/views/columns.py
- seed/views/properties.py
the property/columns and taxlot/columns API method needed to be updated.
Added delete_all API for columns. Fixed API.
Monkey testing.
#1295
> 1295 importing twice

- seed/static/seed/tests/protractor-tests/miscellaneous.spec.js
- seed/static/seed/tests/protractor-tests/orgPages.spec.js
- seed/static/seed/tests/protractor-tests/propPages.spec.js
- seed/static/seed/tests/protractor-tests/taxlotPages.spec.js
> Fix develop tests

- seed/static/seed/partials/inventory_list.html
Added prominent inventory list clear filters button #1242
> Clear filters button

- .travis.yml
- seed/lib/mappings/mapping_columns.py
- seed/lib/mappings/test_mapping_columns.py
- seed/tasks.py
- seed/templates/seed/_js_urls.html
- seed/tests/test_delete.py
- seed/urls/main.py
- seed/views/main.py
Delete organization wasn't working when the inventory wasn't empty. 
Delete the organization's inventory before deleting an organization.
Load inventory in a new organization. Delete organization and make sure that it deletes the inventory.
N/A
> fix delete organization

- seed/serializers/properties.py
Measures were not being serialized in the bricr branch.
Change the representation to use the super method.
Monkey test
N/A
> use super method

- seed/data_importer/views.py
- seed/static/seed/partials/mapping.html
> Fixed missing mapping review grids

- requirements/base.txt
swagger wasn't loading on dev servers.
add doctutils.
deploy check on dev servers.
> need docutils installed to run swagger in production

- seed/data_importer/tests/test_views_matching.py
- seed/tests/test_properties_serializers.py
tests would fail randomly.
Forces the fake label method to create 2 unique labels.
watch travis over time.
N/A
> Fix nondeterministic test

- seed/static/seed/js/controllers/matching_detail_controller.js
- seed/static/seed/js/controllers/matching_list_controller.js
- seed/static/seed/js/services/matching_service.js
- seed/static/seed/partials/matching_list.html
Saves and loads the state of the visibility dropdown on the matching list view (Show All, Show Matched, Show Unmatched)
#1312
> Save state of matching list visibility dropdown - #1312

- seed/static/seed/js/controllers/inventory_list_controller.js
Filter By Label on the inventory list view previously showed all labels that had been applied to any record from any cycle.  Now, the only labels that appear in the dropdown are ones that can be found on records for the currently selected cycle.
Have records in more than one cycle.  Apply a label to records in one cycle that has not been used for the other cycles.  Change cycles to see that the label becomes available or removed in the label filter.
> Filter By Label By Cycle

- .travis.yml
- docker-compose.yml
- docker/seed-entrypoint.sh
- docker/travis_build_docker.sh
- seed/management/commands/create_test_user_json.py
Docker images were only be built for develop. 
This adds another branch and enables echoing out API keys to the command line (in json format).
travis
> Update docker tags

- seed/serializers/properties.py
- seed/views/properties.py
Couldn't save edits.
Fixes saving edits.
Manually edit a field in the inventory detail page.
N/A
> Saving Edits in Detailed Inventory View

- seed/static/seed/js/controllers/inventory_list_controller.js
Property Custom ID 1 wasn't showing up in tax lot inventory view.
Display custom id
Import data, go to tax lot inventory page, verify that you can see the custom id 1 from property.
#1329
> display custom_id_1 on taxlot from property

- CHANGELOG.md
- docker/travis_build_docker.sh
- docs/release_instructions.md
- docs/scripts/change_log.rb
- package.json
> Develop 2.2 changelog

- bin/backup_database.sh
backup script wasn't removing old dumps.
fixes the script to remove old .dump files (not .sql). Now keeps 45 days of backups.
N/A
N/A
N/A
> Fix backup script

- seed/landing/views.py
Password reset wasn't working after django 1.11 upgrade.
This is a temporary fix and simply removed the unused argument.
The correct way to fix this is to convert from function based views to classed based views per the [django documentation](https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.views.PasswordResetView)
Test if you can reset your password.
#1503 
Follow on ticket to address class based views - #1501
> fix password reset

- seed/static/seed/js/controllers/data_quality_modal_controller.js
- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/static/seed/partials/data_quality_modal.html
The organization ID was not being passed causing non-superusers from downloading the CSV.
Passes organization ID
As non superuser try to download the data quality results from inventory list.
#1363 
N/A
> Pass organization ID to DQ CSV download

- docs/translation.md
- seed/static/seed/locales/en_US.json
- seed/static/seed/locales/fr_CA.json
- seed/static/seed/partials/inventory_detail.html
Merge translation example into seed.
Adds merging example.
N/A
N/A
> Translation example

- seed/static/seed/js/controllers/data_upload_modal_controller.js
- seed/static/seed/partials/data_upload_modal.html
1. Go to add a new data file
1. Change the cycle away from the default
1. Import a PM report
1. Check that the selected cycle was used
#1532
> Fixed the selected cycle for PM imports

- requirements/base.txt
- requirements/local.txt
- requirements/test.txt
Update some dependencies
Updates dependencies
travis, dev installations
> upgrade some dependencies to the latest versions

- seed/static/seed/partials/mapping.html
Typo occurred during translation
Fixes the display error for the number of taxlot rows on the mapping review page
#1547
> Fixed the count for the imported number of mapped tax lots

- CHANGELOG.md
- package.json
Release 2.3.1 preparation. 
Release 2.3.1 preparation.
> changelog for 2.3.1 release

- .travis.yml
- tox.ini
Coveralls wasn't building on pull requests. Coveralls was out of state on develop.
Add coveralls token to repo. Remove old secure keys (for sauce labs).
N/A
N/A
> Coveralls Env Vars

- .gitignore
- docs/scripts/export_issues_to_csv.py
- docs/source/conf.py
Needed to download issues and store as CSV for prioritization.
Simple script to connect to github API and download the issues and save to CSV format.
N/A
N/A
N/A
> Add export issues script

- seed/data_importer/tasks.py
- seed/lib/mcm/mapper.py
- seed/models/columns.py
- seed/models/data_quality.py
- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/partials/mapping.html
- seed/utils/organizations.py
- seed/views/data_quality.py
With multiple parallel celery processes, there was a case where more than one process would see that the data quality rules needed to be populated and they would both attempt it causing an integrity error
> Fix race condition on creating DataQualityCheck objects

- seed/data_importer/tasks.py
- seed/models/data_quality.py
- seed/utils/organizations.py
- seed/views/data_quality.py
See sentry error in #1635 
Passes the data_quality checks by organization, not the ID.
Import any file, ensure that it does not hang. Try a non superuser account
#1634 #1635
> fix organization id

- seed/data_importer/tasks.py
- seed/models/data_quality.py
- seed/static/seed/js/controllers/data_quality_admin_controller.js
- seed/static/seed/partials/data_quality_admin.html
- seed/utils/organizations.py
- seed/views/data_quality.py
The data quality checks were returning a 500 when running in celery as non-eager mode.
Converts the do_checks call to pass in the organization_id. The organization object was trying to be converted to a string to persist to redis, which was not possible.
* Run celery in non always eager mode
* Select data from inventory page and run data quality checks.
* verify that the results return
* Fixes #1665
> Data Quality Checks Returned 500

- seed/data_importer/views.py
- seed/lib/mcm/cleaners.py
- seed/lib/mcm/mapper.py
Doing ESPM imports, an issue was found that was actually related to the data import cleaning process.  The Site EUI was missing after the mapping page was completed.  (The preview -- first 5 rows -- page showed the values properly)
1. Sanitizes the property notes field when converting from XML to CSV, cleaning newlines so that the csv looks nice.
2. A quick hack to get the EUI and other similar fields to import properly.
Import from ESPM, make sure EUI is imported all the way to the DB
#1707
> Fix csv import

- seed/data_importer/tasks.py
- seed/lib/mcm/cleaners.py
- seed/lib/mcm/mapper.py
Few fixes to fix specific issues uploading a file.
* Error out nicely when mapping fails. This is only on the backend, the frontend needs to be updated. The frontend will still show the mapping progress bar even though the progress check returned an error.
* Pass in if the field is extra_data when calling the clean value method. An extra data field will no longer be cleaned using the Pint cleaner.
Tests for #1498 
#1498
> Fix pint cleaner and mapping error

- .dockerignore
- bin/backup_database.sh
- deploy.sh
- docker-compose.local.yml
- docker/README.md
- docker/backup_database.sh
- docker/start_celery_docker.sh
SEED was not being deployed with Docker on the test, staging, and production servers. 
Update the containers, docker-compose files, and scripts for deploying with Docker and Docker Stack.
Test the deployment process.
N/A
> add deploy script for docker stack deploy

- seed/static/seed/js/controllers/inventory_map_controller.js
- seed/static/seed/partials/inventory_map.html
PR to review changes and merge to feature
> Map page handles cycles

- seed/models/properties.py
- seed/static/seed/partials/geocode_modal.html
- seed/tests/data/vcr_cassettes/geocode_same_record_twice.yaml
- seed/tests/test_utils_geocode.py
- seed/utils/geocode.py
PR to review changes to feature branch
> Latitude and Longitude fields are synced with long_lat GIS field

- .gitignore
- deploy.sh
- docker-compose.deploy.yml
- docker-compose.local.yml
- docker-compose.yml
- docker/README.md
- requirements/base.txt
The Open Efficiency Platform (OEP) is a 3rd party application developed to connect SEED to Salesforce. 
* Update deploy script to pull OEP containers (regardless if being used)
* Update documentation.
Note that if you want to use OEP, you will need to follow the instructions in the (OEP docker hub repo)[https://cloud.docker.com/u/seedplatform/repository/docker/seedplatform/oep/general]
The easiest way is to set up and deploy with SEED and Salesforce credentials.
#1782
> Open Efficiency Platform

- .dockerignore
- config/settings/common.py
- config/settings/docker.py
- config/settings/local_untracked.py.dist
- deploy.sh
- docker-compose.deploy.yml
- docker-compose.local.yml
- docker-compose.yml
- docs/source/linux.rst
- requirements/aws.txt
- requirements/base.txt
Docker was not able to send emails.
Adds SES configuration to the docker instances
Test on dev1 with your user email address. Make sure you get an email when resetting your password.
> SES in Docker

- requirements/base.txt
https://nvd.nist.gov/vuln/detail/CVE-2019-6975
> Updated Django dependency

- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/scss/style.scss
- seed/templates/seed/_header.html
- Upload buttons within dropdowns didn't have a background color on hover
- Added a warning line item background
> Style Tweaks

- deploy.sh
- docker-compose.yml
Email was not working with the OEP.
* Point to the newest version of the OEP docker container.
N/A
> Update to OEP Version 1.1

- seed/static/seed/tests/settings_controller.spec.js
PR to feature branch
This branch created to separately debug/run front end tests on TravisCI
> Meters org settings test fix

- docs/source/setup_osx.rst
PR into feature branch for review
> Meters timescale osx install

- seed/models/columns.py
> Column renaming hotfix

- deploy.sh
- docker-compose.yml
- docs/source/api.rst
- npm-shrinkwrap.json
- package.json
- seed/landing/models.py
- seed/models/data_quality.py
- seed/static/seed/js/controllers/developer_controller.js
- seed/static/seed/partials/developer.html
- seed/utils/api.py
Running data quality checks against existing data could appear to run indefinitely.
Fixes a bug when running data quality checks against an existing record with a label that doesn't violate a rule that has that same label assigned.  It would attempt to remove the label and fail due to the recent label refactor
@nllong It would be good to create a unit test and remove oep-city from the default deployment
Apply a rule to a record, then create a data quality rule with that same label that the record doesn't violate.  Run data quality checks and it should successfully remove the label.
> Data Quality Label Removal

- seed/static/seed/tests/mapping_controller.spec.js
PR into feature branch to troubleshoot FE tests
> Geocoding fields fe tests

- docs/source/mapping.rst
There were some previous questions and possible issues around the suggestions being built for column mappings during file import.
Add documentation for the column mapping process.
The documentation includes answers to many of the original questions in the issue mentioned below.
#94
> Update column mapping documentation

- seed/static/seed/partials/inventory_list.html
See issue linked below
Makes use of existing "filter check" logic to display filter button and record count using blue text.
Go to inventory page and use filters.
#1563 
See issue above
> Filter indicators on list page

- seed/building_sync/building_sync.py
- seed/building_sync/tests/data/buildingsync_ex01_measures.xml
- seed/building_sync/tests/data/buildingsync_ex01_measures_results.xml
- seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml
- seed/building_sync/tests/data/ex_1.xml
Added ubid @building level in building_sync.py as a required element for seed to import.
#1740
> Added ubid in building_sync.py for seed import

- seed/static/seed/tests/mapping_controller.spec.js
PR to review changes into feature branch
> 1759 mapping presets fe tests

- seed/data_importer/tasks.py
See the details in the related ticket
- Fixes the equivalence partitioner comparator to not compare mixed types
- Also cleans up some code in that task that was irritating me
See the details in the issue
#2031
> Fix equivalence partitioner comparator

- seed/static/seed/js/controllers/admin_controller.js
- seed/static/seed/partials/admin.html
Superusers could create new users without selecting an organization or creating a new one
Adds form validation to ensure that when creating a new user an existing or is selected, or a new org name is specified.  It also prevents the user from trying to select and existing and create a new org.
As a superuser attempt to create a new user without an org
#1024
> New users must have an associated org

- seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js
Makes Geocoding Order changes available in the Column Setting "Save Changes" preview
Make Geocoding Order changes and see them in the "Save Changes" preview.
#2059
> Geocoding order shows in column settings change preview

- .gitignore
- .travis.yml
- bin/apitest_start_server.sh
- config/settings/test.py
- config/settings/test_local_untracked.py
- config/settings/travis.py
- requirements/test.txt
- seed/tests/api/seed_readingtools.py
- seed/tests/api/test_modules.py
- seed/tests/api/test_seed_host_api.py
- tox.ini
There is an intermittent issue with Travis CI and out code that is causing the apitests to lose connection to the server.  The logging has been inadequate to determine what is going on.
* Clean up travis file 
* Add after_failure in travis file
* Clean up test.py settings to ensure logging to file happens
* Ensure that the apitest task uses celery in non-always eager mode
* report memory and list of python/celery processes (and pids)
* check results on CI
#2084
> Travis CI Logging

- docs/source/developer_resources.rst
adding best practices to developer resources readme
review developer_resources.rst
> adding best practices to dev resources

- seed/api/v2/urls.py
- seed/static/seed/js/controllers/export_report_modal_controller.js
- seed/static/seed/js/controllers/inventory_reports_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/inventory_reports_service.js
- seed/static/seed/partials/export_report_modal.html
- seed/static/seed/partials/inventory_reports.html
- seed/templates/seed/_scripts.html
- seed/tests/test_reports.py
- seed/tests/test_tax_lot_property.py
- seed/views/reports.py
See attached issue.
Creates a new button and modal for the exporting of property report data.
For code review, reviewer can go through the initial commits (before the merge develop commits) one by one in order to go through the changed files in a "logical" order.
To test manually via UI, export property report data and inspect resulting Excel file.
#2090
> 1760 export reports

- seed/static/seed/js/controllers/mapping_controller.js
Originally unable to return to mappings page from defaults
solves the undefined variable issue preventing the page from loading
Add data/import/map/pair and then return to the data mappings page
#2080
> Found an undefined variable bug

- requirements/base.txt
Reverts SEED-platform/seed#2107
> Revert "Bump django from 2.0.13 to 2.2.10 in /requirements"

- seed/static/seed/js/controllers/inventory_detail_controller.js
- seed/static/seed/partials/accounts.html
- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/scss/style.scss
modifying table capability in detail view 
Allows the user to pin  the first two columns in detail view
toggle the pin icon on the column header 
#2102
> 2102 freeze column

- .travis.yml
- config/settings/travis.py
Travis has become more strict and now force postgres on 5433 (not 5432)
Fixes travis's postgres port
N/A
N/A
> Travis now uses 5433 for postgres

- seed/static/seed/js/directives/sdResizable.js
Addressing column resizing based on window width
Allows the user to now resize column regardless of window width
Click and drag the column header to the desired length
Directly address #2127
> Added resize func with HEAVY help from Alex

- .travis.yml
- docker/travis_build_docker.sh
- seed/models/building_file.py
- seed/models/scenarios.py
- seed/static/seed/js/controllers/inventory_detail_meters_controller.js
- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/partials/inventory_detail_meters.html
- seed/tests/test_meter_views.py
- seed/tests/test_scenarios.py
- seed/utils/meters.py
- seed/views/meters.py
Reverts SEED-platform/seed#2130
> Revert "Chore/merge bricr dev"

- .gitignore
- CHANGELOG.md
- docs/source/migrations.rst
- package.json
change log and version update for 2.7.0
> Prepare release 2.7.0

- CHANGELOG.md
- deploy.sh
- docs/source/migrations.rst
- package.json
Prep the changelog and other details for the 2.7.1 release
> Prepare release 2.7.1

- deploy.sh
- docker-compose.local.yml
- docs/source/aws.rst
- docs/source/deployment.rst
- docs/source/docker.rst
See issue
* Updates deploy documentation
* Update `deploy.sh` to use docker-compose
* Inspect source code changes
* If ambitious, then try launching ./deploy.sh locally.
#2169
> Deploy docker compose

- .travis.yml
- seed/data_importer/models.py
- seed/data_importer/utils.py
- seed/lib/mcm/utils.py
- seed/management/commands/create_geojson_test_data.py
- seed/models/column_list_settings_columns.py
- seed/utils/api.py
- seed/utils/geocode.py
Python 3.7 does not work with SEED 
* Fixes the yield commands to rescue on StopIteration
* I've updated travis to Python 3.7
* To test locally:
* install a python 3.7 (I used 3.7.7) and pip install the dependencies
* Try to import the sample data 
* before the fix it would have stopped with the image that is in the issue #2216 
#2216
> support for python 3.7

- seed/api/v3/urls.py
- seed/views/v3/column_mapping_presets.py
- seed/views/v3/column_mapping_profiles.py
Test Column Mapping Profile endpoints on the Swagger page.
#2183
> 2183 api v3 column mapping profile

- seed/api/v3/urls.py
- seed/views/v3/geocode.py
- seed/views/v3/ubid.py
Test geocode and UBID endpoints on the Swagger page.
This PR address half of the listed endpoints in #2254
> 2254 api v3 geocode ubid

- seed/api/v3/urls.py
- seed/utils/api_schema.py
- seed/views/v3/notes.py
- seed/views/v3/properties.py
- seed/views/v3/property_scenarios.py
Moves and refactors v2.1 properties endpoints to v3
Test the endpoints mentioned in the issue within the v2.1 section on the swagger page.
#2250
> 2250 refactor/api v3 properties v21

- seed/serializers/columns.py
- seed/views/properties.py
- seed/views/taxlots.py
- seed/views/v3/building_files.py
On Swagger page load, it is successful, but there are multiple errors and warnings on the backend.
Fixes those errors and warnings.
Visit the Swagger page, see that the server doesn't output any errors. 
#2232
> 2232 swagger page errors

- seed/api/v3/urls.py
- seed/views/v3/gbr_properties.py
- seed/views/v3/green_assessment_properties.py
- seed/views/v3/green_assessment_urls.py
- seed/views/v3/green_assessments.py
- seed/views/v3/property_states.py
Copy over GBR-related endpoints from v2 to v3. Also breaks the ViewSets out into their own files.
(Spot) check the endpoints work.
Note that pagination is automatically applied to these views. In practice, users don't actually use this feature, and this feature causes a warning from some of the endpoints when executed on the Swagger page. The fix would normally be to set `pagination_class = None`, but that made those endpoints unusable.  A fix was not found for that in a reasonable amount of time. See the comments in the linked issue for more details.
#2263
> 2263 api v3 gbr

- seed/lib/superperms/orgs/decorators.py
- seed/lib/superperms/orgs/permissions.py
- seed/tests/test_permissions.py
- seed/views/v3/column_mapping_profiles.py
- seed/views/v3/data_quality_check_rules.py
- seed/views/v3/data_quality_checks.py
- seed/views/v3/datasets.py
- seed/views/v3/import_files.py
Small clean up items on misc API v3 endpoints.
Go to Swagger page and test endpoints.
> Api v3 cleanup rd 1

- seed/views/v3/properties.py
- seed/views/v3/property_scenarios.py
- seed/views/v3/taxlots.py
- seed/views/v3/uploads.py
- seed/views/v3/users.py
What's this PR do?
Small clean up items on misc API v3 endpoints.
How should this be manually tested?
Go to Swagger page and test endpoints.
> Api v3 cleanup rd 2

- docs/source/migrations.rst
- seed/migrations/0118_match_merge_link_all_orgs.py
See the related issue
Adds a try/catch to the migration with a link for manual instructions to fix the migration
Using a v2.6.1 db with at least one organization attempt to run migrations from the develop branch
#2295
> Migration Fix

- seed/models/data_quality.py
- seed/tests/test_data_quality_checks.py
DQ rules for extra_data fields that were "required" or "not_null" were not being tagged.
Fixes that issue and add testing to extra_data field rules and non-extra_data field rules.
Monkey test DQ rules
#2293 
The new tests contribute to #2208 .
> 2293 dq extra data bug

- CHANGELOG.md
- docs/source/migrations.rst
- package.json
> Prep 2.7.2 release

- seed/static/seed/js/services/cycle_service.js
- seed/tests/api/test_modules.py
- seed/tests/test_views.py
Part of the effort to convert the frontend to use API v3
See attached issue.
Verify checks in attached issue are warranted.
Also check the following:
**Inventory Tab** 
#2311
> 2311 apiv3 frontend cycles

- seed/static/seed/partials/inventory_detail.html
Fixes update with bsync uploads
Upload a property, on property details page try doing the "update with buildingsync" action.
> fix(partials): remove bad attr in inventory_detail

- seed/building_sync/tests/test_buildingsync_views.py
- seed/tests/api/test_modules.py
Efforts have been made to transition tests and frontend code to use API v3.
Last minute clean up for the above-mentioned effort.
Nothing to test manually; the Travis tests should be enough.
> Update misc view tests to use API v3 instead of v2

- CHANGELOG.md
- docs/source/migrations.rst
- package.json
prepare release.
* Update changelog, migrations, and package.json for release.
n/a
n/a
> bump version

- docker-compose.dev.yml
Fixes the docker config so the web volume can find all necessary libraries.
> fix(docker): fixed a web volume setting

- seed/views/v3/column_mapping_profiles.py
addresses #2418 
Adds HTML entities for text formatting
view the api/v3/column_mapping_profile endpoint
#2418
> style: added HTML entities for asterisks in swagger

- docker-compose.build.yml
- docker-compose.yml
Version of OEP was dated.
Upgrade to the latest version of OEP.
n/a
#2461
> Upgrade OEP Version 1.6

- CHANGELOG.md
> doc: add changelog entry for 2.7.5

- .github/workflows/ci.yml
> refactor(workflows): check if coveralls env var set

- CHANGELOG.md
- docs/scripts/change_log.py
- docs/source/developer_resources.rst
- docs/source/migrations.rst
- package.json
prep for next release
* bumps version
* add in the changelog items
* small fixes to the change_log script in order to allow reading "Include Before Closure" label".
n/a
n/a
> Prep release 2.9.0

- seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
- seed/static/seed/partials/inventory_detail_analyses_modal.html
related to the SEED analyses work
provides config vars for model choice
open the analysis modal and select a model type to run.  
#2533
> 2533 feat/modify analyses payload config

- charts/seed/templates/bsyncr-deployment.yaml
- charts/seed/templates/bsyncr-service.yaml
- charts/seed/templates/web-celery-deployment.yaml
- charts/seed/templates/web-deployment.yaml
Deployment chartwork 
adds the sentry and bsyncr env variables for the web pod.
> adding bsyncr and sentry env varibales and charts

- seed/models/properties.py
- seed/static/seed/partials/dataset_detail.html
- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/scss/style.scss
- seed/views/v3/media.py
> refactor: add download links for uploaded files

- config/settings/common.py
- seed/landing/templates/landing/home.html
- seed/landing/templates/landing/login.html
- seed/landing/urls.py
- seed/landing/views.py
We needed a way to toggle self-registration for deployments
creates an env variable to be set for self registration capability
add `INCLUDE_ACCT_REG` to local_untracked and set to False.  The create account button should not show on the FE.  
#2600
> feat: add self registration env toggle for deployments

- seed/landing/views.py
> fix: locals() picks up context variables

- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/static/seed/scss/style.scss
see original ticket
hides scrollbars on the label list view
see original ticket
https://github.com/SEED-platform/seed/issues/1643
> fix: scrollbars on label list are hidden

- seed/analysis_pipelines/better.py
Hotfix for new BETTER endpoint
> fix: endpoint

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- config/settings/docker.py
ClearlyEnergy integrated PostOffice into SEED.
- uses EMAIL_BACKEND for POST_OFFICE configuration instead of logging emails to console.
After merge into develop, roll the web and celery pods, then send an email and verify it is sent properly
#2728
> refactor(config): docker POST_OFFICE to use EMAIL_BACKEND

- seed/analysis_pipelines/better.py
SEED is improving integration with BETTER
Requires property type in SEED to match those used by BETTER/PM rather than those used by BEDES/BSync
Upload the example file (see below). Map all required fields to SEED fields (City, State, Postal Code, Property Type, PM ID, ...)
Import meters from same file.
You should be able to create a BETTER analysis, and see that the "Building Type" in the BETTER html file is K-12
Closes #2752 
[PM_BETTER_INPUT.xlsx](https://github.com/SEED-platform/seed/files/6857341/PM_BETTER_INPUT.xlsx)
> refactor(better): map from ESPM property types to BSync types

- seed/analysis_pipelines/better.py
BETTER integration improvements
Adds address to BuildingSync file. 
View the bsync input file and optional upload to BETTER building create endpoint via bsync content
#2764
> fix: add address line 1 to bsync file to send to BETTER

- seed/analysis_pipelines/better.py
- seed/tests/test_analysis_pipelines.py
Updates a few error strings to be more user friendly.
None should really be needed, no functionality was changed.
https://github.com/SEED-platform/seed/pull/2771
> refactor: updated a few error strings

- seed/analysis_pipelines/better/buildingsync.py
BETTER integration todo's
Ensures the gross floor area units are sqft and converts values accordingly.
confirm all better analysis input files are using sqft even when SEED has meters squared values. 
#2786
> 2786 fix/sqft encoding

- seed/static/seed/js/controllers/analysis_run_controller.js
- seed/static/seed/partials/analysis_runs.html
- seed/views/v3/analysis_views.py
adds a link back to the original property on the analysis run page
https://github.com/SEED-platform/seed/issues/2842
> feat: added link to analysis run page back to original property

- seed/analysis_pipelines/better/pipeline.py
- seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
- seed/static/seed/partials/analyses.html
- seed/static/seed/partials/analysis_card.html
- seed/static/seed/partials/analysis_details.html
- seed/static/seed/partials/inventory_detail_analyses_modal.html
- seed/tests/test_analysis_pipelines.py
Removes nested config options and fixes a broken key that BETTER required.
Run a better analysis and ensure the config looks correct on the property detail page (see original ticket).
https://github.com/SEED-platform/seed/issues/2865
> fix: removed nested config and changed broken min_model_r_squared key

- seed/analysis_pipelines/better/buildingsync.py
- seed/tests/test_analysis_pipelines.py
See issue
Try to run a BETTER analysis. It should work.
#2908
> refactor: use bsync v2.3 for BETTER analysis

- charts/seed/templates/db-postgres-deployment.yaml
- charts/seed/templates/db-postgres-service.yaml
- charts/seed/templates/db-redis-deployment.yaml
- charts/seed/templates/web-celery-deployment.yaml
- charts/seed/templates/web-deployment.yaml
- charts/seed/templates/web-service.yaml
- config/settings/common.py
- config/settings/dev.py
- config/settings/docker_dev.py
- docker/nginx-seed.conf
- seed/analysis_pipelines/better/client.py
> Expose better URL as a config setting

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> build: prep for 2.12.0 release

- seed/building_sync/building_sync.py
- seed/building_sync/schemas/BuildingSync_v2_2_0.xsd
- seed/building_sync/schemas/BuildingSync_v2_3_0.xsd
- seed/building_sync/schemas/BuildingSync_v2_4_0.xsd
- seed/building_sync/validation_client.py
- seed/tests/test_analysis_pipelines.py
Adds support for BuildingSync v2.4.0
Upload a 2.4.0 buildingsync xml and then try exporting it as such.
https://github.com/SEED-platform/seed/issues/2938
> feature: bumped BuildingSync version up to 2.4.0

- CHANGELOG.md
- docs/scripts/change_log.py
- npm-shrinkwrap.json
- package.json
- update package.json and changelog for 2.12.2 release
#2981
> Chore/prep 2.12.2

- seed/data_importer/tasks.py
see ticket
Updates the text in one upload step.
see ticket
https://github.com/SEED-platform/seed/issues/2958
> refactor: updated text

- CHANGELOG.md
- docs/scripts/change_log.py
- npm-shrinkwrap.json
- package.json
> update package and changelog for 2.12.3

- seed/static/seed/js/controllers/data_upload_modal_controller.js
- seed/static/seed/partials/data_upload_modal.html
see ticket
adds a button allowing you to download a CSV of imported file issues
import a file with issues
https://github.com/SEED-platform/seed/issues/2960
Single file import issues and downloaded CSV:
Single file match issues and downloaded CSV:
Multiple files:
> feature: added an export csv button for import issues

- seed/static/seed/js/controllers/delete_column_modal_controller.js
- seed/static/seed/partials/delete_column_modal.html
- seed/tasks.py
Authorized organization users have the ability to delete extra "PropertyState" or "TaxLotState" columns from the organization. If there are only a few "-States" then the process is quite quick. As more "-States" are added to the DB the column deleting process can become so time-consuming that it causes the webserver to timeout and 'harakiri' or kill itself. 
The general process is to query the database for all the "-States" that are both in the organization and have that specific column. Then as the columns are deleted the progress bar is updated showing `results deleted / total results` and the estimated time remaining. Both of these bits of data use the total number of results returned by the query. The original query is "lazy" and won't be evaluated until called. Asking for the length …
> 3018 Delete Column Timeout Refactor

- CHANGELOG.md
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> Prepare 2.13 release

- seed/utils/api.py
> Replace deprecated function request.is ajax

- README.md
- bin/apitest_start_server.sh
- bin/protractor_start_server.sh
- bin/start-seed.sh
- bin/start_celery.sh
- docker/start_celery_docker.sh
- docs/source/aws.rst
- docs/source/linux.rst
- docs/source/setup_osx.rst
- requirements/base.txt
> upgrade: celery 5.2.2 and tasks per child

- seed/static/seed/js/controllers/inventory_list_beta_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/inventory_service.js
- seed/utils/inventory_filter.py
See tickets.
Adds the ability to filter on labels with the new paginated beta inventory.
Add and remove labels on various properties, noting the label logic.
https://github.com/SEED-platform/seed/issues/3044
https://github.com/SEED-platform/seed/issues/3049
> Feat 3044/filter labels serverside

- seed/analysis_pipelines/better/pipeline.py
quick update to PR https://github.com/SEED-platform/seed/pull/3171
minor typo fix
n/a
https://github.com/SEED-platform/seed/issues/2843
> fix: minor text change

- requirements/test.txt
Sphinx needed to be updated.  See https://github.com/sphinx-doc/sphinx/issues/10291
> new sphinx version

- seed/lib/merging/merging.py
- seed/lib/merging/tests/test_merging.py
- seed/static/seed/partials/column_settings.html
- seed/views/v3/analyses.py
see ticket
Updates "recognize_null" to not affect imports where a column is missing.
- Pick a field (ie: energy_star).
- turn "recognize_null" OFF for this field
- import a file with the field present and non-empty, note it's presence on the property
- import another file with the field missing completely, note the value on the property doesn't change
- import another file with the field present and empty, note the property value still doesn't change
- turn "recognize_null" ON for this field
- import a file with the field present and non-empty, note it's presence on the property
- import another file with the field missing completely, note the value on the property doesn't change
- import another file with the field present and empty, note the property value finally changes …
> 3163 fix/differentiate null and missing

- seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
- seed/static/seed/partials/inventory_detail_sensors.html
Add ability to filter readings by DataLogger and sensor type
> Add sensor readings filter

- .pre-commit-config.yaml
- seed/analysis_pipelines/pipeline.py
- seed/decorators.py
- seed/lib/mcm/reader.py
- seed/lib/superperms/orgs/exceptions.py
- seed/utils/api.py
- seed/utils/geocode.py
- seed/utils/viewsets.py
- tox.ini
No longer need to have `pass` defined in methods.
> Upgrade autoflake

- seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
- seed/static/seed/partials/inventory_detail_sensors.html
see ticket 
https://github.com/SEED-platform/seed/issues/3281
> Change datalogger export

- seed/analysis_pipelines/better/pipeline.py
Adds the BETTER Run ID field
Run a better analysis and view results on property list and detail view
Fixes #2868
> BETTER - Add Run ID to fields in Property List and Detail view

- config/settings/common.py
- config/settings/docker.py
- config/settings/local_untracked.py.dist
- config/urls.py
- docker-compose.local.yml
- docker-compose.yml
- docs/source/deployment.rst
- docs/source/developer_resources.rst
- requirements/base.txt
- seed/celery.py
- seed/landing/views.py
- seed/static/seed/js/services/flippers.js
- seed/templates/seed/base.html
- seed/views/main.py
- vendors/package-lock.json
- vendors/package.json
See issue #3382 
* Replace `raven` package with `sentry-sdk`
* Fix the contexts of the login pages. There are some remaining render contexts that need updated but only affect when SEED launches (see #3385)
* Remove `raven-js`. A new ticket was created to add in JS error logging via #3383
Unit tests should cover the basic. Logging in is the most likely issue.
#3382
> update sentry to use sentry-sdk

- seed/search.py
see ticket
enables sorting and filtering on extra data columns with a space in it's name
Sort on an extra data field with a space in it's name.
https://github.com/SEED-platform/seed/issues/3401
> fix: remove offending characters before making annotation alias

- .github/workflows/ci.yml
- CHANGELOG.md
- docker-compose.dev.yml
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> bump version and generate changelog

- seed/static/seed/js/controllers/inventory_settings_controller.js
- seed/static/seed/js/controllers/settings_profile_modal_controller.js
See ticket.
Fixes creating new column list profiles.
Try to make a new column list profile.
https://github.com/SEED-platform/seed/issues/3411
> fix: pass in expected lists

- seed/search.py
- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/utils/inventory_filter.py
See ticket.
disables sorting and filtereing on related columns
see screenshot
https://github.com/SEED-platform/seed/issues/3426
> 3426 fix/cross inventory filter

- seed/static/seed/partials/inventory_nav.html
just renames Summary to Summary (Beta)
https://github.com/SEED-platform/seed/issues/3444
> Rename summary tab to Summary (Beta)

- seed/data_importer/meters_parser.py
Meter imports were failing.
Fixes meter imports via "Upload Portfolio Manager Meter Usage"
https://github.com/SEED-platform/seed/issues/3484
> fix the data type operations on strings for meters

- seed/static/seed/js/controllers/data_view_controller.js
- seed/static/seed/partials/data_view.html
- seed/tests/test_data_view_views.py
Updates to the data view custom reports page
sorts cycles in the table view and data view by cycle start vs id so they show up chronologically.  Adds a legend title to show solid lines are associated with the left axis and dashed lines are associated with the right axis.  
#3493
> 3493 data view format and usability improvements

- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/partials/mapping.html
- seed/static/seed/scss/style.scss
> Enable ability to not map a column in SEED

- seed/static/seed/js/controllers/insights_property_controller.js
Resolves weird graph behaviors
Fixes #3531
> Fix null x axis

- seed/static/seed/partials/accounts_nav.html
- seed/static/seed/partials/insights_nav.html
- seed/static/seed/partials/inventory_nav.html
Adds html comments so that whitespace doesn't create gaps between links
#3532
Before:
> 3532 Fixed nav gaps

- seed/static/seed/js/controllers/program_setup_controller.js
- seed/static/seed/partials/program_setup.html
save changes on program metric didnt notify user
adds notification and hyperlink
save a program metric and follow hyperlink
#3528
> 3528 UI improvements

- seed/static/seed/js/controllers/data_view_controller.js
Custom reports table not updating on save
forces a refresh after save changes to update graph
change filter group on custom reports page and then clicks save 
#3534
> force utility spinner and refresh to update chart

- seed/static/seed/js/controllers/program_setup_controller.js
- seed/static/seed/partials/program_setup.html
program metric page save button always enabled - confusing to user
disables buttons until changes are made to any or all fields
use the program metrics page 
#3529
> 3529 modify save

- CHANGELOG.md
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> update changelog/versions for 2.16.0-beta release

- seed/static/seed/js/controllers/inventory_list_controller.js
>  Switch to created filter group after creation

- seed/static/seed/partials/insights_program.html
- seed/static/seed/partials/insights_property.html
> Style expot buttons as in mockups

- .github/workflows/stale.yml
> exempt all milestones

- seed/static/seed/js/controllers/data_view_controller.js
https://github.com/SEED-platform/seed/issues/3490
does what is says on the tin
> Toggle cycles for cutom data view

- seed/static/seed/js/controllers/data_view_controller.js
https://github.com/SEED-platform/seed/issues/3552
> Use the same color for each axis per filter group

- seed/analysis_pipelines/better/pipeline.py
- seed/templates/seed/_sidebar.html
closes #3331  and addresses bug in sidebar.
> 3331 better results

- seed/static/seed/partials/analysis_run.html
demo hotfix
removes phantom copy pasta code from somewhere
run an analyis
> remove unused closing tag and something else

- seed/views/v3/portfolio_manager.py
> Output proper error message

- seed/static/seed/js/controllers/inventory_list_controller.js
[#3586](https://github.com/SEED-platform/seed/issues/3586)
> Apply label to only selected

- seed/static/seed/js/controllers/inventory_detail_meters_controller.js
- seed/static/seed/js/controllers/meter_deletion_modal_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/meter_service.js
- seed/static/seed/partials/inventory_detail_meters.html
- seed/static/seed/partials/meter_deletion_modal.html
- seed/templates/seed/_scripts.html
> Add delete meters UI

- seed/static/seed/js/controllers/data_view_controller.js
https://github.com/SEED-platform/seed/issues/3665
> Sort legend on custom reports

- seed/models/compliance_metrics.py
Started doing this [ticket](https://github.com/orgs/SEED-platform/projects/3/views/1?filterQuery=assignee%3Ahaneslinger), realized it was already done [here](https://github.com/SEED-platform/seed/commit/cadf06379dba6304cfc1f9239f45a86a63e4be05), but had broken it (woops), this fixes it.
> Fix tooltip in insights legend

- seed/lib/mcm/reader.py
When importing `.csv` files that have many spaces, the Python Sniffer can interpret the delimiter as a space, which causes the headers to be space-delimited instead of comma-delimited. This happen with only a large amount of rows like the ones below
```csv
id, address, a, b, c, square footage, d, total area
1,15013 Denver West Parkway,,1,," 10,000.00 ",," 10,500.00 "
2,15014 Denver West Parkway,,1,," 15,000.00 ",," 20,500.00 "
3,15015 Denver West Parkway,,1,," 20,000.00 ",," 50,500.00 "
4,15016 Denver West Parkway,,1,," 30,000.00 ",," 100,500.00 "
...
```
* Since it MCM parser is expecting CSV files, then force the format to be CSV if the Sniffer detects something otherwise.
* Create a long file (1000 rows) with the example above and verify it loads
#3675
> Support import of a csv file that has lots of spaces

- seed/static/seed/js/controllers/data_view_controller.js
- seed/static/seed/js/controllers/insights_program_controller.js
- seed/static/seed/js/controllers/insights_property_controller.js
- seed/utils/properties.py
Not perfect but pretty good.
[#3683](https://github.com/SEED-platform/seed/issues/3683)
> Make sure the left and right axis have the same range

- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> bump release versions

- seed/static/seed/js/controllers/insights_property_controller.js
https://github.com/SEED-platform/seed/issues/3605
before
after
> Fix stacked property points

- seed/utils/properties.py
[#3696](https://github.com/SEED-platform/seed/issues/3696)
> Fix filter group with extra column work on revised programs

- seed/static/seed/js/controllers/column_settings_controller.js
- seed/static/seed/js/controllers/create_column_modal_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/columns_service.js
- seed/static/seed/partials/column_settings.html
- seed/static/seed/partials/create_column_modal.html
- seed/templates/seed/_scripts.html
- seed/tests/test_column_views.py
- seed/views/v3/columns.py
https://github.com/SEED-platform/seed/issues/1758
not quite sure why it looks ugly.
> Allow users to create columns

- seed/utils/search.py
Filter on both "" and null values. 
- pick a column
- ensure the column has a full, null and "" value
- test the "" and !"" filters. 
[#3600](https://github.com/SEED-platform/seed/issues/3600)
> Fix filter on nulls and empty strings

- seed/static/seed/js/services/meters_service.js
> fix meter service route for units in organization settings

- seed/static/seed/js/controllers/data_view_controller.js
idk why chrome doesn't like `>` but 🤷 
https://github.com/SEED-platform/seed/issues/3665
> Fix custom report legend sort for chrome

- seed/migrations/0170_column_derived_column.py
- seed/models/derived_columns.py
- seed/serializers/derived_columns.py
- seed/static/seed/js/controllers/derived_columns_editor_controller.js
- seed/static/seed/partials/derived_columns_editor.html
- seed/test_helpers/fake.py
- seed/tests/test_derived_columns.py
* See the original issue from @ebeers-png #3439 
* This update makes us that *maybe* forcing column names to be unique via a database constraint would be a good idea. Uniqueness constraint would be a combination of `org`, `table_name`, and `column_name`
* updates the migration to check if the creation of the column from the derived column will result in a name conflict
* adds in the `is_extra_data` to the column creations per the original issue's suggestion
Testing is a bit complicated since most databases have probably already run this migration. I've documented my testing in case you don't want to test this workflow.
* Checkout SEED to a version before the `0170` migration existed (I used sha `d43fdfc2e`)
* In a clean database since you went back to a pretty old commit, import some data …
> Update derived column migration to prevent conflicting column names and prevent duplicate column names

- CHANGELOG.md
- bin/drop_create_db.sh
- docs/source/developer_resources.rst
- docs/source/setup_osx.rst
- seed/docs/faq/industry involvement/plugins.md
- seed/tests/api/test_seed_host_api.py
remove references to server urls that should be more generic.
> remove references to prod server, as needed

- docs/source/help.rst
Just cleaning up the language on the help page.
No testing needed
> Update help text

- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/static/seed/js/filters/tolerantNumber.js
- seed/static/seed/js/seed.js
- seed/templates/seed/_scripts.html
- seed/tests/test_search.py
- seed/utils/search.py
https://github.com/SEED-platform/seed/issues/3759#event-8314373744
> Fix filtering on "" and !"" for all data types

- .github/workflows/pr-labels.yml
- CHANGELOG.md
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> Prep release 2.17.1

- seed/models/data_views.py
[500 error in Custom Reports for specific case#3750](https://github.com/SEED-platform/seed/issues/3750)
> Fix 500 on data view evaluate when extra data is not present

- seed/tests/test_column_views.py
- seed/views/v3/columns.py
> Remove state population in create column

- seed/api/v3/urls.py
- seed/serializers/properties.py
- seed/serializers/taxlots.py
- seed/static/seed/js/controllers/inventory_detail_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/inventory_service.js
- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/tests/inventory_detail_controller.spec.js
- seed/static/seed/tests/property_detail_controller.spec.js
- seed/static/seed/tests/taxlot_detail_controller.spec.js
- seed/views/v3/property_views.py
- seed/views/v3/taxlot_views.py
> Allow switching cycles in inventory detail page

- CHANGELOG.md
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
- requirements/base.txt
* bump version of Django to include latest security release
* prepare Patch with small changes for logging.
> Update Django to 3.2.17 and bump SEED to 2.17.2

- docs/scripts/export_issues_to_csv.py
- mypy.ini
- requirements/test.txt
- seed/models/derived_columns.py
- tox.ini
for some reason mypy was being more stringent on the `salesforce-integration` branch. I updated mypy to 1.0 since it was just released and updated some config options.
> Update mypy to version 1.0

- CHANGELOG.md
- docs/source/migrations.rst
- npm-shrinkwrap.json
- package.json
> Prep release 2.17.3

- docker/nginx-seed.conf
Address security vulnerabilities in headers. 
This is a patch on top of #3866
> Update nginx security

- seed/static/seed/js/controllers/data_view_controller.js
- seed/static/seed/partials/data_view.html
On Custom Reports page, click `New Custom Report` then click the X to delete
https://github.com/SEED-platform/seed/issues/3909
> Fix deletion of new custom report

- .github/workflows/ci.yml
Moves `SF_DOMAIN` from secrets to vars
If the CI passes (and test names are unobscured) it's good to go
#3929
> Fix GitHub Actions Masking

- seed/static/seed/partials/data_view.html
Looks like a big change, but I just added a single div and indented the rest!
#3910
> Fix custom reports download button

- seed/serializers/compliance_metrics.py
- seed/tests/test_compliance_metrics_views.py
> Make test_compliance_metric_retrieve_endpoint deterministic

- seed/static/seed/js/controllers/data_view_controller.js
- seed/static/seed/partials/data_view.html
https://github.com/SEED-platform/seed/issues/3923
> Fix custom report creation reload

- CHANGELOG.md
- docs/source/migrations.rst
- package-lock.json
- package.json
Bump version and udpate changelog for release.
> Bump version and update changelog

- seed/data_importer/match.py
- seed/lib/superperms/orgs/migrations/0025_auto_20230413_1250.py
- seed/lib/superperms/orgs/models.py
- seed/lib/superperms/tests/test_organization_access_levels.py
- seed/models/properties.py
- seed/tests/test_organization_access_levels.py
> Import properties access levels

- seed/static/seed/js/controllers/insights_program_controller.js
> Add percentages to program overview

- seed/tests/test_reports.py
- seed/views/v3/organizations.py
see ticket
https://github.com/SEED-platform/seed/issues/3869
ate)
> Add matching criteria to report export

- seed/lib/superperms/orgs/decorators.py
- seed/tests/test_property_views.py
- seed/views/v3/data_logger.py
> Add Permisions for DataLoggerViewSet

- seed/tests/test_meter_views.py
- seed/tests/test_property_views.py
- seed/views/v3/meters.py
> Add AH Permissions to MeterViewSet

- seed/tests/test_scenarios.py
- seed/views/v3/property_scenarios.py
> Add AH Permissions to Scenarios

- seed/lib/superperms/orgs/decorators.py
- seed/tests/test_cycles.py
- seed/views/v3/cycles.py
> Add permissions to CycleViewSet

- seed/tests/test_column_views.py
- seed/views/v3/columns.py
> Add Permissions to ColumnViewSet

- seed/models/data_views.py
- seed/tests/test_data_view_views.py
- seed/views/v3/data_views.py
> Add permissions to DataViewViewSet

- seed/static/seed/js/controllers/menu_controller.js
- seed/static/seed/js/controllers/new_member_modal_controller.js
- seed/static/seed/partials/new_member_modal.html
- seed/templates/seed/_header.html
- seed/tests/test_account_views.py
- seed/views/main.py
very small tweaks:
1. fixed a few typos
2. fixed the access level appearing in top right of app
3. fixed the ALI dropdown in add new member (it was not populating correctly with changes to the access level dropdown above it)
> Ah bug fixes

- seed/lib/superperms/orgs/models.py
- seed/models/columns.py
- seed/tests/test_columns.py
- seed/tests/test_organization_access_levels.py
- seed/utils/organizations.py
- seed/views/v3/access_levels.py
> Add aln contraints

- seed/tests/test_derived_columns.py
- seed/views/v3/derived_columns.py
> Add permissions to DerivedColumnViewSet

- seed/lib/superperms/orgs/models.py
> Fix ali rename

- seed/tests/test_column_mapping_profiles_views.py
- seed/views/v3/column_mapping_profiles.py
> Add permissions to ColumnMappingProfileViewSet

- .cspell/custom-dictionary-workspace.txt
- .gitignore
- seed/lib/xml_mapping/mapper.py
- seed/tests/test_portfoliomanager.py
- seed/views/v3/analyses.py
- seed/views/v3/portfolio_manager.py
> Add ESPM download for single property (via API)

- seed/tests/test_meter_views.py
> Add permissions to MeterReadingViewSet

- seed/lib/superperms/orgs/decorators.py
- seed/tests/test_views.py
- seed/views/v3/datasets.py
> Add permissions to datasetviewset

- seed/static/seed/js/controllers/analysis_run_controller.js
- seed/static/seed/partials/analysis_runs.html
> Fix display name

- seed/lib/superperms/orgs/models.py
- seed/models/columns.py
- seed/tests/test_column_views.py
- seed/tests/test_organization_access_levels.py
- seed/views/v3/columns.py
> Add access level name/ column display name constraints

- seed/tests/test_green_assessments.py
- seed/views/v3/green_assessment_properties.py
- seed/views/v3/green_assessment_urls.py
- seed/views/v3/green_assessments.py
> Ah permissions/green assessments view sets

- seed/tests/test_postoffice.py
- seed/views/v3/postoffice.py
> Add permissions to postofficeviewset

- seed/views/v3/salesforce_mappings.py
> Ah permissions/salesforce

- seed/tests/test_tax_lot_property.py
- seed/views/v3/tax_lot_properties.py
> Add permissions to Taxlot Properties

- seed/tests/test_geocode_views.py
- seed/views/v3/geocode.py
> Add permissions to GeocodeViewSet

- seed/tests/test_events.py
- seed/tests/test_property_views.py
- seed/views/v3/events.py
- seed/views/v3/properties.py
> Add more Permissions

- seed/tests/test_labels_api_views.py
- seed/views/v3/label_inventories.py
> Add permissions to LabelInventoryViewSet

- .github/workflows/publish.yml
Need to build the develop AH containers for deployment
* Add the AH/develop branch to the list of branches to publish
* Tag and push to docker hub as develop-ah
* After merging this down, this should tag should auto update: https://hub.docker.com/layers/seedplatform/seed/develop-ah/images/sha256-3ad98ac50b6265a4b1011da99678916a8092bb59d01a753fbedcf885013e6dd1?context=repo
n/a
> Build docker container for accountability branch

- seed/data_importer/meters_parser.py
Handles the corner case where timezone-unaware meter timestamps can exist twice in a year, e.g. during the hour when daylight savings "falls back" to standard time.
#4286
> Handle ambiguous timestamps

- seed/data_importer/meters_parser.py
- seed/data_importer/tests/test_meters_parser.py
- Handles the corner case where timezone-unaware meter timestamps cannot exist, e.g. during the hour when daylight savings "springs forward" to dst.
- This PR also adds tests for the ambiguous and nonexistent scenarios.
#4293
> Handle nonexistent timestamps

- seed/static/seed/js/controllers/organization_access_level_tree_controller.js
- seed/templates/seed/_header.html
Remove the following from + Menu for low-level users that do not have access to them:
- Access Level Tree
- Program Setup
- Derived Columns
- Email Templates
before:
after:
> Remove unauthorized items from + menu for lower-level users

- docs/source/developer_resources.rst
Updates the developer resources documentation and release process based on current practices
> Updated developer resources documentation

- seed/lib/superperms/orgs/decorators.py
- seed/tests/test_portfoliomanager.py
- seed/views/v3/uploads.py
> Permission UploadViewSet

- seed/tests/test_taxlot_views_viewset.py
- seed/views/v3/taxlot_views.py
> Add Permissions to TaxlotViewViewSet

- seed/static/seed/js/controllers/new_member_modal_controller.js
- seed/static/seed/partials/new_member_modal.html
Owners can only exist in the root of the tree
brings backend error message to frontend
as an owner, try to create an owner outside of root
> Display error message on failed invite

- seed/lib/superperms/orgs/decorators.py
- seed/tests/test_ubids.py
- seed/utils/ubid.py
- seed/views/v3/ubid.py
AH permissioning for UBID endpoints
> Ah permissions/ubid view set

- seed/lib/superperms/orgs/decorators.py
> Fix upload

- seed/lib/superperms/orgs/decorators.py
- seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
- seed/static/seed/js/services/analyses_service.js
> Fix analysis bug

- seed/static/seed/js/controllers/inventory_summary_controller.js
- seed/static/seed/partials/inventory_summary.html
https://github.com/SEED-platform/seed/issues/4397
> Upgrade table

- seed/views/v3/analyses.py
> Forgo evil evil serializer

- seed/lib/superperms/orgs/models.py
- seed/tests/test_organization_access_levels.py
- seed/views/v3/access_levels.py
> Fix ali tree permissions

- seed/data_importer/tasks.py
This line is need to give better AH results. For example:
without change
with
> Fix ah import messages

- seed/static/seed/partials/sensors_upload_modal.html
- seed/utils/sensors.py
vroom vroom https://github.com/SEED-platform/seed/issues/3328
> Fix and optimize sensors

- seed/lib/superperms/orgs/models.py
> Fix column names errors

- LICENSE.md
- docs/source/conf.py
> Update copyright to 2024

- seed/static/seed/partials/inventory_detail.html
- seed/static/seed/scss/style.scss
The ALI table on inventory details page showed the access levels in random order:
Fixed to show the levels in order:
#4488
> Update ALI table on inventory details page

- seed/static/seed/partials/organization_delete_access_level_instance_modal.html
- seed/static/seed/scss/style.scss
https://github.com/SEED-platform/seed/issues/4491#event-11517720988
> Enable force ali delete

- seed/static/seed/js/controllers/portfolio_summary_controller.js
> Rename goal detail headers

- seed/static/seed/js/controllers/inventory_detail_controller.js
- seed/static/seed/js/controllers/merge_modal_controller.js
- seed/tests/api/seed_readingtools.py
- seed/tests/test_property_views.py
- seed/tests/test_taxlot_views.py
- seed/utils/match.py
- seed/utils/merge.py
- seed/views/v3/properties.py
- seed/views/v3/taxlots.py
try the merge two things in different alis?
> Disallow manual merge of records with different alis

- seed/management/commands/create_default_user.py
- seed/static/seed/js/controllers/admin_controller.js
- seed/static/seed/js/controllers/goal_editor_modal_controller.js
- seed/static/seed/js/controllers/inventory_detail_controller.js
- seed/static/seed/js/controllers/new_member_modal_controller.js
- seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
- seed/static/seed/js/controllers/portfolio_summary_controller.js
- seed/static/seed/js/seed.js
- seed/static/seed/js/services/ah_service.js
- seed/static/seed/partials/inventory_detail.html
- seed/templates/seed/_header.html
- seed/templates/seed/_scripts.html
- seed/utils/inventory_filter.py
- seed/views/v3/organization_users.py
- Fixed an AH bug in the `create_default_user` script that failed for users that did not already belong to pre-existing orgs
- Refactored ~5 duplications of `calculate_access_level_instances_by_depth` into a new ah_service
- Fixed the admin page `Add/Remove a user to an organization` form for compatibility with AH
- Fixed a related bug that prevented sending emails when adding users via this form
- Updated the admin page to make `Owner` the default role
- Fixed a few portfolio summary bugs
- Improved header Access Level spacing
- Cleanup and ESLint fixes
#4531
> Several AH bug fixes

- seed/models/tax_lot_properties.py
- seed/tests/test_analysis_pipelines.py
- seed/tests/test_columns.py
- seed/tests/test_tax_lot_property.py
more robust type checking for extra data unit conversion
> Fix unit conversion for non numeric values

- seed/static/seed/js/controllers/members_controller.js
- seed/static/seed/js/controllers/new_member_modal_controller.js
- seed/static/seed/partials/members.html
- seed/static/seed/partials/new_member_modal.html
- seed/static/seed/tests/new_member_modal_controller.spec.js
- seed/views/v3/users.py
> Disallow changing nonroot users to owner

- seed/static/seed/js/controllers/portfolio_summary_controller.js
- seed/static/seed/scss/style.scss
- removes unnecessary cellTemplate preventing cell edits 
- removes viewers ability to edit cells
- standardizes cursor style
> Fix portfolio summary editable cells

- seed/static/seed/js/controllers/insights_property_controller.js
[#4547](https://github.com/SEED-platform/seed/issues/4547)
> Fix categorical axis

- seed/analysis_pipelines/co2.py
[#4122](https://github.com/SEED-platform/seed/issues/4122)
Open
[SEED-platform](https://github.com/SEED-platform)SEED-platform
/
[seed](https://github.com/SEED-platform/seed)
> Better co2 Analysis error message

- seed/static/seed/js/controllers/inventory_list_controller.js
https://github.com/SEED-platform/seed/issues/4132
> Dont shorten lat/long

- seed/static/seed/js/controllers/inventory_list_controller.js
- seed/static/seed/js/controllers/portfolio_summary_controller.js
- seed/static/seed/scss/style.scss
https://github.com/SEED-platform/seed/assets/30241543/6917b725-ab2c-46f3-a759-fd288cd8842f
> Empty label section remains same size when toggled

- seed/views/v3/organization_users.py
From the admin page, a 500 error was occurring if the superuser attempted to select an organization under `Add/Remove a user to an organization` that the superuser wasn't a member of.
Fixes a bug that prevents superusers from listing members of an org that the superuser does not belong to.
1. Go to the admin page, `/app/#/profile/admin`
2. Under `Add/Remove a user to an organization` select an org that you do not belong to and confirm that the members are listed as expected
> Allow superusers to list all org members

- requirements/base.txt
There have been minor changes to the library.
* Sync up our version of the UBID library with PNNL and Swindler's version.
Unit tests should catch any loading issues, there are no changes to the UBID algorithm.
n/a
> Update to latest version of UBID library

- Dockerfile
- Dockerfile-dev
Node v14 reached end of life a year ago, and we're seeing warnings in our CI publish logs because Alpine 3.14 defaults to Node v14.
Updates Node from v14 to v20
The CI should pass, or you can build the docker container and launch it
> Update Node in Docker images

- seed/utils/inventory_filter.py
https://github.com/SEED-platform/seed/issues/3997
> Dont dupe inventory rows

- .github/release.yml
- .github/workflows/ci.yml
- .github/workflows/pr-labels.yml
- .github/workflows/publish.yml
- .pre-commit-config.yaml
- charts/persistentvolumes/values.yaml
- charts/seed/values.yaml
- charts/values.yaml
- seed/landing/static/landing/scss/landing.scss
- seed/static/seed/scss/style.scss
Simple update to the versions used in pre-commit. 
* There are only a few code updates for syntax
* `pre-commit run --all-files`
n/a
> Update pre-commit versions

- seed/analysis_pipelines/better/client.py
- seed/analysis_pipelines/better/pipeline.py
- seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
- vendors/package-lock.json
I couldn't get BETTER to work without these fixes..🤷‍♀️
> Better update

- seed/static/seed/js/controllers/inventory_settings_controller.js
- seed/tests/test_column_list_profiles_views.py
see [#4180](https://github.com/SEED-platform/seed/issues/4180)
> Improve Column list profile creation

- seed/models/tax_lot_properties.py
> Fix has meter indicator

- seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
https://github.com/SEED-platform/seed/issues/4668
> Fix timeline user display

- docker-compose.dev.yml
- seed/views/v3/organizations.py
> Fix reports with `None` values

- seed/data_importer/match.py
- seed/tests/test_match_existing.py
- seed/tests/test_property_views.py
- seed/tests/test_taxlot_views.py
- seed/utils/match.py
- seed/utils/ubid.py
- seed/views/properties.py
- seed/views/v3/organizations.py
- seed/views/v3/properties.py
- seed/views/v3/taxlots.py
Importing data into a large organization can take a considerable amount of time to go through the matching/merging/linking process
Optimizes several steps throughout the import process to improve performance:
When importing 512 records that will merge into an org with 512 records, _with UBID data_:
|             | **Before** | **After** |
|-------------|------------|-----------|
| **Queries** | 520        | 7         |
| **Time**    | 1m 28s     | 11s       |
When importing 5000 records that will merge into an org with 145,000 records, _without UBID data_:
|          | **Before** | **After** |
|----------|------------|-----------|
| **Time** | 26m 43s    | 15s     |
When importing 40,000 records that will merge into an org with 145,000 records, _without UBID data_:
|          | **Before** …
> Major import performance improvements

- seed/models/tax_lot_properties.py
https://github.com/SEED-platform/seed/issues/4728
> dont make non numbers numerical

- seed/tests/test_salesforce_views.py
Update Salesforce test ID and credentials to get tests running again
> Fix Salesforce Tests

- seed/audit_template/audit_template.py
Org Settings AT imports do not work on dev1 and dev2. I have been unable to recreate this issue locally.
Adds logs to task response
> Adds developer logs to AT workflow

- seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js
> Fix update display name

- seed/static/seed/js/controllers/inventory_reports_controller.js
Fixes the scatter plot chart to properly display data for non-numerical x-axis selections
Select an x-axis that is non-numerical and examine the scatterplot chart on the left.
#4733
> Fix scatter plot for non numeric x axis

- seed/views/v3/properties.py
> Fix cts export

- seed/views/v3/organizations.py
Fixes the bug whereby the organization_id is hardcoded in the axis report constructor
> Fix rollup table

- seed/views/v3/properties.py
- Use "Total of Modeled/MDMS Total Energy Usage" instead of "Sum of Modeled/MDMS Total Energy Usage"
- translate "Energy Management System Status" to a number
- correct meter exists (by correcting group by)
@laurenliz22 have I forgotten something?
> More cts fixes

- seed/data_importer/meters_parser.py
- seed/data_importer/tests/test_meters_parser.py
- seed/tests/test_meter_usage_import.py
https://github.com/SEED-platform/seed/issues/4861
> Speed up pm meters preview

- seed/views/v3/organizations.py
[#4803](https://github.com/SEED-platform/seed/issues/4803)
> Add derived columns to default reports

- seed/static/seed/js/controllers/organization_settings_controller.js
> Updated list of possible Audit Template reports in Org Settings

- seed/static/seed/js/controllers/mapping_controller.js
- seed/static/seed/js/controllers/program_setup_controller.js
Fixes a corner case bug when reviewing a previous import's mappings that can cause the page to fail to load
Replaces some lodash code with the modern ES6 equivalent
> Mapping review and line length bug fixes

- LICENSE.md
- docs/source/conf.py
> Update copyright to 2025

- seed/analysis_pipelines/upgrade_recommendation.py
> Fix  upgrade recommendation

- seed/analysis_pipelines/bsyncr.py
Meter of type Meter.ELECTRICITY was not included in this analysis. this PR adds it.
> Add meter of type Electric to BSyncR analysis

- seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
> Fix group meter interval

- seed/serializers/meters.py
- seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
- seed/tests/test_property_views.py
the property display name column now 1. works with extra data and 2. links. I wanna add a screen shot, but its army data, so, dm me i guess, @kflemin
> Fix groups meters property column

- seed/static/seed/js/controllers/inventory_reports_controller.js
> Fix report chart

- seed/static/seed/js/controllers/inventory_reports_controller.js
> Fix scatter chart ordering for all browsers

- seed/utils/v4/inventory_filter.py
- catches bug if cycle does not exist. This can happen when switching between orgs
- adds logic to handle ag grids additional filters (null for numbers)
> Fixes bug for angular grid filtering
